.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

glabel func_800C9B60
/* CA760 800C9B60 03E00008 */  jr         $ra
/* CA764 800C9B64 46006004 */   sqrt.s    $f0, $f12
/* CA768 800C9B68 00000000 */  nop
/* CA76C 800C9B6C 00000000 */  nop
