.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

glabel get_stack_pointer
/* B89A0 800B7DA0 03E00008 */  jr         $ra
/* B89A4 800B7DA4 03A01025 */   or        $v0, $sp, $zero
/* B89A8 800B7DA8 00000000 */  nop
/* B89AC 800B7DAC 00000000 */  nop
