.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel func_800C6950
/* C7550 800C6950 3C0B8013 */  lui        $t3, %hi(D_8012AB64)
/* C7554 800C6954 8D6BAB64 */  lw         $t3, %lo(D_8012AB64)($t3)
/* C7558 800C6958 3C018013 */  lui        $at, %hi(D_8012AB68)
/* C755C 800C695C AC20AB68 */  sw         $zero, %lo(D_8012AB68)($at)
/* C7560 800C6960 24080001 */  addiu      $t0, $zero, 0x1
/* C7564 800C6964 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* C7568 800C6968 3C0C800E */  lui        $t4, %hi(D_800E37F8)
/* C756C 800C696C 3C0A8013 */  lui        $t2, %hi(D_8012AB60)
/* C7570 800C6970 0168082B */  sltu       $at, $t3, $t0
/* C7574 800C6974 AFBF001C */  sw         $ra, 0x1C($sp)
/* C7578 800C6978 AFB00018 */  sw         $s0, 0x18($sp)
/* C757C 800C697C 8D8C37F8 */  lw         $t4, %lo(D_800E37F8)($t4)
/* C7580 800C6980 10200008 */  beqz       $at, .L800C69A4
/* C7584 800C6984 8D4AAB60 */   lw        $t2, %lo(D_8012AB60)($t2)
.L800C6988:
/* C7588 800C6988 91820000 */  lbu        $v0, 0x0($t4)
/* C758C 800C698C 258C0001 */  addiu      $t4, $t4, 0x1
/* C7590 800C6990 01621004 */  sllv       $v0, $v0, $t3
/* C7594 800C6994 256B0008 */  addiu      $t3, $t3, 0x8
/* C7598 800C6998 0168082A */  slt        $at, $t3, $t0
/* C759C 800C699C 1420FFFA */  bnez       $at, .L800C6988
/* C75A0 800C69A0 01425025 */   or        $t2, $t2, $v0
.L800C69A4:
/* C75A4 800C69A4 31500001 */  andi       $s0, $t2, 0x1
/* C75A8 800C69A8 010A5006 */  srlv       $t2, $t2, $t0
/* C75AC 800C69AC 01685822 */  sub        $t3, $t3, $t0 /* handwritten instruction */
/* C75B0 800C69B0 24080002 */  addiu      $t0, $zero, 0x2
/* C75B4 800C69B4 0168082B */  sltu       $at, $t3, $t0
/* C75B8 800C69B8 10200008 */  beqz       $at, .L800C69DC
/* C75BC 800C69BC 00000000 */   nop
.L800C69C0:
/* C75C0 800C69C0 91820000 */  lbu        $v0, 0x0($t4)
/* C75C4 800C69C4 258C0001 */  addiu      $t4, $t4, 0x1
/* C75C8 800C69C8 01621004 */  sllv       $v0, $v0, $t3
/* C75CC 800C69CC 256B0008 */  addiu      $t3, $t3, 0x8
/* C75D0 800C69D0 0168082A */  slt        $at, $t3, $t0
/* C75D4 800C69D4 1420FFFA */  bnez       $at, .L800C69C0
/* C75D8 800C69D8 01425025 */   or        $t2, $t2, $v0
.L800C69DC:
/* C75DC 800C69DC 3C01800E */  lui        $at, %hi(D_800E37F8)
/* C75E0 800C69E0 31490003 */  andi       $t1, $t2, 0x3
/* C75E4 800C69E4 AC2C37F8 */  sw         $t4, %lo(D_800E37F8)($at)
/* C75E8 800C69E8 010A5006 */  srlv       $t2, $t2, $t0
/* C75EC 800C69EC 3C018013 */  lui        $at, %hi(D_8012AB60)
/* C75F0 800C69F0 AC2AAB60 */  sw         $t2, %lo(D_8012AB60)($at)
/* C75F4 800C69F4 01685822 */  sub        $t3, $t3, $t0 /* handwritten instruction */
/* C75F8 800C69F8 3C018013 */  lui        $at, %hi(D_8012AB64)
/* C75FC 800C69FC AC2BAB64 */  sw         $t3, %lo(D_8012AB64)($at)
/* C7600 800C6A00 24010002 */  addiu      $at, $zero, 0x2
/* C7604 800C6A04 1121000B */  beq        $t1, $at, .L800C6A34
/* C7608 800C6A08 24010001 */   addiu     $at, $zero, 0x1
/* C760C 800C6A0C 11210005 */  beq        $t1, $at, .L800C6A24
/* C7610 800C6A10 00000000 */   nop
/* C7614 800C6A14 0C031BF1 */  jal        func_800C6FC4
/* C7618 800C6A18 00000000 */   nop
/* C761C 800C6A1C 08031A8F */  j          .L800C6A3C
/* C7620 800C6A20 00000000 */   nop
.L800C6A24:
/* C7624 800C6A24 0C031B9B */  jal        func_800C6E6C
/* C7628 800C6A28 00000000 */   nop
/* C762C 800C6A2C 08031A8F */  j          .L800C6A3C
/* C7630 800C6A30 00000000 */   nop
.L800C6A34:
/* C7634 800C6A34 0C031A95 */  jal        func_800C6A54
/* C7638 800C6A38 00000000 */   nop
.L800C6A3C:
/* C763C 800C6A3C 8FBF001C */  lw         $ra, 0x1C($sp)
/* C7640 800C6A40 24020001 */  addiu      $v0, $zero, 0x1
/* C7644 800C6A44 00501022 */  sub        $v0, $v0, $s0 /* handwritten instruction */
/* C7648 800C6A48 8FB00018 */  lw         $s0, 0x18($sp)
/* C764C 800C6A4C 03E00008 */  jr         $ra
/* C7650 800C6A50 27BD0020 */   addiu     $sp, $sp, 0x20

/* Handwritten function */
glabel func_800C6A54
/* C7654 800C6A54 27BDFAC0 */  addiu      $sp, $sp, -0x540
/* C7658 800C6A58 AFB30028 */  sw         $s3, 0x28($sp)
/* C765C 800C6A5C 3C138013 */  lui        $s3, %hi(D_8012AB64)
/* C7660 800C6A60 8E73AB64 */  lw         $s3, %lo(D_8012AB64)($s3)
/* C7664 800C6A64 AFB4002C */  sw         $s4, 0x2C($sp)
/* C7668 800C6A68 AFB20024 */  sw         $s2, 0x24($sp)
/* C766C 800C6A6C 24080005 */  addiu      $t0, $zero, 0x5
/* C7670 800C6A70 3C14800E */  lui        $s4, %hi(D_800E37F8)
/* C7674 800C6A74 3C128013 */  lui        $s2, %hi(D_8012AB60)
/* C7678 800C6A78 0268082B */  sltu       $at, $s3, $t0
/* C767C 800C6A7C AFBF0030 */  sw         $ra, 0x30($sp)
/* C7680 800C6A80 AFB10020 */  sw         $s1, 0x20($sp)
/* C7684 800C6A84 AFB0001C */  sw         $s0, 0x1C($sp)
/* C7688 800C6A88 8E9437F8 */  lw         $s4, %lo(D_800E37F8)($s4)
/* C768C 800C6A8C 10200008 */  beqz       $at, .L800C6AB0
/* C7690 800C6A90 8E52AB60 */   lw        $s2, %lo(D_8012AB60)($s2)
.L800C6A94:
/* C7694 800C6A94 92820000 */  lbu        $v0, 0x0($s4)
/* C7698 800C6A98 26940001 */  addiu      $s4, $s4, 0x1
/* C769C 800C6A9C 02621004 */  sllv       $v0, $v0, $s3
/* C76A0 800C6AA0 26730008 */  addiu      $s3, $s3, 0x8
/* C76A4 800C6AA4 0268082A */  slt        $at, $s3, $t0
/* C76A8 800C6AA8 1420FFFA */  bnez       $at, .L800C6A94
/* C76AC 800C6AAC 02429025 */   or        $s2, $s2, $v0
.L800C6AB0:
/* C76B0 800C6AB0 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C76B4 800C6AB4 3251001F */  andi       $s1, $s2, 0x1F
/* C76B8 800C6AB8 0268082B */  sltu       $at, $s3, $t0
/* C76BC 800C6ABC 26310101 */  addiu      $s1, $s1, 0x101
/* C76C0 800C6AC0 10200008 */  beqz       $at, .L800C6AE4
/* C76C4 800C6AC4 01129006 */   srlv      $s2, $s2, $t0
.L800C6AC8:
/* C76C8 800C6AC8 92820000 */  lbu        $v0, 0x0($s4)
/* C76CC 800C6ACC 26940001 */  addiu      $s4, $s4, 0x1
/* C76D0 800C6AD0 02621004 */  sllv       $v0, $v0, $s3
/* C76D4 800C6AD4 26730008 */  addiu      $s3, $s3, 0x8
/* C76D8 800C6AD8 0268082A */  slt        $at, $s3, $t0
/* C76DC 800C6ADC 1420FFFA */  bnez       $at, .L800C6AC8
/* C76E0 800C6AE0 02429025 */   or        $s2, $s2, $v0
.L800C6AE4:
/* C76E4 800C6AE4 3250001F */  andi       $s0, $s2, 0x1F
/* C76E8 800C6AE8 01129006 */  srlv       $s2, $s2, $t0
/* C76EC 800C6AEC 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C76F0 800C6AF0 24080004 */  addiu      $t0, $zero, 0x4
/* C76F4 800C6AF4 0268082B */  sltu       $at, $s3, $t0
/* C76F8 800C6AF8 10200008 */  beqz       $at, .L800C6B1C
/* C76FC 800C6AFC 26100001 */   addiu     $s0, $s0, 0x1
.L800C6B00:
/* C7700 800C6B00 92820000 */  lbu        $v0, 0x0($s4)
/* C7704 800C6B04 26940001 */  addiu      $s4, $s4, 0x1
/* C7708 800C6B08 02621004 */  sllv       $v0, $v0, $s3
/* C770C 800C6B0C 26730008 */  addiu      $s3, $s3, 0x8
/* C7710 800C6B10 0268082A */  slt        $at, $s3, $t0
/* C7714 800C6B14 1420FFFA */  bnez       $at, .L800C6B00
/* C7718 800C6B18 02429025 */   or        $s2, $s2, $v0
.L800C6B1C:
/* C771C 800C6B1C 324A000F */  andi       $t2, $s2, 0xF
/* C7720 800C6B20 254A0004 */  addiu      $t2, $t2, 0x4
/* C7724 800C6B24 3C19800F */  lui        $t9, %hi(D_800E9450)
/* C7728 800C6B28 01129006 */  srlv       $s2, $s2, $t0
/* C772C 800C6B2C 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7730 800C6B30 000A4825 */  or         $t1, $zero, $t2
/* C7734 800C6B34 27399450 */  addiu      $t9, $t9, %lo(D_800E9450)
/* C7738 800C6B38 11400019 */  beqz       $t2, .L800C6BA0
/* C773C 800C6B3C 23AF0044 */   addi      $t7, $sp, 0x44 /* handwritten instruction */
.L800C6B40:
/* C7740 800C6B40 24080003 */  addiu      $t0, $zero, 0x3
/* C7744 800C6B44 0268082B */  sltu       $at, $s3, $t0
/* C7748 800C6B48 50200009 */  beql       $at, $zero, .L800C6B70
/* C774C 800C6B4C 93230000 */   lbu       $v1, 0x0($t9)
.L800C6B50:
/* C7750 800C6B50 92820000 */  lbu        $v0, 0x0($s4)
/* C7754 800C6B54 26940001 */  addiu      $s4, $s4, 0x1
/* C7758 800C6B58 02621004 */  sllv       $v0, $v0, $s3
/* C775C 800C6B5C 26730008 */  addiu      $s3, $s3, 0x8
/* C7760 800C6B60 0268082A */  slt        $at, $s3, $t0
/* C7764 800C6B64 1420FFFA */  bnez       $at, .L800C6B50
/* C7768 800C6B68 02429025 */   or        $s2, $s2, $v0
/* C776C 800C6B6C 93230000 */  lbu        $v1, 0x0($t9)
.L800C6B70:
/* C7770 800C6B70 32420007 */  andi       $v0, $s2, 0x7
/* C7774 800C6B74 254AFFFF */  addiu      $t2, $t2, -0x1
/* C7778 800C6B78 00031880 */  sll        $v1, $v1, 2
/* C777C 800C6B7C 006F1821 */  addu       $v1, $v1, $t7
/* C7780 800C6B80 AC620000 */  sw         $v0, 0x0($v1)
/* C7784 800C6B84 01129006 */  srlv       $s2, $s2, $t0
/* C7788 800C6B88 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C778C 800C6B8C 1540FFEC */  bnez       $t2, .L800C6B40
/* C7790 800C6B90 27390001 */   addiu     $t9, $t9, 0x1
/* C7794 800C6B94 2D210013 */  sltiu      $at, $t1, 0x13
/* C7798 800C6B98 5020000A */  beql       $at, $zero, .L800C6BC4
/* C779C 800C6B9C 240D0007 */   addiu     $t5, $zero, 0x7
.L800C6BA0:
/* C77A0 800C6BA0 93230000 */  lbu        $v1, 0x0($t9)
/* C77A4 800C6BA4 25290001 */  addiu      $t1, $t1, 0x1
/* C77A8 800C6BA8 29210013 */  slti       $at, $t1, 0x13
/* C77AC 800C6BAC 00031880 */  sll        $v1, $v1, 2
/* C77B0 800C6BB0 006F1821 */  addu       $v1, $v1, $t7
/* C77B4 800C6BB4 AC600000 */  sw         $zero, 0x0($v1)
/* C77B8 800C6BB8 1420FFF9 */  bnez       $at, .L800C6BA0
/* C77BC 800C6BBC 27390001 */   addiu     $t9, $t9, 0x1
/* C77C0 800C6BC0 240D0007 */  addiu      $t5, $zero, 0x7
.L800C6BC4:
/* C77C4 800C6BC4 23A80034 */  addi       $t0, $sp, 0x34 /* handwritten instruction */
/* C77C8 800C6BC8 23A90038 */  addi       $t1, $sp, 0x38 /* handwritten instruction */
/* C77CC 800C6BCC AFAD0038 */  sw         $t5, 0x38($sp)
/* C77D0 800C6BD0 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C77D4 800C6BD4 24050013 */  addiu      $a1, $zero, 0x13
/* C77D8 800C6BD8 24060013 */  addiu      $a2, $zero, 0x13
/* C77DC 800C6BDC 24070000 */  addiu      $a3, $zero, 0x0
/* C77E0 800C6BE0 AFA00010 */  sw         $zero, 0x10($sp)
/* C77E4 800C6BE4 AFA80014 */  sw         $t0, 0x14($sp)
/* C77E8 800C6BE8 0C0318C1 */  jal        func_800C6304
/* C77EC 800C6BEC AFA90018 */   sw        $t1, 0x18($sp)
/* C77F0 800C6BF0 23A90038 */  addi       $t1, $sp, 0x38 /* handwritten instruction */
/* C77F4 800C6BF4 8D2D0000 */  lw         $t5, 0x0($t1)
/* C77F8 800C6BF8 3C02800F */  lui        $v0, %hi(D_800E951C)
/* C77FC 800C6BFC 2442951C */  addiu      $v0, $v0, %lo(D_800E951C)
/* C7800 800C6C00 000D1840 */  sll        $v1, $t5, 1
/* C7804 800C6C04 23A80034 */  addi       $t0, $sp, 0x34 /* handwritten instruction */
/* C7808 800C6C08 00431020 */  add        $v0, $v0, $v1 /* handwritten instruction */
/* C780C 800C6C0C 8D0E0000 */  lw         $t6, 0x0($t0)
/* C7810 800C6C10 0230C820 */  add        $t9, $s1, $s0 /* handwritten instruction */
/* C7814 800C6C14 84580000 */  lh         $t8, 0x0($v0)
/* C7818 800C6C18 23AF0044 */  addi       $t7, $sp, 0x44 /* handwritten instruction */
/* C781C 800C6C1C 240A0000 */  addiu      $t2, $zero, 0x0
.L800C6C20:
/* C7820 800C6C20 1320005F */  beqz       $t9, .L800C6DA0
/* C7824 800C6C24 026D082B */   sltu      $at, $s3, $t5
/* C7828 800C6C28 50200009 */  beql       $at, $zero, .L800C6C50
/* C782C 800C6C2C 02581024 */   and       $v0, $s2, $t8
.L800C6C30:
/* C7830 800C6C30 92820000 */  lbu        $v0, 0x0($s4)
/* C7834 800C6C34 26940001 */  addiu      $s4, $s4, 0x1
/* C7838 800C6C38 02621004 */  sllv       $v0, $v0, $s3
/* C783C 800C6C3C 26730008 */  addiu      $s3, $s3, 0x8
/* C7840 800C6C40 026D082A */  slt        $at, $s3, $t5
/* C7844 800C6C44 1420FFFA */  bnez       $at, .L800C6C30
/* C7848 800C6C48 02429025 */   or        $s2, $s2, $v0
/* C784C 800C6C4C 02581024 */  and        $v0, $s2, $t8
.L800C6C50:
/* C7850 800C6C50 000210C0 */  sll        $v0, $v0, 3
/* C7854 800C6C54 01C24821 */  addu       $t1, $t6, $v0
/* C7858 800C6C58 95280004 */  lhu        $t0, 0x4($t1)
/* C785C 800C6C5C 91220001 */  lbu        $v0, 0x1($t1)
/* C7860 800C6C60 29010010 */  slti       $at, $t0, 0x10
/* C7864 800C6C64 00529006 */  srlv       $s2, $s2, $v0
/* C7868 800C6C68 1420001C */  bnez       $at, .L800C6CDC
/* C786C 800C6C6C 02629822 */   sub       $s3, $s3, $v0 /* handwritten instruction */
/* C7870 800C6C70 24010010 */  addiu      $at, $zero, 0x10
/* C7874 800C6C74 1101001E */  beq        $t0, $at, .L800C6CF0
/* C7878 800C6C78 24010011 */   addiu     $at, $zero, 0x11
/* C787C 800C6C7C 51010033 */  beql       $t0, $at, .L800C6D4C
/* C7880 800C6C80 24080003 */   addiu     $t0, $zero, 0x3
/* C7884 800C6C84 24080007 */  addiu      $t0, $zero, 0x7
/* C7888 800C6C88 0268082B */  sltu       $at, $s3, $t0
/* C788C 800C6C8C 50200009 */  beql       $at, $zero, .L800C6CB4
/* C7890 800C6C90 3249007F */   andi      $t1, $s2, 0x7F
.L800C6C94:
/* C7894 800C6C94 92820000 */  lbu        $v0, 0x0($s4)
/* C7898 800C6C98 26940001 */  addiu      $s4, $s4, 0x1
/* C789C 800C6C9C 02621004 */  sllv       $v0, $v0, $s3
/* C78A0 800C6CA0 26730008 */  addiu      $s3, $s3, 0x8
/* C78A4 800C6CA4 0268082A */  slt        $at, $s3, $t0
/* C78A8 800C6CA8 1420FFFA */  bnez       $at, .L800C6C94
/* C78AC 800C6CAC 02429025 */   or        $s2, $s2, $v0
/* C78B0 800C6CB0 3249007F */  andi       $t1, $s2, 0x7F
.L800C6CB4:
/* C78B4 800C6CB4 2529000B */  addiu      $t1, $t1, 0xB
/* C78B8 800C6CB8 01129006 */  srlv       $s2, $s2, $t0
/* C78BC 800C6CBC 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C78C0 800C6CC0 0329C823 */  subu       $t9, $t9, $t1
.L800C6CC4:
/* C78C4 800C6CC4 2529FFFF */  addiu      $t1, $t1, -0x1
/* C78C8 800C6CC8 ADE00000 */  sw         $zero, 0x0($t7)
/* C78CC 800C6CCC 1520FFFD */  bnez       $t1, .L800C6CC4
/* C78D0 800C6CD0 25EF0004 */   addiu     $t7, $t7, 0x4
/* C78D4 800C6CD4 08031B08 */  j          .L800C6C20
/* C78D8 800C6CD8 240A0000 */   addiu     $t2, $zero, 0x0
.L800C6CDC:
/* C78DC 800C6CDC ADE80000 */  sw         $t0, 0x0($t7)
/* C78E0 800C6CE0 25EF0004 */  addiu      $t7, $t7, 0x4
/* C78E4 800C6CE4 2739FFFF */  addiu      $t9, $t9, -0x1
/* C78E8 800C6CE8 08031B08 */  j          .L800C6C20
/* C78EC 800C6CEC 00085025 */   or        $t2, $zero, $t0
.L800C6CF0:
/* C78F0 800C6CF0 24080002 */  addiu      $t0, $zero, 0x2
/* C78F4 800C6CF4 0268082B */  sltu       $at, $s3, $t0
/* C78F8 800C6CF8 50200009 */  beql       $at, $zero, .L800C6D20
/* C78FC 800C6CFC 32490003 */   andi      $t1, $s2, 0x3
.L800C6D00:
/* C7900 800C6D00 92820000 */  lbu        $v0, 0x0($s4)
/* C7904 800C6D04 26940001 */  addiu      $s4, $s4, 0x1
/* C7908 800C6D08 02621004 */  sllv       $v0, $v0, $s3
/* C790C 800C6D0C 26730008 */  addiu      $s3, $s3, 0x8
/* C7910 800C6D10 0268082A */  slt        $at, $s3, $t0
/* C7914 800C6D14 1420FFFA */  bnez       $at, .L800C6D00
/* C7918 800C6D18 02429025 */   or        $s2, $s2, $v0
/* C791C 800C6D1C 32490003 */  andi       $t1, $s2, 0x3
.L800C6D20:
/* C7920 800C6D20 21290003 */  addi       $t1, $t1, 0x3 /* handwritten instruction */
/* C7924 800C6D24 01129006 */  srlv       $s2, $s2, $t0
/* C7928 800C6D28 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C792C 800C6D2C 0329C823 */  subu       $t9, $t9, $t1
.L800C6D30:
/* C7930 800C6D30 2529FFFF */  addiu      $t1, $t1, -0x1
/* C7934 800C6D34 ADEA0000 */  sw         $t2, 0x0($t7)
/* C7938 800C6D38 1520FFFD */  bnez       $t1, .L800C6D30
/* C793C 800C6D3C 25EF0004 */   addiu     $t7, $t7, 0x4
/* C7940 800C6D40 08031B08 */  j          .L800C6C20
/* C7944 800C6D44 00000000 */   nop
/* C7948 800C6D48 24080003 */  addiu      $t0, $zero, 0x3
.L800C6D4C:
/* C794C 800C6D4C 0268082B */  sltu       $at, $s3, $t0
/* C7950 800C6D50 50200009 */  beql       $at, $zero, .L800C6D78
/* C7954 800C6D54 32490007 */   andi      $t1, $s2, 0x7
.L800C6D58:
/* C7958 800C6D58 92820000 */  lbu        $v0, 0x0($s4)
/* C795C 800C6D5C 26940001 */  addiu      $s4, $s4, 0x1
/* C7960 800C6D60 02621004 */  sllv       $v0, $v0, $s3
/* C7964 800C6D64 26730008 */  addiu      $s3, $s3, 0x8
/* C7968 800C6D68 0268082A */  slt        $at, $s3, $t0
/* C796C 800C6D6C 1420FFFA */  bnez       $at, .L800C6D58
/* C7970 800C6D70 02429025 */   or        $s2, $s2, $v0
/* C7974 800C6D74 32490007 */  andi       $t1, $s2, 0x7
.L800C6D78:
/* C7978 800C6D78 21290003 */  addi       $t1, $t1, 0x3 /* handwritten instruction */
/* C797C 800C6D7C 01129006 */  srlv       $s2, $s2, $t0
/* C7980 800C6D80 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7984 800C6D84 0329C823 */  subu       $t9, $t9, $t1
.L800C6D88:
/* C7988 800C6D88 2529FFFF */  addiu      $t1, $t1, -0x1
/* C798C 800C6D8C ADE00000 */  sw         $zero, 0x0($t7)
/* C7990 800C6D90 1520FFFD */  bnez       $t1, .L800C6D88
/* C7994 800C6D94 25EF0004 */   addiu     $t7, $t7, 0x4
/* C7998 800C6D98 08031B08 */  j          .L800C6C20
/* C799C 800C6D9C 240A0000 */   addiu     $t2, $zero, 0x0
.L800C6DA0:
/* C79A0 800C6DA0 3C01800E */  lui        $at, %hi(D_800E37F8)
/* C79A4 800C6DA4 AC3437F8 */  sw         $s4, %lo(D_800E37F8)($at)
/* C79A8 800C6DA8 3C018013 */  lui        $at, %hi(D_8012AB60)
/* C79AC 800C6DAC 24080009 */  addiu      $t0, $zero, 0x9
/* C79B0 800C6DB0 AC32AB60 */  sw         $s2, %lo(D_8012AB60)($at)
/* C79B4 800C6DB4 AFA80038 */  sw         $t0, 0x38($sp)
/* C79B8 800C6DB8 3C02800F */  lui        $v0, %hi(D_800E94A2)
/* C79BC 800C6DBC 3C018013 */  lui        $at, %hi(D_8012AB64)
/* C79C0 800C6DC0 3C07800F */  lui        $a3, %hi(D_800E9464)
/* C79C4 800C6DC4 244294A2 */  addiu      $v0, $v0, %lo(D_800E94A2)
/* C79C8 800C6DC8 23A30034 */  addi       $v1, $sp, 0x34 /* handwritten instruction */
/* C79CC 800C6DCC 23A80038 */  addi       $t0, $sp, 0x38 /* handwritten instruction */
/* C79D0 800C6DD0 AC33AB64 */  sw         $s3, %lo(D_8012AB64)($at)
/* C79D4 800C6DD4 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C79D8 800C6DD8 00112825 */  or         $a1, $zero, $s1
/* C79DC 800C6DDC 24060101 */  addiu      $a2, $zero, 0x101
/* C79E0 800C6DE0 24E79464 */  addiu      $a3, $a3, %lo(D_800E9464)
/* C79E4 800C6DE4 AFA20010 */  sw         $v0, 0x10($sp)
/* C79E8 800C6DE8 AFA30014 */  sw         $v1, 0x14($sp)
/* C79EC 800C6DEC 0C0318C1 */  jal        func_800C6304
/* C79F0 800C6DF0 AFA80018 */   sw        $t0, 0x18($sp)
/* C79F4 800C6DF4 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C79F8 800C6DF8 00111080 */  sll        $v0, $s1, 2
/* C79FC 800C6DFC 24080006 */  addiu      $t0, $zero, 0x6
/* C7A00 800C6E00 00822021 */  addu       $a0, $a0, $v0
/* C7A04 800C6E04 AFA80040 */  sw         $t0, 0x40($sp)
/* C7A08 800C6E08 3C02800F */  lui        $v0, %hi(D_800E94FE)
/* C7A0C 800C6E0C 3C07800F */  lui        $a3, %hi(D_800E94C2)
/* C7A10 800C6E10 244294FE */  addiu      $v0, $v0, %lo(D_800E94FE)
/* C7A14 800C6E14 23A3003C */  addi       $v1, $sp, 0x3C /* handwritten instruction */
/* C7A18 800C6E18 23A80040 */  addi       $t0, $sp, 0x40 /* handwritten instruction */
/* C7A1C 800C6E1C 00102825 */  or         $a1, $zero, $s0
/* C7A20 800C6E20 24060000 */  addiu      $a2, $zero, 0x0
/* C7A24 800C6E24 24E794C2 */  addiu      $a3, $a3, %lo(D_800E94C2)
/* C7A28 800C6E28 AFA20010 */  sw         $v0, 0x10($sp)
/* C7A2C 800C6E2C AFA30014 */  sw         $v1, 0x14($sp)
/* C7A30 800C6E30 0C0318C1 */  jal        func_800C6304
/* C7A34 800C6E34 AFA80018 */   sw        $t0, 0x18($sp)
/* C7A38 800C6E38 8FA40034 */  lw         $a0, 0x34($sp)
/* C7A3C 800C6E3C 8FA5003C */  lw         $a1, 0x3C($sp)
/* C7A40 800C6E40 8FA60038 */  lw         $a2, 0x38($sp)
/* C7A44 800C6E44 0C031C34 */  jal        func_800C70D0
/* C7A48 800C6E48 8FA70040 */   lw        $a3, 0x40($sp)
/* C7A4C 800C6E4C 8FBF0030 */  lw         $ra, 0x30($sp)
/* C7A50 800C6E50 8FB4002C */  lw         $s4, 0x2C($sp)
/* C7A54 800C6E54 8FB30028 */  lw         $s3, 0x28($sp)
/* C7A58 800C6E58 8FB20024 */  lw         $s2, 0x24($sp)
/* C7A5C 800C6E5C 8FB10020 */  lw         $s1, 0x20($sp)
/* C7A60 800C6E60 8FB0001C */  lw         $s0, 0x1C($sp)
/* C7A64 800C6E64 03E00008 */  jr         $ra
/* C7A68 800C6E68 27BD0540 */   addiu     $sp, $sp, 0x540

/* Handwritten function */
glabel func_800C6E6C
/* C7A6C 800C6E6C 27BDFAD0 */  addiu      $sp, $sp, -0x530
/* C7A70 800C6E70 AFBF001C */  sw         $ra, 0x1C($sp)
/* C7A74 800C6E74 23AB0044 */  addi       $t3, $sp, 0x44 /* handwritten instruction */
/* C7A78 800C6E78 24080024 */  addiu      $t0, $zero, 0x24
/* C7A7C 800C6E7C 24090008 */  addiu      $t1, $zero, 0x8
.L800C6E80:
/* C7A80 800C6E80 2508FFFF */  addiu      $t0, $t0, -0x1
/* C7A84 800C6E84 AD690000 */  sw         $t1, 0x0($t3)
/* C7A88 800C6E88 AD690004 */  sw         $t1, 0x4($t3)
/* C7A8C 800C6E8C AD690008 */  sw         $t1, 0x8($t3)
/* C7A90 800C6E90 AD69000C */  sw         $t1, 0xC($t3)
/* C7A94 800C6E94 1500FFFA */  bnez       $t0, .L800C6E80
/* C7A98 800C6E98 256B0010 */   addiu     $t3, $t3, 0x10
/* C7A9C 800C6E9C 2408001C */  addiu      $t0, $zero, 0x1C
/* C7AA0 800C6EA0 24090009 */  addiu      $t1, $zero, 0x9
.L800C6EA4:
/* C7AA4 800C6EA4 2508FFFF */  addiu      $t0, $t0, -0x1
/* C7AA8 800C6EA8 AD690000 */  sw         $t1, 0x0($t3)
/* C7AAC 800C6EAC AD690004 */  sw         $t1, 0x4($t3)
/* C7AB0 800C6EB0 AD690008 */  sw         $t1, 0x8($t3)
/* C7AB4 800C6EB4 AD69000C */  sw         $t1, 0xC($t3)
/* C7AB8 800C6EB8 1500FFFA */  bnez       $t0, .L800C6EA4
/* C7ABC 800C6EBC 256B0010 */   addiu     $t3, $t3, 0x10
/* C7AC0 800C6EC0 24080006 */  addiu      $t0, $zero, 0x6
/* C7AC4 800C6EC4 24090007 */  addiu      $t1, $zero, 0x7
.L800C6EC8:
/* C7AC8 800C6EC8 2508FFFF */  addiu      $t0, $t0, -0x1
/* C7ACC 800C6ECC AD690000 */  sw         $t1, 0x0($t3)
/* C7AD0 800C6ED0 AD690004 */  sw         $t1, 0x4($t3)
/* C7AD4 800C6ED4 AD690008 */  sw         $t1, 0x8($t3)
/* C7AD8 800C6ED8 AD69000C */  sw         $t1, 0xC($t3)
/* C7ADC 800C6EDC 1500FFFA */  bnez       $t0, .L800C6EC8
/* C7AE0 800C6EE0 256B0010 */   addiu     $t3, $t3, 0x10
/* C7AE4 800C6EE4 24090008 */  addiu      $t1, $zero, 0x8
/* C7AE8 800C6EE8 AD690000 */  sw         $t1, 0x0($t3)
/* C7AEC 800C6EEC AD690004 */  sw         $t1, 0x4($t3)
/* C7AF0 800C6EF0 AD690008 */  sw         $t1, 0x8($t3)
/* C7AF4 800C6EF4 AD69000C */  sw         $t1, 0xC($t3)
/* C7AF8 800C6EF8 AD690010 */  sw         $t1, 0x10($t3)
/* C7AFC 800C6EFC AD690014 */  sw         $t1, 0x14($t3)
/* C7B00 800C6F00 AD690018 */  sw         $t1, 0x18($t3)
/* C7B04 800C6F04 AD69001C */  sw         $t1, 0x1C($t3)
/* C7B08 800C6F08 24080007 */  addiu      $t0, $zero, 0x7
/* C7B0C 800C6F0C AFA80038 */  sw         $t0, 0x38($sp)
/* C7B10 800C6F10 3C02800F */  lui        $v0, %hi(D_800E94A2)
/* C7B14 800C6F14 3C07800F */  lui        $a3, %hi(D_800E9464)
/* C7B18 800C6F18 244294A2 */  addiu      $v0, $v0, %lo(D_800E94A2)
/* C7B1C 800C6F1C 23A30020 */  addi       $v1, $sp, 0x20 /* handwritten instruction */
/* C7B20 800C6F20 23A80024 */  addi       $t0, $sp, 0x24 /* handwritten instruction */
/* C7B24 800C6F24 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C7B28 800C6F28 24050120 */  addiu      $a1, $zero, 0x120
/* C7B2C 800C6F2C 24060101 */  addiu      $a2, $zero, 0x101
/* C7B30 800C6F30 24E79464 */  addiu      $a3, $a3, %lo(D_800E9464)
/* C7B34 800C6F34 AFA20010 */  sw         $v0, 0x10($sp)
/* C7B38 800C6F38 AFA30014 */  sw         $v1, 0x14($sp)
/* C7B3C 800C6F3C 0C0318C1 */  jal        func_800C6304
/* C7B40 800C6F40 AFA80018 */   sw        $t0, 0x18($sp)
/* C7B44 800C6F44 23AB0044 */  addi       $t3, $sp, 0x44 /* handwritten instruction */
/* C7B48 800C6F48 2408000A */  addiu      $t0, $zero, 0xA
/* C7B4C 800C6F4C 24090005 */  addiu      $t1, $zero, 0x5
.L800C6F50:
/* C7B50 800C6F50 2508FFFF */  addiu      $t0, $t0, -0x1
/* C7B54 800C6F54 AD690000 */  sw         $t1, 0x0($t3)
/* C7B58 800C6F58 AD690004 */  sw         $t1, 0x4($t3)
/* C7B5C 800C6F5C AD690008 */  sw         $t1, 0x8($t3)
/* C7B60 800C6F60 1500FFFB */  bnez       $t0, .L800C6F50
/* C7B64 800C6F64 256B000C */   addiu     $t3, $t3, 0xC
/* C7B68 800C6F68 3C02800F */  lui        $v0, %hi(D_800E94FE)
/* C7B6C 800C6F6C 3C07800F */  lui        $a3, %hi(D_800E94C2)
/* C7B70 800C6F70 244294FE */  addiu      $v0, $v0, %lo(D_800E94FE)
/* C7B74 800C6F74 23A30028 */  addi       $v1, $sp, 0x28 /* handwritten instruction */
/* C7B78 800C6F78 23A8002C */  addi       $t0, $sp, 0x2C /* handwritten instruction */
/* C7B7C 800C6F7C AFA90040 */  sw         $t1, 0x40($sp)
/* C7B80 800C6F80 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C7B84 800C6F84 2405001E */  addiu      $a1, $zero, 0x1E
/* C7B88 800C6F88 24060000 */  addiu      $a2, $zero, 0x0
/* C7B8C 800C6F8C 24E794C2 */  addiu      $a3, $a3, %lo(D_800E94C2)
/* C7B90 800C6F90 AFA20010 */  sw         $v0, 0x10($sp)
/* C7B94 800C6F94 AFA30014 */  sw         $v1, 0x14($sp)
/* C7B98 800C6F98 0C0318C1 */  jal        func_800C6304
/* C7B9C 800C6F9C AFA80018 */   sw        $t0, 0x18($sp)
/* C7BA0 800C6FA0 8FA40020 */  lw         $a0, 0x20($sp)
/* C7BA4 800C6FA4 8FA50028 */  lw         $a1, 0x28($sp)
/* C7BA8 800C6FA8 8FA60024 */  lw         $a2, 0x24($sp)
/* C7BAC 800C6FAC 0C031C34 */  jal        func_800C70D0
/* C7BB0 800C6FB0 8FA7002C */   lw        $a3, 0x2C($sp)
/* C7BB4 800C6FB4 8FBF001C */  lw         $ra, 0x1C($sp)
/* C7BB8 800C6FB8 27BD0530 */  addiu      $sp, $sp, 0x530
/* C7BBC 800C6FBC 03E00008 */  jr         $ra
/* C7BC0 800C6FC0 00000000 */   nop

/* Handwritten function */
glabel func_800C6FC4
/* C7BC4 800C6FC4 3C0D8013 */  lui        $t5, %hi(D_8012AB64)
/* C7BC8 800C6FC8 8DADAB64 */  lw         $t5, %lo(D_8012AB64)($t5)
/* C7BCC 800C6FCC 3C0C8013 */  lui        $t4, %hi(D_8012AB60)
/* C7BD0 800C6FD0 8D8CAB60 */  lw         $t4, %lo(D_8012AB60)($t4)
/* C7BD4 800C6FD4 31A80007 */  andi       $t0, $t5, 0x7
/* C7BD8 800C6FD8 01A86822 */  sub        $t5, $t5, $t0 /* handwritten instruction */
/* C7BDC 800C6FDC 010C6006 */  srlv       $t4, $t4, $t0
/* C7BE0 800C6FE0 24080010 */  addiu      $t0, $zero, 0x10
/* C7BE4 800C6FE4 3C0F800E */  lui        $t7, %hi(D_800E37F8)
/* C7BE8 800C6FE8 3C0E800E */  lui        $t6, %hi(D_800E37FC)
/* C7BEC 800C6FEC 01A8082B */  sltu       $at, $t5, $t0
/* C7BF0 800C6FF0 8DEF37F8 */  lw         $t7, %lo(D_800E37F8)($t7)
/* C7BF4 800C6FF4 10200008 */  beqz       $at, .L800C7018
/* C7BF8 800C6FF8 8DCE37FC */   lw        $t6, %lo(D_800E37FC)($t6)
.L800C6FFC:
/* C7BFC 800C6FFC 91E20000 */  lbu        $v0, 0x0($t7)
/* C7C00 800C7000 25EF0001 */  addiu      $t7, $t7, 0x1
/* C7C04 800C7004 01A21004 */  sllv       $v0, $v0, $t5
/* C7C08 800C7008 25AD0008 */  addiu      $t5, $t5, 0x8
/* C7C0C 800C700C 01A8082A */  slt        $at, $t5, $t0
/* C7C10 800C7010 1420FFFA */  bnez       $at, .L800C6FFC
/* C7C14 800C7014 01826025 */   or        $t4, $t4, $v0
.L800C7018:
/* C7C18 800C7018 01A86822 */  sub        $t5, $t5, $t0 /* handwritten instruction */
/* C7C1C 800C701C 3189FFFF */  andi       $t1, $t4, 0xFFFF
/* C7C20 800C7020 01A8082B */  sltu       $at, $t5, $t0
/* C7C24 800C7024 10200008 */  beqz       $at, .L800C7048
/* C7C28 800C7028 010C6006 */   srlv      $t4, $t4, $t0
.L800C702C:
/* C7C2C 800C702C 91E20000 */  lbu        $v0, 0x0($t7)
/* C7C30 800C7030 25EF0001 */  addiu      $t7, $t7, 0x1
/* C7C34 800C7034 01A21004 */  sllv       $v0, $v0, $t5
/* C7C38 800C7038 25AD0008 */  addiu      $t5, $t5, 0x8
/* C7C3C 800C703C 01A8082A */  slt        $at, $t5, $t0
/* C7C40 800C7040 1420FFFA */  bnez       $at, .L800C702C
/* C7C44 800C7044 01826025 */   or        $t4, $t4, $v0
.L800C7048:
/* C7C48 800C7048 31220003 */  andi       $v0, $t1, 0x3
/* C7C4C 800C704C 010C6006 */  srlv       $t4, $t4, $t0
/* C7C50 800C7050 1040000A */  beqz       $v0, .L800C707C
/* C7C54 800C7054 01A86822 */   sub       $t5, $t5, $t0 /* handwritten instruction */
/* C7C58 800C7058 01224822 */  sub        $t1, $t1, $v0 /* handwritten instruction */
.L800C705C:
/* C7C5C 800C705C 91EA0000 */  lbu        $t2, 0x0($t7)
/* C7C60 800C7060 2042FFFF */  addi       $v0, $v0, -0x1 /* handwritten instruction */
/* C7C64 800C7064 21EF0001 */  addi       $t7, $t7, 0x1 /* handwritten instruction */
/* C7C68 800C7068 21CE0001 */  addi       $t6, $t6, 0x1 /* handwritten instruction */
/* C7C6C 800C706C 1440FFFB */  bnez       $v0, .L800C705C
/* C7C70 800C7070 A1CAFFFF */   sb        $t2, -0x1($t6)
/* C7C74 800C7074 1120000D */  beqz       $t1, .L800C70AC
/* C7C78 800C7078 00000000 */   nop
.L800C707C:
/* C7C7C 800C707C 91E20000 */  lbu        $v0, 0x0($t7)
/* C7C80 800C7080 2529FFFC */  addiu      $t1, $t1, -0x4
/* C7C84 800C7084 25EF0004 */  addiu      $t7, $t7, 0x4
/* C7C88 800C7088 A1C20000 */  sb         $v0, 0x0($t6)
/* C7C8C 800C708C 91E3FFFD */  lbu        $v1, -0x3($t7)
/* C7C90 800C7090 25CE0004 */  addiu      $t6, $t6, 0x4
/* C7C94 800C7094 A1C3FFFD */  sb         $v1, -0x3($t6)
/* C7C98 800C7098 91EAFFFE */  lbu        $t2, -0x2($t7)
/* C7C9C 800C709C A1CAFFFE */  sb         $t2, -0x2($t6)
/* C7CA0 800C70A0 91EBFFFF */  lbu        $t3, -0x1($t7)
/* C7CA4 800C70A4 1520FFF5 */  bnez       $t1, .L800C707C
/* C7CA8 800C70A8 A1CBFFFF */   sb        $t3, -0x1($t6)
.L800C70AC:
/* C7CAC 800C70AC 3C01800E */  lui        $at, %hi(D_800E37F8)
/* C7CB0 800C70B0 AC2F37F8 */  sw         $t7, %lo(D_800E37F8)($at)
/* C7CB4 800C70B4 3C01800E */  lui        $at, %hi(D_800E37FC)
/* C7CB8 800C70B8 AC2E37FC */  sw         $t6, %lo(D_800E37FC)($at)
/* C7CBC 800C70BC 3C018013 */  lui        $at, %hi(D_8012AB60)
/* C7CC0 800C70C0 AC2CAB60 */  sw         $t4, %lo(D_8012AB60)($at)
/* C7CC4 800C70C4 3C018013 */  lui        $at, %hi(D_8012AB64)
/* C7CC8 800C70C8 03E00008 */  jr         $ra
/* C7CCC 800C70CC AC2DAB64 */   sw        $t5, %lo(D_8012AB64)($at)

/* Handwritten function */
glabel func_800C70D0
/* C7CD0 800C70D0 27BDFFF0 */  addiu      $sp, $sp, -0x10
/* C7CD4 800C70D4 3C0B800F */  lui        $t3, %hi(D_800E951C)
/* C7CD8 800C70D8 AFB20008 */  sw         $s2, 0x8($sp)
/* C7CDC 800C70DC AFB10004 */  sw         $s1, 0x4($sp)
/* C7CE0 800C70E0 AFB00000 */  sw         $s0, 0x0($sp)
/* C7CE4 800C70E4 256B951C */  addiu      $t3, $t3, %lo(D_800E951C)
/* C7CE8 800C70E8 00061040 */  sll        $v0, $a2, 1
/* C7CEC 800C70EC 00074040 */  sll        $t0, $a3, 1
/* C7CF0 800C70F0 3C12800E */  lui        $s2, %hi(D_800E37F8)
/* C7CF4 800C70F4 3C11800E */  lui        $s1, %hi(D_800E37FC)
/* C7CF8 800C70F8 3C198013 */  lui        $t9, %hi(D_8012AB60)
/* C7CFC 800C70FC 3C108013 */  lui        $s0, %hi(D_8012AB64)
/* C7D00 800C7100 01621821 */  addu       $v1, $t3, $v0
/* C7D04 800C7104 01684821 */  addu       $t1, $t3, $t0
/* C7D08 800C7108 8E5237F8 */  lw         $s2, %lo(D_800E37F8)($s2)
/* C7D0C 800C710C 8E3137FC */  lw         $s1, %lo(D_800E37FC)($s1)
/* C7D10 800C7110 8F39AB60 */  lw         $t9, %lo(D_8012AB60)($t9)
/* C7D14 800C7114 8E10AB64 */  lw         $s0, %lo(D_8012AB64)($s0)
/* C7D18 800C7118 946D0000 */  lhu        $t5, 0x0($v1)
/* C7D1C 800C711C 952C0000 */  lhu        $t4, 0x0($t1)
.L800C7120:
/* C7D20 800C7120 0206082B */  sltu       $at, $s0, $a2
.L800C7124:
/* C7D24 800C7124 50200009 */  beql       $at, $zero, .L800C714C
/* C7D28 800C7128 032D1024 */   and       $v0, $t9, $t5
.L800C712C:
/* C7D2C 800C712C 92420000 */  lbu        $v0, 0x0($s2)
/* C7D30 800C7130 26520001 */  addiu      $s2, $s2, 0x1
/* C7D34 800C7134 02021004 */  sllv       $v0, $v0, $s0
/* C7D38 800C7138 26100008 */  addiu      $s0, $s0, 0x8
/* C7D3C 800C713C 0206082A */  slt        $at, $s0, $a2
/* C7D40 800C7140 1420FFFA */  bnez       $at, .L800C712C
/* C7D44 800C7144 0322C825 */   or        $t9, $t9, $v0
/* C7D48 800C7148 032D1024 */  and        $v0, $t9, $t5
.L800C714C:
/* C7D4C 800C714C 000210C0 */  sll        $v0, $v0, 3
/* C7D50 800C7150 00827821 */  addu       $t7, $a0, $v0
/* C7D54 800C7154 91F80000 */  lbu        $t8, 0x0($t7)
/* C7D58 800C7158 2B010011 */  slti       $at, $t8, 0x11
/* C7D5C 800C715C 5420001A */  bnel       $at, $zero, .L800C71C8
/* C7D60 800C7160 91E20001 */   lbu       $v0, 0x1($t7)
/* C7D64 800C7164 81E30001 */  lb         $v1, 0x1($t7)
.L800C7168:
/* C7D68 800C7168 2318FFF0 */  addi       $t8, $t8, -0x10 /* handwritten instruction */
/* C7D6C 800C716C 02038022 */  sub        $s0, $s0, $v1 /* handwritten instruction */
/* C7D70 800C7170 0218082B */  sltu       $at, $s0, $t8
/* C7D74 800C7174 10200008 */  beqz       $at, .L800C7198
/* C7D78 800C7178 0079C806 */   srlv      $t9, $t9, $v1
.L800C717C:
/* C7D7C 800C717C 92420000 */  lbu        $v0, 0x0($s2)
/* C7D80 800C7180 26520001 */  addiu      $s2, $s2, 0x1
/* C7D84 800C7184 02021004 */  sllv       $v0, $v0, $s0
/* C7D88 800C7188 26100008 */  addiu      $s0, $s0, 0x8
/* C7D8C 800C718C 0218082A */  slt        $at, $s0, $t8
/* C7D90 800C7190 1420FFFA */  bnez       $at, .L800C717C
/* C7D94 800C7194 0322C825 */   or        $t9, $t9, $v0
.L800C7198:
/* C7D98 800C7198 00181040 */  sll        $v0, $t8, 1
/* C7D9C 800C719C 004B1021 */  addu       $v0, $v0, $t3
/* C7DA0 800C71A0 94490000 */  lhu        $t1, 0x0($v0)
/* C7DA4 800C71A4 8DE80004 */  lw         $t0, 0x4($t7)
/* C7DA8 800C71A8 01394824 */  and        $t1, $t1, $t9
/* C7DAC 800C71AC 000948C0 */  sll        $t1, $t1, 3
/* C7DB0 800C71B0 01097820 */  add        $t7, $t0, $t1 /* handwritten instruction */
/* C7DB4 800C71B4 91F80000 */  lbu        $t8, 0x0($t7)
/* C7DB8 800C71B8 2F010011 */  sltiu      $at, $t8, 0x11
/* C7DBC 800C71BC 5020FFEA */  beql       $at, $zero, .L800C7168
/* C7DC0 800C71C0 81E30001 */   lb        $v1, 0x1($t7)
/* C7DC4 800C71C4 91E20001 */  lbu        $v0, 0x1($t7)
.L800C71C8:
/* C7DC8 800C71C8 24010010 */  addiu      $at, $zero, 0x10
/* C7DCC 800C71CC 0059C806 */  srlv       $t9, $t9, $v0
/* C7DD0 800C71D0 17010005 */  bne        $t8, $at, .L800C71E8
/* C7DD4 800C71D4 02028022 */   sub       $s0, $s0, $v0 /* handwritten instruction */
/* C7DD8 800C71D8 95E20004 */  lhu        $v0, 0x4($t7)
/* C7DDC 800C71DC 26310001 */  addiu      $s1, $s1, 0x1
/* C7DE0 800C71E0 08031C48 */  j          .L800C7120
/* C7DE4 800C71E4 A222FFFF */   sb        $v0, -0x1($s1)
.L800C71E8:
/* C7DE8 800C71E8 2401000F */  addiu      $at, $zero, 0xF
/* C7DEC 800C71EC 13010068 */  beq        $t8, $at, .L800C7390
/* C7DF0 800C71F0 0218082B */   sltu      $at, $s0, $t8
/* C7DF4 800C71F4 50200009 */  beql       $at, $zero, .L800C721C
/* C7DF8 800C71F8 00181040 */   sll       $v0, $t8, 1
.L800C71FC:
/* C7DFC 800C71FC 92420000 */  lbu        $v0, 0x0($s2)
/* C7E00 800C7200 26520001 */  addiu      $s2, $s2, 0x1
/* C7E04 800C7204 02021004 */  sllv       $v0, $v0, $s0
/* C7E08 800C7208 26100008 */  addiu      $s0, $s0, 0x8
/* C7E0C 800C720C 0218082A */  slt        $at, $s0, $t8
/* C7E10 800C7210 1420FFFA */  bnez       $at, .L800C71FC
/* C7E14 800C7214 0322C825 */   or        $t9, $t9, $v0
/* C7E18 800C7218 00181040 */  sll        $v0, $t8, 1
.L800C721C:
/* C7E1C 800C721C 004B1021 */  addu       $v0, $v0, $t3
/* C7E20 800C7220 94490000 */  lhu        $t1, 0x0($v0)
/* C7E24 800C7224 95E80004 */  lhu        $t0, 0x4($t7)
/* C7E28 800C7228 02188022 */  sub        $s0, $s0, $t8 /* handwritten instruction */
/* C7E2C 800C722C 0207082B */  sltu       $at, $s0, $a3
/* C7E30 800C7230 01394824 */  and        $t1, $t1, $t9
/* C7E34 800C7234 0319C806 */  srlv       $t9, $t9, $t8
/* C7E38 800C7238 10200008 */  beqz       $at, .L800C725C
/* C7E3C 800C723C 01097021 */   addu      $t6, $t0, $t1
.L800C7240:
/* C7E40 800C7240 92420000 */  lbu        $v0, 0x0($s2)
/* C7E44 800C7244 26520001 */  addiu      $s2, $s2, 0x1
/* C7E48 800C7248 02021004 */  sllv       $v0, $v0, $s0
/* C7E4C 800C724C 26100008 */  addiu      $s0, $s0, 0x8
/* C7E50 800C7250 0207082A */  slt        $at, $s0, $a3
/* C7E54 800C7254 1420FFFA */  bnez       $at, .L800C7240
/* C7E58 800C7258 0322C825 */   or        $t9, $t9, $v0
.L800C725C:
/* C7E5C 800C725C 01991024 */  and        $v0, $t4, $t9
/* C7E60 800C7260 000210C0 */  sll        $v0, $v0, 3
/* C7E64 800C7264 00A27821 */  addu       $t7, $a1, $v0
/* C7E68 800C7268 91F80000 */  lbu        $t8, 0x0($t7)
/* C7E6C 800C726C 2B010011 */  slti       $at, $t8, 0x11
/* C7E70 800C7270 5420001A */  bnel       $at, $zero, .L800C72DC
/* C7E74 800C7274 91E20001 */   lbu       $v0, 0x1($t7)
/* C7E78 800C7278 91E80001 */  lbu        $t0, 0x1($t7)
.L800C727C:
/* C7E7C 800C727C 2318FFF0 */  addi       $t8, $t8, -0x10 /* handwritten instruction */
/* C7E80 800C7280 02088022 */  sub        $s0, $s0, $t0 /* handwritten instruction */
/* C7E84 800C7284 0218082B */  sltu       $at, $s0, $t8
/* C7E88 800C7288 10200008 */  beqz       $at, .L800C72AC
/* C7E8C 800C728C 0119C806 */   srlv      $t9, $t9, $t0
.L800C7290:
/* C7E90 800C7290 92420000 */  lbu        $v0, 0x0($s2)
/* C7E94 800C7294 26520001 */  addiu      $s2, $s2, 0x1
/* C7E98 800C7298 02021004 */  sllv       $v0, $v0, $s0
/* C7E9C 800C729C 26100008 */  addiu      $s0, $s0, 0x8
/* C7EA0 800C72A0 0218082A */  slt        $at, $s0, $t8
/* C7EA4 800C72A4 1420FFFA */  bnez       $at, .L800C7290
/* C7EA8 800C72A8 0322C825 */   or        $t9, $t9, $v0
.L800C72AC:
/* C7EAC 800C72AC 00181040 */  sll        $v0, $t8, 1
/* C7EB0 800C72B0 004B1021 */  addu       $v0, $v0, $t3
/* C7EB4 800C72B4 94490000 */  lhu        $t1, 0x0($v0)
/* C7EB8 800C72B8 8DE80004 */  lw         $t0, 0x4($t7)
/* C7EBC 800C72BC 01394824 */  and        $t1, $t1, $t9
/* C7EC0 800C72C0 000948C0 */  sll        $t1, $t1, 3
/* C7EC4 800C72C4 01097821 */  addu       $t7, $t0, $t1
/* C7EC8 800C72C8 91F80000 */  lbu        $t8, 0x0($t7)
/* C7ECC 800C72CC 2F010011 */  sltiu      $at, $t8, 0x11
/* C7ED0 800C72D0 5020FFEA */  beql       $at, $zero, .L800C727C
/* C7ED4 800C72D4 91E80001 */   lbu       $t0, 0x1($t7)
/* C7ED8 800C72D8 91E20001 */  lbu        $v0, 0x1($t7)
.L800C72DC:
/* C7EDC 800C72DC 02028022 */  sub        $s0, $s0, $v0 /* handwritten instruction */
/* C7EE0 800C72E0 0218082B */  sltu       $at, $s0, $t8
/* C7EE4 800C72E4 10200008 */  beqz       $at, .L800C7308
/* C7EE8 800C72E8 0059C806 */   srlv      $t9, $t9, $v0
.L800C72EC:
/* C7EEC 800C72EC 92420000 */  lbu        $v0, 0x0($s2)
/* C7EF0 800C72F0 26520001 */  addiu      $s2, $s2, 0x1
/* C7EF4 800C72F4 02021004 */  sllv       $v0, $v0, $s0
/* C7EF8 800C72F8 26100008 */  addiu      $s0, $s0, 0x8
/* C7EFC 800C72FC 0218082A */  slt        $at, $s0, $t8
/* C7F00 800C7300 1420FFFA */  bnez       $at, .L800C72EC
/* C7F04 800C7304 0322C825 */   or        $t9, $t9, $v0
.L800C7308:
/* C7F08 800C7308 00181040 */  sll        $v0, $t8, 1
/* C7F0C 800C730C 004B1021 */  addu       $v0, $v0, $t3
/* C7F10 800C7310 94490000 */  lhu        $t1, 0x0($v0)
/* C7F14 800C7314 95E30004 */  lhu        $v1, 0x4($t7)
/* C7F18 800C7318 31C20003 */  andi       $v0, $t6, 0x3
/* C7F1C 800C731C 01394824 */  and        $t1, $t1, $t9
/* C7F20 800C7320 02234022 */  sub        $t0, $s1, $v1 /* handwritten instruction */
/* C7F24 800C7324 01094022 */  sub        $t0, $t0, $t1 /* handwritten instruction */
/* C7F28 800C7328 0319C806 */  srlv       $t9, $t9, $t8
/* C7F2C 800C732C 1040000A */  beqz       $v0, .L800C7358
/* C7F30 800C7330 02188022 */   sub       $s0, $s0, $t8 /* handwritten instruction */
/* C7F34 800C7334 01C27022 */  sub        $t6, $t6, $v0 /* handwritten instruction */
.L800C7338:
/* C7F38 800C7338 910A0000 */  lbu        $t2, 0x0($t0)
/* C7F3C 800C733C 2042FFFF */  addi       $v0, $v0, -0x1 /* handwritten instruction */
/* C7F40 800C7340 21080001 */  addi       $t0, $t0, 0x1 /* handwritten instruction */
/* C7F44 800C7344 22310001 */  addi       $s1, $s1, 0x1 /* handwritten instruction */
/* C7F48 800C7348 1440FFFB */  bnez       $v0, .L800C7338
/* C7F4C 800C734C A22AFFFF */   sb        $t2, -0x1($s1)
/* C7F50 800C7350 51C0FF74 */  beql       $t6, $zero, .L800C7124
/* C7F54 800C7354 0206082B */   sltu      $at, $s0, $a2
.L800C7358:
/* C7F58 800C7358 91020000 */  lbu        $v0, 0x0($t0)
/* C7F5C 800C735C 25CEFFFC */  addiu      $t6, $t6, -0x4
/* C7F60 800C7360 25080004 */  addiu      $t0, $t0, 0x4
/* C7F64 800C7364 A2220000 */  sb         $v0, 0x0($s1)
/* C7F68 800C7368 9103FFFD */  lbu        $v1, -0x3($t0)
/* C7F6C 800C736C 26310004 */  addiu      $s1, $s1, 0x4
/* C7F70 800C7370 A223FFFD */  sb         $v1, -0x3($s1)
/* C7F74 800C7374 9109FFFE */  lbu        $t1, -0x2($t0)
/* C7F78 800C7378 A229FFFE */  sb         $t1, -0x2($s1)
/* C7F7C 800C737C 910AFFFF */  lbu        $t2, -0x1($t0)
/* C7F80 800C7380 15C0FFF5 */  bnez       $t6, .L800C7358
/* C7F84 800C7384 A22AFFFF */   sb        $t2, -0x1($s1)
/* C7F88 800C7388 08031C48 */  j          .L800C7120
/* C7F8C 800C738C 00000000 */   nop
.L800C7390:
/* C7F90 800C7390 3C01800E */  lui        $at, %hi(D_800E37F8)
/* C7F94 800C7394 AC3237F8 */  sw         $s2, %lo(D_800E37F8)($at)
/* C7F98 800C7398 3C01800E */  lui        $at, %hi(D_800E37FC)
/* C7F9C 800C739C AC3137FC */  sw         $s1, %lo(D_800E37FC)($at)
/* C7FA0 800C73A0 3C018013 */  lui        $at, %hi(D_8012AB60)
/* C7FA4 800C73A4 AC39AB60 */  sw         $t9, %lo(D_8012AB60)($at)
/* C7FA8 800C73A8 3C018013 */  lui        $at, %hi(D_8012AB64)
/* C7FAC 800C73AC AC30AB64 */  sw         $s0, %lo(D_8012AB64)($at)
/* C7FB0 800C73B0 8FB20008 */  lw         $s2, 0x8($sp)
/* C7FB4 800C73B4 8FB10004 */  lw         $s1, 0x4($sp)
/* C7FB8 800C73B8 8FB00000 */  lw         $s0, 0x0($sp)
/* C7FBC 800C73BC 03E00008 */  jr         $ra
/* C7FC0 800C73C0 27BD0010 */   addiu     $sp, $sp, 0x10
/* C7FC4 800C73C4 00000000 */  nop
/* C7FC8 800C73C8 00000000 */  nop
/* C7FCC 800C73CC 00000000 */  nop
