.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel disable_interrupts
/* 70110 8006F510 3C08800E */  lui        $t0, %hi(gIntDisFlag)
/* 70114 8006F514 8108D4C0 */  lb         $t0, %lo(gIntDisFlag)($t0)
/* 70118 8006F518 11000006 */  beqz       $t0, .L8006F534
/* 7011C 8006F51C 40086000 */   mfc0      $t0, $12 /* handwritten instruction */
/* 70120 8006F520 2401FFFE */  addiu      $at, $zero, -0x2
/* 70124 8006F524 01014824 */  and        $t1, $t0, $at
/* 70128 8006F528 40896000 */  mtc0       $t1, $12 /* handwritten instruction */
/* 7012C 8006F52C 31020001 */  andi       $v0, $t0, 0x1
/* 70130 8006F530 00000000 */  nop
.L8006F534:
/* 70134 8006F534 03E00008 */  jr         $ra
/* 70138 8006F538 00000000 */   nop

/* Handwritten function */
glabel enable_interrupts
/* 7013C 8006F53C 3C08800E */  lui        $t0, %hi(gIntDisFlag)
/* 70140 8006F540 8108D4C0 */  lb         $t0, %lo(gIntDisFlag)($t0)
/* 70144 8006F544 11000005 */  beqz       $t0, .L8006F55C
/* 70148 8006F548 40086000 */   mfc0      $t0, $12 /* handwritten instruction */
/* 7014C 8006F54C 01044025 */  or         $t0, $t0, $a0
/* 70150 8006F550 40886000 */  mtc0       $t0, $12 /* handwritten instruction */
/* 70154 8006F554 00000000 */  nop
/* 70158 8006F558 00000000 */  nop
.L8006F55C:
/* 7015C 8006F55C 03E00008 */  jr         $ra
/* 70160 8006F560 00000000 */   nop

glabel set_gIntDisFlag
/* 70164 8006F564 3C01800E */  lui        $at, %hi(gIntDisFlag)
/* 70168 8006F568 03E00008 */  jr         $ra
/* 7016C 8006F56C A024D4C0 */   sb        $a0, %lo(gIntDisFlag)($at)

glabel get_gIntDisFlag
/* 70170 8006F570 3C02800E */  lui        $v0, %hi(gIntDisFlag)
/* 70174 8006F574 03E00008 */  jr         $ra
/* 70178 8006F578 9042D4C0 */   lbu       $v0, %lo(gIntDisFlag)($v0)

/* Handwritten function */
glabel s32_matrix_to_s16_matrix
/* 7017C 8006F57C 34080004 */  ori        $t0, $zero, 0x4
/* 70180 8006F580 3C0FFFFF */  lui        $t7, (0xFFFF0000 >> 16)
.L8006F584:
/* 70184 8006F584 8C890000 */  lw         $t1, 0x0($a0)
/* 70188 8006F588 8C8A0020 */  lw         $t2, 0x20($a0)
/* 7018C 8006F58C 8C8B0004 */  lw         $t3, 0x4($a0)
/* 70190 8006F590 8C8C0024 */  lw         $t4, 0x24($a0)
/* 70194 8006F594 A4A90004 */  sh         $t1, 0x4($a1)
/* 70198 8006F598 A4AA0006 */  sh         $t2, 0x6($a1)
/* 7019C 8006F59C A4AB000C */  sh         $t3, 0xC($a1)
/* 701A0 8006F5A0 A4AC000E */  sh         $t4, 0xE($a1)
/* 701A4 8006F5A4 00094C02 */  srl        $t1, $t1, 16
/* 701A8 8006F5A8 000A5402 */  srl        $t2, $t2, 16
/* 701AC 8006F5AC 000B5C02 */  srl        $t3, $t3, 16
/* 701B0 8006F5B0 000C6402 */  srl        $t4, $t4, 16
/* 701B4 8006F5B4 24840008 */  addiu      $a0, $a0, 0x8
/* 701B8 8006F5B8 A4A90000 */  sh         $t1, 0x0($a1)
/* 701BC 8006F5BC A4AA0002 */  sh         $t2, 0x2($a1)
/* 701C0 8006F5C0 A4AB0008 */  sh         $t3, 0x8($a1)
/* 701C4 8006F5C4 A4AC000A */  sh         $t4, 0xA($a1)
/* 701C8 8006F5C8 20A50010 */  addi       $a1, $a1, 0x10 /* handwritten instruction */
/* 701CC 8006F5CC 2508FFFF */  addiu      $t0, $t0, -0x1
/* 701D0 8006F5D0 5500FFEC */  bnel       $t0, $zero, .L8006F584
/* 701D4 8006F5D4 00000000 */   nop
/* 701D8 8006F5D8 03E00008 */  jr         $ra
/* 701DC 8006F5DC 00000000 */   nop

glabel f32_matrix_to_s32_matrix
/* 701E0 8006F5E0 3C014780 */  lui        $at, (0x47800000 >> 16)
/* 701E4 8006F5E4 44816000 */  mtc1       $at, $f12
/* 701E8 8006F5E8 34080004 */  ori        $t0, $zero, 0x4
.L8006F5EC:
/* 701EC 8006F5EC C4840000 */  lwc1       $f4, 0x0($a0)
/* 701F0 8006F5F0 C4860004 */  lwc1       $f6, 0x4($a0)
/* 701F4 8006F5F4 C4880008 */  lwc1       $f8, 0x8($a0)
/* 701F8 8006F5F8 460C2102 */  mul.s      $f4, $f4, $f12
/* 701FC 8006F5FC C48A000C */  lwc1       $f10, 0xC($a0)
/* 70200 8006F600 24840010 */  addiu      $a0, $a0, 0x10
/* 70204 8006F604 460C3182 */  mul.s      $f6, $f6, $f12
/* 70208 8006F608 2508FFFF */  addiu      $t0, $t0, -0x1
/* 7020C 8006F60C 24A50010 */  addiu      $a1, $a1, 0x10
/* 70210 8006F610 460C4202 */  mul.s      $f8, $f8, $f12
/* 70214 8006F614 00000000 */  nop
/* 70218 8006F618 460C5282 */  mul.s      $f10, $f10, $f12
/* 7021C 8006F61C 4600210D */  trunc.w.s  $f4, $f4
/* 70220 8006F620 4600318D */  trunc.w.s  $f6, $f6
/* 70224 8006F624 E4A4FFF0 */  swc1       $f4, -0x10($a1)
/* 70228 8006F628 4600420D */  trunc.w.s  $f8, $f8
/* 7022C 8006F62C E4A6FFF4 */  swc1       $f6, -0xC($a1)
/* 70230 8006F630 4600528D */  trunc.w.s  $f10, $f10
/* 70234 8006F634 E4A8FFF8 */  swc1       $f8, -0x8($a1)
/* 70238 8006F638 E4AAFFFC */  swc1       $f10, -0x4($a1)
/* 7023C 8006F63C 5500FFEB */  bnel       $t0, $zero, .L8006F5EC
/* 70240 8006F640 00000000 */   nop
/* 70244 8006F644 03E00008 */  jr         $ra
/* 70248 8006F648 00000000 */   nop

glabel guMtxXFMF
/* 7024C 8006F64C 44856000 */  mtc1       $a1, $f12
/* 70250 8006F650 C4840000 */  lwc1       $f4, 0x0($a0)
/* 70254 8006F654 44867000 */  mtc1       $a2, $f14
/* 70258 8006F658 C4880010 */  lwc1       $f8, 0x10($a0)
/* 7025C 8006F65C 460C2182 */  mul.s      $f6, $f4, $f12
/* 70260 8006F660 44878000 */  mtc1       $a3, $f16
/* 70264 8006F664 C4840020 */  lwc1       $f4, 0x20($a0)
/* 70268 8006F668 460E4282 */  mul.s      $f10, $f8, $f14
/* 7026C 8006F66C 8FAE0010 */  lw         $t6, 0x10($sp)
/* 70270 8006F670 46102202 */  mul.s      $f8, $f4, $f16
/* 70274 8006F674 460A3480 */  add.s      $f18, $f6, $f10
/* 70278 8006F678 C48A0030 */  lwc1       $f10, 0x30($a0)
/* 7027C 8006F67C 46089180 */  add.s      $f6, $f18, $f8
/* 70280 8006F680 46065100 */  add.s      $f4, $f10, $f6
/* 70284 8006F684 E5C40000 */  swc1       $f4, 0x0($t6)
/* 70288 8006F688 C4920004 */  lwc1       $f18, 0x4($a0)
/* 7028C 8006F68C C48A0014 */  lwc1       $f10, 0x14($a0)
/* 70290 8006F690 8FAF0014 */  lw         $t7, 0x14($sp)
/* 70294 8006F694 460C9202 */  mul.s      $f8, $f18, $f12
/* 70298 8006F698 C4920024 */  lwc1       $f18, 0x24($a0)
/* 7029C 8006F69C 460E5182 */  mul.s      $f6, $f10, $f14
/* 702A0 8006F6A0 46064100 */  add.s      $f4, $f8, $f6
/* 702A4 8006F6A4 46109282 */  mul.s      $f10, $f18, $f16
/* 702A8 8006F6A8 C4860034 */  lwc1       $f6, 0x34($a0)
/* 702AC 8006F6AC 460A2200 */  add.s      $f8, $f4, $f10
/* 702B0 8006F6B0 46083480 */  add.s      $f18, $f6, $f8
/* 702B4 8006F6B4 E5F20000 */  swc1       $f18, 0x0($t7)
/* 702B8 8006F6B8 C4840008 */  lwc1       $f4, 0x8($a0)
/* 702BC 8006F6BC C4860018 */  lwc1       $f6, 0x18($a0)
/* 702C0 8006F6C0 8FB80018 */  lw         $t8, 0x18($sp)
/* 702C4 8006F6C4 460C2282 */  mul.s      $f10, $f4, $f12
/* 702C8 8006F6C8 C4840028 */  lwc1       $f4, 0x28($a0)
/* 702CC 8006F6CC 460E3202 */  mul.s      $f8, $f6, $f14
/* 702D0 8006F6D0 46085480 */  add.s      $f18, $f10, $f8
/* 702D4 8006F6D4 46102182 */  mul.s      $f6, $f4, $f16
/* 702D8 8006F6D8 C4880038 */  lwc1       $f8, 0x38($a0)
/* 702DC 8006F6DC 46069280 */  add.s      $f10, $f18, $f6
/* 702E0 8006F6E0 460A4100 */  add.s      $f4, $f8, $f10
/* 702E4 8006F6E4 03E00008 */  jr         $ra
/* 702E8 8006F6E8 E7040000 */   swc1      $f4, 0x0($t8)

glabel f32_matrix_dot
/* 702EC 8006F6EC C4A40000 */  lwc1       $f4, 0x0($a1)
/* 702F0 8006F6F0 C48A0000 */  lwc1       $f10, 0x0($a0)
/* 702F4 8006F6F4 C4A60004 */  lwc1       $f6, 0x4($a1)
/* 702F8 8006F6F8 C48C0010 */  lwc1       $f12, 0x10($a0)
/* 702FC 8006F6FC 460A2282 */  mul.s      $f10, $f4, $f10
/* 70300 8006F700 C4A80008 */  lwc1       $f8, 0x8($a1)
/* 70304 8006F704 C48E0020 */  lwc1       $f14, 0x20($a0)
/* 70308 8006F708 460C3302 */  mul.s      $f12, $f6, $f12
/* 7030C 8006F70C 460C5300 */  add.s      $f12, $f10, $f12
/* 70310 8006F710 460E4382 */  mul.s      $f14, $f8, $f14
/* 70314 8006F714 C48A0004 */  lwc1       $f10, 0x4($a0)
/* 70318 8006F718 460A2282 */  mul.s      $f10, $f4, $f10
/* 7031C 8006F71C 460E6400 */  add.s      $f16, $f12, $f14
/* 70320 8006F720 C48C0014 */  lwc1       $f12, 0x14($a0)
/* 70324 8006F724 C48E0024 */  lwc1       $f14, 0x24($a0)
/* 70328 8006F728 460C3302 */  mul.s      $f12, $f6, $f12
/* 7032C 8006F72C E4D00000 */  swc1       $f16, 0x0($a2)
/* 70330 8006F730 460E4382 */  mul.s      $f14, $f8, $f14
/* 70334 8006F734 460C5300 */  add.s      $f12, $f10, $f12
/* 70338 8006F738 C48A0008 */  lwc1       $f10, 0x8($a0)
/* 7033C 8006F73C 460E6400 */  add.s      $f16, $f12, $f14
/* 70340 8006F740 460A2282 */  mul.s      $f10, $f4, $f10
/* 70344 8006F744 C48C0018 */  lwc1       $f12, 0x18($a0)
/* 70348 8006F748 C48E0028 */  lwc1       $f14, 0x28($a0)
/* 7034C 8006F74C E4D00004 */  swc1       $f16, 0x4($a2)
/* 70350 8006F750 460C3302 */  mul.s      $f12, $f6, $f12
/* 70354 8006F754 460C5300 */  add.s      $f12, $f10, $f12
/* 70358 8006F758 460E4382 */  mul.s      $f14, $f8, $f14
/* 7035C 8006F75C 460E6380 */  add.s      $f14, $f12, $f14
/* 70360 8006F760 03E00008 */  jr         $ra
/* 70364 8006F764 E4CE0008 */   swc1      $f14, 0x8($a2)

glabel f32_matrix_mult
/* 70368 8006F768 27BDFFF8 */  addiu      $sp, $sp, -0x8
/* 7036C 8006F76C F7A20000 */  sdc1       $f2, 0x0($sp)
/* 70370 8006F770 34080004 */  ori        $t0, $zero, 0x4
.L8006F774:
/* 70374 8006F774 C4820000 */  lwc1       $f2, 0x0($a0)
/* 70378 8006F778 C4AA0000 */  lwc1       $f10, 0x0($a1)
/* 7037C 8006F77C C4840004 */  lwc1       $f4, 0x4($a0)
/* 70380 8006F780 C4AC0010 */  lwc1       $f12, 0x10($a1)
/* 70384 8006F784 460A1282 */  mul.s      $f10, $f2, $f10
/* 70388 8006F788 C4860008 */  lwc1       $f6, 0x8($a0)
/* 7038C 8006F78C C4AE0020 */  lwc1       $f14, 0x20($a1)
/* 70390 8006F790 460C2302 */  mul.s      $f12, $f4, $f12
/* 70394 8006F794 C488000C */  lwc1       $f8, 0xC($a0)
/* 70398 8006F798 C4B00030 */  lwc1       $f16, 0x30($a1)
/* 7039C 8006F79C 460E3382 */  mul.s      $f14, $f6, $f14
/* 703A0 8006F7A0 24840010 */  addiu      $a0, $a0, 0x10
/* 703A4 8006F7A4 24C60010 */  addiu      $a2, $a2, 0x10
/* 703A8 8006F7A8 46104402 */  mul.s      $f16, $f8, $f16
/* 703AC 8006F7AC 2508FFFF */  addiu      $t0, $t0, -0x1
/* 703B0 8006F7B0 460E6380 */  add.s      $f14, $f12, $f14
/* 703B4 8006F7B4 C4AC0014 */  lwc1       $f12, 0x14($a1)
/* 703B8 8006F7B8 46105400 */  add.s      $f16, $f10, $f16
/* 703BC 8006F7BC C4AA0004 */  lwc1       $f10, 0x4($a1)
/* 703C0 8006F7C0 460A1282 */  mul.s      $f10, $f2, $f10
/* 703C4 8006F7C4 46107480 */  add.s      $f18, $f14, $f16
/* 703C8 8006F7C8 C4AE0024 */  lwc1       $f14, 0x24($a1)
/* 703CC 8006F7CC 460C2302 */  mul.s      $f12, $f4, $f12
/* 703D0 8006F7D0 C4B00034 */  lwc1       $f16, 0x34($a1)
/* 703D4 8006F7D4 E4D2FFF0 */  swc1       $f18, -0x10($a2)
/* 703D8 8006F7D8 460E3382 */  mul.s      $f14, $f6, $f14
/* 703DC 8006F7DC 00000000 */  nop
/* 703E0 8006F7E0 46104402 */  mul.s      $f16, $f8, $f16
/* 703E4 8006F7E4 460E6380 */  add.s      $f14, $f12, $f14
/* 703E8 8006F7E8 C4AC0018 */  lwc1       $f12, 0x18($a1)
/* 703EC 8006F7EC 46105400 */  add.s      $f16, $f10, $f16
/* 703F0 8006F7F0 C4AA0008 */  lwc1       $f10, 0x8($a1)
/* 703F4 8006F7F4 460A1282 */  mul.s      $f10, $f2, $f10
/* 703F8 8006F7F8 46107480 */  add.s      $f18, $f14, $f16
/* 703FC 8006F7FC C4AE0028 */  lwc1       $f14, 0x28($a1)
/* 70400 8006F800 460C2302 */  mul.s      $f12, $f4, $f12
/* 70404 8006F804 C4B00038 */  lwc1       $f16, 0x38($a1)
/* 70408 8006F808 E4D2FFF4 */  swc1       $f18, -0xC($a2)
/* 7040C 8006F80C 460E3382 */  mul.s      $f14, $f6, $f14
/* 70410 8006F810 00000000 */  nop
/* 70414 8006F814 46104402 */  mul.s      $f16, $f8, $f16
/* 70418 8006F818 460E6380 */  add.s      $f14, $f12, $f14
/* 7041C 8006F81C C4AC001C */  lwc1       $f12, 0x1C($a1)
/* 70420 8006F820 46105400 */  add.s      $f16, $f10, $f16
/* 70424 8006F824 C4AA000C */  lwc1       $f10, 0xC($a1)
/* 70428 8006F828 460A1282 */  mul.s      $f10, $f2, $f10
/* 7042C 8006F82C 46107480 */  add.s      $f18, $f14, $f16
/* 70430 8006F830 C4AE002C */  lwc1       $f14, 0x2C($a1)
/* 70434 8006F834 460C2302 */  mul.s      $f12, $f4, $f12
/* 70438 8006F838 C4B0003C */  lwc1       $f16, 0x3C($a1)
/* 7043C 8006F83C E4D2FFF8 */  swc1       $f18, -0x8($a2)
/* 70440 8006F840 460E3382 */  mul.s      $f14, $f6, $f14
/* 70444 8006F844 00000000 */  nop
/* 70448 8006F848 46104402 */  mul.s      $f16, $f8, $f16
/* 7044C 8006F84C 460E6380 */  add.s      $f14, $f12, $f14
/* 70450 8006F850 46105400 */  add.s      $f16, $f10, $f16
/* 70454 8006F854 46107480 */  add.s      $f18, $f14, $f16
/* 70458 8006F858 E4D2FFFC */  swc1       $f18, -0x4($a2)
/* 7045C 8006F85C 5500FFC5 */  bnel       $t0, $zero, .L8006F774
/* 70460 8006F860 00000000 */   nop
/* 70464 8006F864 D7A20000 */  ldc1       $f2, 0x0($sp)
/* 70468 8006F868 03E00008 */  jr         $ra
/* 7046C 8006F86C 27BD0008 */   addiu     $sp, $sp, 0x8

glabel f32_matrix_to_s16_matrix
/* 70470 8006F870 3C014780 */  lui        $at, (0x47800000 >> 16)
/* 70474 8006F874 44816000 */  mtc1       $at, $f12
/* 70478 8006F878 34080004 */  ori        $t0, $zero, 0x4
.L8006F87C:
/* 7047C 8006F87C C4840000 */  lwc1       $f4, 0x0($a0)
/* 70480 8006F880 C4860004 */  lwc1       $f6, 0x4($a0)
/* 70484 8006F884 C4880008 */  lwc1       $f8, 0x8($a0)
/* 70488 8006F888 460C2102 */  mul.s      $f4, $f4, $f12
/* 7048C 8006F88C C48A000C */  lwc1       $f10, 0xC($a0)
/* 70490 8006F890 24840010 */  addiu      $a0, $a0, 0x10
/* 70494 8006F894 460C3182 */  mul.s      $f6, $f6, $f12
/* 70498 8006F898 24A50008 */  addiu      $a1, $a1, 0x8
/* 7049C 8006F89C 2508FFFF */  addiu      $t0, $t0, -0x1
/* 704A0 8006F8A0 460C4202 */  mul.s      $f8, $f8, $f12
/* 704A4 8006F8A4 00000000 */  nop
/* 704A8 8006F8A8 460C5282 */  mul.s      $f10, $f10, $f12
/* 704AC 8006F8AC 46002124 */  cvt.w.s    $f4, $f4
/* 704B0 8006F8B0 460031A4 */  cvt.w.s    $f6, $f6
/* 704B4 8006F8B4 44092000 */  mfc1       $t1, $f4
/* 704B8 8006F8B8 46004224 */  cvt.w.s    $f8, $f8
/* 704BC 8006F8BC 440A3000 */  mfc1       $t2, $f6
/* 704C0 8006F8C0 A4A90018 */  sh         $t1, 0x18($a1)
/* 704C4 8006F8C4 460052A4 */  cvt.w.s    $f10, $f10
/* 704C8 8006F8C8 440B4000 */  mfc1       $t3, $f8
/* 704CC 8006F8CC A4AA001A */  sh         $t2, 0x1A($a1)
/* 704D0 8006F8D0 00094C02 */  srl        $t1, $t1, 16
/* 704D4 8006F8D4 440C5000 */  mfc1       $t4, $f10
/* 704D8 8006F8D8 A4AB001C */  sh         $t3, 0x1C($a1)
/* 704DC 8006F8DC 000A5402 */  srl        $t2, $t2, 16
/* 704E0 8006F8E0 A4AC001E */  sh         $t4, 0x1E($a1)
/* 704E4 8006F8E4 000B5C02 */  srl        $t3, $t3, 16
/* 704E8 8006F8E8 000C6402 */  srl        $t4, $t4, 16
/* 704EC 8006F8EC A4A9FFF8 */  sh         $t1, -0x8($a1)
/* 704F0 8006F8F0 A4AAFFFA */  sh         $t2, -0x6($a1)
/* 704F4 8006F8F4 A4ABFFFC */  sh         $t3, -0x4($a1)
/* 704F8 8006F8F8 A4ACFFFE */  sh         $t4, -0x2($a1)
/* 704FC 8006F8FC 5500FFDF */  bnel       $t0, $zero, .L8006F87C
/* 70500 8006F900 00000000 */   nop
/* 70504 8006F904 03E00008 */  jr         $ra
/* 70508 8006F908 00000000 */   nop

glabel set_rng_seed
/* 7050C 8006F90C 3C01800E */  lui        $at, %hi(gCurrentRNGSeed)
/* 70510 8006F910 03E00008 */  jr         $ra
/* 70514 8006F914 AC24D4C4 */   sw        $a0, %lo(gCurrentRNGSeed)($at)

glabel save_rng_seed
/* 70518 8006F918 3C04800E */  lui        $a0, %hi(gCurrentRNGSeed)
/* 7051C 8006F91C 8C84D4C4 */  lw         $a0, %lo(gCurrentRNGSeed)($a0)
/* 70520 8006F920 3C01800E */  lui        $at, %hi(gPrevRNGSeed)
/* 70524 8006F924 03E00008 */  jr         $ra
/* 70528 8006F928 AC24D4C8 */   sw        $a0, %lo(gPrevRNGSeed)($at)

glabel load_rng_seed
/* 7052C 8006F92C 3C04800E */  lui        $a0, %hi(gPrevRNGSeed)
/* 70530 8006F930 8C84D4C8 */  lw         $a0, %lo(gPrevRNGSeed)($a0)
/* 70534 8006F934 3C01800E */  lui        $at, %hi(gCurrentRNGSeed)
/* 70538 8006F938 03E00008 */  jr         $ra
/* 7053C 8006F93C AC24D4C4 */   sw        $a0, %lo(gCurrentRNGSeed)($at)

glabel get_rng_seed
/* 70540 8006F940 3C02800E */  lui        $v0, %hi(gCurrentRNGSeed)
/* 70544 8006F944 03E00008 */  jr         $ra
/* 70548 8006F948 8C42D4C4 */   lw        $v0, %lo(gCurrentRNGSeed)($v0)

/* Handwritten function */
glabel get_random_number_from_range
/* 7054C 8006F94C 3C08800E */  lui        $t0, %hi(gCurrentRNGSeed)
/* 70550 8006F950 8D08D4C4 */  lw         $t0, %lo(gCurrentRNGSeed)($t0)
/* 70554 8006F954 3C01800E */  lui        $at, %hi(gCurrentRNGSeed)
/* 70558 8006F958 00A42822 */  sub        $a1, $a1, $a0 /* handwritten instruction */
/* 7055C 8006F95C 00084FFC */  dsll32     $t1, $t0, 31
/* 70560 8006F960 000857F8 */  dsll       $t2, $t0, 31
/* 70564 8006F964 00094FFA */  dsrl       $t1, $t1, 31
/* 70568 8006F968 000A503E */  dsrl32     $t2, $t2, 0
/* 7056C 8006F96C 00085B3C */  dsll32     $t3, $t0, 12
/* 70570 8006F970 012A4825 */  or         $t1, $t1, $t2
/* 70574 8006F974 000B583E */  dsrl32     $t3, $t3, 0
/* 70578 8006F978 012B4826 */  xor        $t1, $t1, $t3
/* 7057C 8006F97C 00095D3A */  dsrl       $t3, $t1, 20
/* 70580 8006F980 316B0FFF */  andi       $t3, $t3, 0xFFF
/* 70584 8006F984 01694026 */  xor        $t0, $t3, $t1
/* 70588 8006F988 AC28D4C4 */  sw         $t0, %lo(gCurrentRNGSeed)($at)
/* 7058C 8006F98C 20A50001 */  addi       $a1, $a1, 0x1 /* handwritten instruction */
/* 70590 8006F990 01044023 */  subu       $t0, $t0, $a0
/* 70594 8006F994 0105001B */  divu       $zero, $t0, $a1
/* 70598 8006F998 00004012 */  mflo       $t0
/* 7059C 8006F99C 00001010 */  mfhi       $v0
/* 705A0 8006F9A0 00441020 */  add        $v0, $v0, $a0 /* handwritten instruction */
/* 705A4 8006F9A4 14A00002 */  bnez       $a1, .L8006F9B0
/* 705A8 8006F9A8 00000000 */   nop
/* 705AC 8006F9AC 0007000D */  break      7
.L8006F9B0:
/* 705B0 8006F9B0 03E00008 */  jr         $ra
/* 705B4 8006F9B4 00000000 */   nop

/* Handwritten function */
glabel s16_matrix_rotate
/* 705B8 8006F9B8 84880000 */  lh         $t0, 0x0($a0)
/* 705BC 8006F9BC 84AB0000 */  lh         $t3, 0x0($a1)
/* 705C0 8006F9C0 84890002 */  lh         $t1, 0x2($a0)
/* 705C4 8006F9C4 84AC0002 */  lh         $t4, 0x2($a1)
/* 705C8 8006F9C8 010B0018 */  mult       $t0, $t3
/* 705CC 8006F9CC 848A0004 */  lh         $t2, 0x4($a0)
/* 705D0 8006F9D0 84AD0004 */  lh         $t5, 0x4($a1)
/* 705D4 8006F9D4 00007012 */  mflo       $t6
/* 705D8 8006F9D8 00000000 */  nop
/* 705DC 8006F9DC 00000000 */  nop
/* 705E0 8006F9E0 012C0018 */  mult       $t1, $t4
/* 705E4 8006F9E4 00007812 */  mflo       $t7
/* 705E8 8006F9E8 01CF7020 */  add        $t6, $t6, $t7 /* handwritten instruction */
/* 705EC 8006F9EC 00000000 */  nop
/* 705F0 8006F9F0 014D0018 */  mult       $t2, $t5
/* 705F4 8006F9F4 0000C012 */  mflo       $t8
/* 705F8 8006F9F8 01D87020 */  add        $t6, $t6, $t8 /* handwritten instruction */
/* 705FC 8006F9FC 000E7303 */  sra        $t6, $t6, 12
/* 70600 8006FA00 01CB0018 */  mult       $t6, $t3
/* 70604 8006FA04 00005812 */  mflo       $t3
/* 70608 8006FA08 000B5B43 */  sra        $t3, $t3, 13
/* 7060C 8006FA0C 01685822 */  sub        $t3, $t3, $t0 /* handwritten instruction */
/* 70610 8006FA10 01CC0018 */  mult       $t6, $t4
/* 70614 8006FA14 A48B0006 */  sh         $t3, 0x6($a0)
/* 70618 8006FA18 00006012 */  mflo       $t4
/* 7061C 8006FA1C 000C6343 */  sra        $t4, $t4, 13
/* 70620 8006FA20 01896022 */  sub        $t4, $t4, $t1 /* handwritten instruction */
/* 70624 8006FA24 01CD0018 */  mult       $t6, $t5
/* 70628 8006FA28 A48C0008 */  sh         $t4, 0x8($a0)
/* 7062C 8006FA2C 00006812 */  mflo       $t5
/* 70630 8006FA30 000D6B43 */  sra        $t5, $t5, 13
/* 70634 8006FA34 01A86822 */  sub        $t5, $t5, $t0 /* handwritten instruction */
/* 70638 8006FA38 03E00008 */  jr         $ra
/* 7063C 8006FA3C A48D000A */   sh        $t5, 0xA($a0)

/* Handwritten function */
glabel s16_matrix_to_s32_matrix
/* 70640 8006FA40 340A0010 */  ori        $t2, $zero, 0x10
/* 70644 8006FA44 016B5826 */  xor        $t3, $t3, $t3
.L8006FA48:
/* 70648 8006FA48 84880000 */  lh         $t0, 0x0($a0)
/* 7064C 8006FA4C 94890020 */  lhu        $t1, 0x20($a0)
/* 70650 8006FA50 20840002 */  addi       $a0, $a0, 0x2 /* handwritten instruction */
/* 70654 8006FA54 00084400 */  sll        $t0, $t0, 16
/* 70658 8006FA58 01094025 */  or         $t0, $t0, $t1
/* 7065C 8006FA5C ACA80000 */  sw         $t0, 0x0($a1)
/* 70660 8006FA60 20A50004 */  addi       $a1, $a1, 0x4 /* handwritten instruction */
/* 70664 8006FA64 256B0001 */  addiu      $t3, $t3, 0x1
/* 70668 8006FA68 556AFFF7 */  bnel       $t3, $t2, .L8006FA48
/* 7066C 8006FA6C 00000000 */   nop
/* 70670 8006FA70 03E00008 */  jr         $ra
/* 70674 8006FA74 00000000 */   nop

/* Handwritten function */
glabel s16_vec3_mult_by_s32_matrix_full
/* 70678 8006FA78 84A80000 */  lh         $t0, 0x0($a1)
/* 7067C 8006FA7C 8C8B0000 */  lw         $t3, 0x0($a0)
/* 70680 8006FA80 84A90002 */  lh         $t1, 0x2($a1)
/* 70684 8006FA84 84AA0004 */  lh         $t2, 0x4($a1)
/* 70688 8006FA88 010B0018 */  mult       $t0, $t3
/* 7068C 8006FA8C 8C8B0010 */  lw         $t3, 0x10($a0)
/* 70690 8006FA90 00006012 */  mflo       $t4
/* 70694 8006FA94 00000000 */  nop
/* 70698 8006FA98 00000000 */  nop
/* 7069C 8006FA9C 012B0018 */  mult       $t1, $t3
/* 706A0 8006FAA0 8C8B0020 */  lw         $t3, 0x20($a0)
/* 706A4 8006FAA4 00006812 */  mflo       $t5
/* 706A8 8006FAA8 018D6020 */  add        $t4, $t4, $t5 /* handwritten instruction */
/* 706AC 8006FAAC 00000000 */  nop
/* 706B0 8006FAB0 014B0018 */  mult       $t2, $t3
/* 706B4 8006FAB4 8C8B0030 */  lw         $t3, 0x30($a0)
/* 706B8 8006FAB8 00007012 */  mflo       $t6
/* 706BC 8006FABC 018E6020 */  add        $t4, $t4, $t6 /* handwritten instruction */
/* 706C0 8006FAC0 018B6020 */  add        $t4, $t4, $t3 /* handwritten instruction */
/* 706C4 8006FAC4 000C6403 */  sra        $t4, $t4, 16
/* 706C8 8006FAC8 A4AC0000 */  sh         $t4, 0x0($a1)
/* 706CC 8006FACC 8C8B0004 */  lw         $t3, 0x4($a0)
/* 706D0 8006FAD0 010B0018 */  mult       $t0, $t3
/* 706D4 8006FAD4 8C8B0014 */  lw         $t3, 0x14($a0)
/* 706D8 8006FAD8 00006012 */  mflo       $t4
/* 706DC 8006FADC 00000000 */  nop
/* 706E0 8006FAE0 00000000 */  nop
/* 706E4 8006FAE4 012B0018 */  mult       $t1, $t3
/* 706E8 8006FAE8 8C8B0024 */  lw         $t3, 0x24($a0)
/* 706EC 8006FAEC 00006812 */  mflo       $t5
/* 706F0 8006FAF0 018D6020 */  add        $t4, $t4, $t5 /* handwritten instruction */
/* 706F4 8006FAF4 00000000 */  nop
/* 706F8 8006FAF8 014B0018 */  mult       $t2, $t3
/* 706FC 8006FAFC 8C8B0034 */  lw         $t3, 0x34($a0)
/* 70700 8006FB00 00007012 */  mflo       $t6
/* 70704 8006FB04 018E6020 */  add        $t4, $t4, $t6 /* handwritten instruction */
/* 70708 8006FB08 018B6020 */  add        $t4, $t4, $t3 /* handwritten instruction */
/* 7070C 8006FB0C 000C6403 */  sra        $t4, $t4, 16
/* 70710 8006FB10 A4AC0002 */  sh         $t4, 0x2($a1)
/* 70714 8006FB14 8C8B0008 */  lw         $t3, 0x8($a0)
/* 70718 8006FB18 010B0018 */  mult       $t0, $t3
/* 7071C 8006FB1C 8C8B0018 */  lw         $t3, 0x18($a0)
/* 70720 8006FB20 00006012 */  mflo       $t4
/* 70724 8006FB24 00000000 */  nop
/* 70728 8006FB28 00000000 */  nop
/* 7072C 8006FB2C 012B0018 */  mult       $t1, $t3
/* 70730 8006FB30 8C8B0028 */  lw         $t3, 0x28($a0)
/* 70734 8006FB34 00006812 */  mflo       $t5
/* 70738 8006FB38 018D6020 */  add        $t4, $t4, $t5 /* handwritten instruction */
/* 7073C 8006FB3C 00000000 */  nop
/* 70740 8006FB40 014B0018 */  mult       $t2, $t3
/* 70744 8006FB44 8C8B0038 */  lw         $t3, 0x38($a0)
/* 70748 8006FB48 00007012 */  mflo       $t6
/* 7074C 8006FB4C 018E6020 */  add        $t4, $t4, $t6 /* handwritten instruction */
/* 70750 8006FB50 018B6020 */  add        $t4, $t4, $t3 /* handwritten instruction */
/* 70754 8006FB54 000C6403 */  sra        $t4, $t4, 16
/* 70758 8006FB58 03E00008 */  jr         $ra
/* 7075C 8006FB5C A4AC0004 */   sh        $t4, 0x4($a1)

/* Handwritten function */
glabel s16_vec3_mult_by_s32_matrix
/* 70760 8006FB60 8C8B0000 */  lw         $t3, 0x0($a0)
/* 70764 8006FB64 84A80000 */  lh         $t0, 0x0($a1)
/* 70768 8006FB68 84A90002 */  lh         $t1, 0x2($a1)
/* 7076C 8006FB6C 84AA0004 */  lh         $t2, 0x4($a1)
/* 70770 8006FB70 010B0018 */  mult       $t0, $t3
/* 70774 8006FB74 8C8B0010 */  lw         $t3, 0x10($a0)
/* 70778 8006FB78 00006012 */  mflo       $t4
/* 7077C 8006FB7C 00000000 */  nop
/* 70780 8006FB80 00000000 */  nop
/* 70784 8006FB84 012B0018 */  mult       $t1, $t3
/* 70788 8006FB88 8C8B0020 */  lw         $t3, 0x20($a0)
/* 7078C 8006FB8C 00006812 */  mflo       $t5
/* 70790 8006FB90 018D6020 */  add        $t4, $t4, $t5 /* handwritten instruction */
/* 70794 8006FB94 00000000 */  nop
/* 70798 8006FB98 014B0018 */  mult       $t2, $t3
/* 7079C 8006FB9C 8C8B0004 */  lw         $t3, 0x4($a0)
/* 707A0 8006FBA0 00007012 */  mflo       $t6
/* 707A4 8006FBA4 018E6020 */  add        $t4, $t4, $t6 /* handwritten instruction */
/* 707A8 8006FBA8 000C6403 */  sra        $t4, $t4, 16
/* 707AC 8006FBAC 010B0018 */  mult       $t0, $t3
/* 707B0 8006FBB0 A4AC0000 */  sh         $t4, 0x0($a1)
/* 707B4 8006FBB4 8C8B0014 */  lw         $t3, 0x14($a0)
/* 707B8 8006FBB8 00006012 */  mflo       $t4
/* 707BC 8006FBBC 00000000 */  nop
/* 707C0 8006FBC0 00000000 */  nop
/* 707C4 8006FBC4 012B0018 */  mult       $t1, $t3
/* 707C8 8006FBC8 8C8B0024 */  lw         $t3, 0x24($a0)
/* 707CC 8006FBCC 00006812 */  mflo       $t5
/* 707D0 8006FBD0 018D6020 */  add        $t4, $t4, $t5 /* handwritten instruction */
/* 707D4 8006FBD4 00000000 */  nop
/* 707D8 8006FBD8 014B0018 */  mult       $t2, $t3
/* 707DC 8006FBDC 8C8B0008 */  lw         $t3, 0x8($a0)
/* 707E0 8006FBE0 00007012 */  mflo       $t6
/* 707E4 8006FBE4 018E6020 */  add        $t4, $t4, $t6 /* handwritten instruction */
/* 707E8 8006FBE8 000C6403 */  sra        $t4, $t4, 16
/* 707EC 8006FBEC 010B0018 */  mult       $t0, $t3
/* 707F0 8006FBF0 A4AC0002 */  sh         $t4, 0x2($a1)
/* 707F4 8006FBF4 8C8B0018 */  lw         $t3, 0x18($a0)
/* 707F8 8006FBF8 00006012 */  mflo       $t4
/* 707FC 8006FBFC 00000000 */  nop
/* 70800 8006FC00 00000000 */  nop
/* 70804 8006FC04 012B0018 */  mult       $t1, $t3
/* 70808 8006FC08 8C8B0028 */  lw         $t3, 0x28($a0)
/* 7080C 8006FC0C 00006812 */  mflo       $t5
/* 70810 8006FC10 018D6020 */  add        $t4, $t4, $t5 /* handwritten instruction */
/* 70814 8006FC14 00000000 */  nop
/* 70818 8006FC18 014B0018 */  mult       $t2, $t3
/* 7081C 8006FC1C 00007012 */  mflo       $t6
/* 70820 8006FC20 018E6020 */  add        $t4, $t4, $t6 /* handwritten instruction */
/* 70824 8006FC24 000C6403 */  sra        $t4, $t4, 16
/* 70828 8006FC28 03E00008 */  jr         $ra
/* 7082C 8006FC2C A4AC0004 */   sh        $t4, 0x4($a1)

glabel object_transform_to_matrix
/* 70830 8006FC30 27BDFFF8 */  addiu      $sp, $sp, -0x8
/* 70834 8006FC34 3C013780 */  lui        $at, (0x37800000 >> 16)
/* 70838 8006FC38 FFBF0000 */  sd         $ra, 0x0($sp)
/* 7083C 8006FC3C 00803825 */  or         $a3, $a0, $zero
/* 70840 8006FC40 44819000 */  mtc1       $at, $f18
/* 70844 8006FC44 0C01C20C */  jal        sins_1
/* 70848 8006FC48 84A40000 */   lh        $a0, 0x0($a1)
/* 7084C 8006FC4C 44820000 */  mtc1       $v0, $f0
/* 70850 8006FC50 84A40000 */  lh         $a0, 0x0($a1)
/* 70854 8006FC54 46800020 */  cvt.s.w    $f0, $f0
/* 70858 8006FC58 46120002 */  mul.s      $f0, $f0, $f18
/* 7085C 8006FC5C 0C01C20B */  jal        coss_1
/* 70860 8006FC60 00000000 */   nop
/* 70864 8006FC64 44821000 */  mtc1       $v0, $f2
/* 70868 8006FC68 84A40002 */  lh         $a0, 0x2($a1)
/* 7086C 8006FC6C 468010A0 */  cvt.s.w    $f2, $f2
/* 70870 8006FC70 46121082 */  mul.s      $f2, $f2, $f18
/* 70874 8006FC74 0C01C20C */  jal        sins_1
/* 70878 8006FC78 00000000 */   nop
/* 7087C 8006FC7C 44822000 */  mtc1       $v0, $f4
/* 70880 8006FC80 84A40002 */  lh         $a0, 0x2($a1)
/* 70884 8006FC84 46802120 */  cvt.s.w    $f4, $f4
/* 70888 8006FC88 46122102 */  mul.s      $f4, $f4, $f18
/* 7088C 8006FC8C 0C01C20B */  jal        coss_1
/* 70890 8006FC90 00000000 */   nop
/* 70894 8006FC94 44823000 */  mtc1       $v0, $f6
/* 70898 8006FC98 84A40004 */  lh         $a0, 0x4($a1)
/* 7089C 8006FC9C 468031A0 */  cvt.s.w    $f6, $f6
/* 708A0 8006FCA0 46123182 */  mul.s      $f6, $f6, $f18
/* 708A4 8006FCA4 0C01C20C */  jal        sins_1
/* 708A8 8006FCA8 00000000 */   nop
/* 708AC 8006FCAC 44824000 */  mtc1       $v0, $f8
/* 708B0 8006FCB0 84A40004 */  lh         $a0, 0x4($a1)
/* 708B4 8006FCB4 46804220 */  cvt.s.w    $f8, $f8
/* 708B8 8006FCB8 46124202 */  mul.s      $f8, $f8, $f18
/* 708BC 8006FCBC 0C01C20B */  jal        coss_1
/* 708C0 8006FCC0 00000000 */   nop
/* 708C4 8006FCC4 44825000 */  mtc1       $v0, $f10
/* 708C8 8006FCC8 8CAA0008 */  lw         $t2, 0x8($a1)
/* 708CC 8006FCCC ACE0000C */  sw         $zero, 0xC($a3)
/* 708D0 8006FCD0 468052A0 */  cvt.s.w    $f10, $f10
/* 708D4 8006FCD4 ACE0001C */  sw         $zero, 0x1C($a3)
/* 708D8 8006FCD8 ACE0002C */  sw         $zero, 0x2C($a3)
/* 708DC 8006FCDC 3C013F80 */  lui        $at, (0x3F800000 >> 16)
/* 708E0 8006FCE0 46125282 */  mul.s      $f10, $f10, $f18
/* 708E4 8006FCE4 00000000 */  nop
/* 708E8 8006FCE8 46002402 */  mul.s      $f16, $f4, $f0
/* 708EC 8006FCEC 00000000 */  nop
/* 708F0 8006FCF0 46088402 */  mul.s      $f16, $f16, $f8
/* 708F4 8006FCF4 00000000 */  nop
/* 708F8 8006FCF8 46025482 */  mul.s      $f18, $f10, $f2
/* 708FC 8006FCFC 46128400 */  add.s      $f16, $f16, $f18
/* 70900 8006FD00 448A9000 */  mtc1       $t2, $f18
/* 70904 8006FD04 00000000 */  nop
/* 70908 8006FD08 46128402 */  mul.s      $f16, $f16, $f18
/* 7090C 8006FD0C E4F00000 */  swc1       $f16, 0x0($a3)
/* 70910 8006FD10 46064402 */  mul.s      $f16, $f8, $f6
/* 70914 8006FD14 00000000 */  nop
/* 70918 8006FD18 46128402 */  mul.s      $f16, $f16, $f18
/* 7091C 8006FD1C E4F00004 */  swc1       $f16, 0x4($a3)
/* 70920 8006FD20 46022402 */  mul.s      $f16, $f4, $f2
/* 70924 8006FD24 00000000 */  nop
/* 70928 8006FD28 46088402 */  mul.s      $f16, $f16, $f8
/* 7092C 8006FD2C 00000000 */  nop
/* 70930 8006FD30 46005482 */  mul.s      $f18, $f10, $f0
/* 70934 8006FD34 46128401 */  sub.s      $f16, $f16, $f18
/* 70938 8006FD38 448A9000 */  mtc1       $t2, $f18
/* 7093C 8006FD3C 00000000 */  nop
/* 70940 8006FD40 46128402 */  mul.s      $f16, $f16, $f18
/* 70944 8006FD44 E4F00008 */  swc1       $f16, 0x8($a3)
/* 70948 8006FD48 46002402 */  mul.s      $f16, $f4, $f0
/* 7094C 8006FD4C 00000000 */  nop
/* 70950 8006FD50 460A8402 */  mul.s      $f16, $f16, $f10
/* 70954 8006FD54 00000000 */  nop
/* 70958 8006FD58 46024482 */  mul.s      $f18, $f8, $f2
/* 7095C 8006FD5C 46128401 */  sub.s      $f16, $f16, $f18
/* 70960 8006FD60 448A9000 */  mtc1       $t2, $f18
/* 70964 8006FD64 00000000 */  nop
/* 70968 8006FD68 46128402 */  mul.s      $f16, $f16, $f18
/* 7096C 8006FD6C E4F00010 */  swc1       $f16, 0x10($a3)
/* 70970 8006FD70 46065402 */  mul.s      $f16, $f10, $f6
/* 70974 8006FD74 00000000 */  nop
/* 70978 8006FD78 46128402 */  mul.s      $f16, $f16, $f18
/* 7097C 8006FD7C E4F00014 */  swc1       $f16, 0x14($a3)
/* 70980 8006FD80 46022402 */  mul.s      $f16, $f4, $f2
/* 70984 8006FD84 00000000 */  nop
/* 70988 8006FD88 460A8402 */  mul.s      $f16, $f16, $f10
/* 7098C 8006FD8C 00000000 */  nop
/* 70990 8006FD90 46004482 */  mul.s      $f18, $f8, $f0
/* 70994 8006FD94 46128400 */  add.s      $f16, $f16, $f18
/* 70998 8006FD98 448A9000 */  mtc1       $t2, $f18
/* 7099C 8006FD9C 00000000 */  nop
/* 709A0 8006FDA0 46128402 */  mul.s      $f16, $f16, $f18
/* 709A4 8006FDA4 E4F00018 */  swc1       $f16, 0x18($a3)
/* 709A8 8006FDA8 46003402 */  mul.s      $f16, $f6, $f0
/* 709AC 8006FDAC 00000000 */  nop
/* 709B0 8006FDB0 46128402 */  mul.s      $f16, $f16, $f18
/* 709B4 8006FDB4 E4F00020 */  swc1       $f16, 0x20($a3)
/* 709B8 8006FDB8 46122402 */  mul.s      $f16, $f4, $f18
/* 709BC 8006FDBC 46008407 */  neg.s      $f16, $f16
/* 709C0 8006FDC0 E4F00024 */  swc1       $f16, 0x24($a3)
/* 709C4 8006FDC4 46023402 */  mul.s      $f16, $f6, $f2
/* 709C8 8006FDC8 00000000 */  nop
/* 709CC 8006FDCC 46128402 */  mul.s      $f16, $f16, $f18
/* 709D0 8006FDD0 44819000 */  mtc1       $at, $f18
/* 709D4 8006FDD4 E4F00028 */  swc1       $f16, 0x28($a3)
/* 709D8 8006FDD8 8CA8000C */  lw         $t0, 0xC($a1)
/* 709DC 8006FDDC ACE80030 */  sw         $t0, 0x30($a3)
/* 709E0 8006FDE0 8CA80010 */  lw         $t0, 0x10($a1)
/* 709E4 8006FDE4 ACE80034 */  sw         $t0, 0x34($a3)
/* 709E8 8006FDE8 8CA80014 */  lw         $t0, 0x14($a1)
/* 709EC 8006FDEC E4F2003C */  swc1       $f18, 0x3C($a3)
/* 709F0 8006FDF0 ACE80038 */  sw         $t0, 0x38($a3)
/* 709F4 8006FDF4 DFBF0000 */  ld         $ra, 0x0($sp)
/* 709F8 8006FDF8 27BD0008 */  addiu      $sp, $sp, 0x8
/* 709FC 8006FDFC 03E00008 */  jr         $ra
/* 70A00 8006FE00 00000000 */   nop

glabel f32_matrix_scale
/* 70A04 8006FE04 44859000 */  mtc1       $a1, $f18
/* 70A08 8006FE08 C4900010 */  lwc1       $f16, 0x10($a0)
/* 70A0C 8006FE0C 46128402 */  mul.s      $f16, $f16, $f18
/* 70A10 8006FE10 E4900010 */  swc1       $f16, 0x10($a0)
/* 70A14 8006FE14 C4F00014 */  lwc1       $f16, 0x14($a3)
/* 70A18 8006FE18 46128402 */  mul.s      $f16, $f16, $f18
/* 70A1C 8006FE1C E4900014 */  swc1       $f16, 0x14($a0)
/* 70A20 8006FE20 C4900018 */  lwc1       $f16, 0x18($a0)
/* 70A24 8006FE24 46128402 */  mul.s      $f16, $f16, $f18
/* 70A28 8006FE28 03E00008 */  jr         $ra
/* 70A2C 8006FE2C E4900018 */   swc1      $f16, 0x18($a0)

glabel f32_matrix_y_scale
/* 70A30 8006FE30 44858000 */  mtc1       $a1, $f16
/* 70A34 8006FE34 C4800010 */  lwc1       $f0, 0x10($a0)
/* 70A38 8006FE38 C4840014 */  lwc1       $f4, 0x14($a0)
/* 70A3C 8006FE3C C4880018 */  lwc1       $f8, 0x18($a0)
/* 70A40 8006FE40 46100002 */  mul.s      $f0, $f0, $f16
/* 70A44 8006FE44 C4820030 */  lwc1       $f2, 0x30($a0)
/* 70A48 8006FE48 C4860034 */  lwc1       $f6, 0x34($a0)
/* 70A4C 8006FE4C 46102102 */  mul.s      $f4, $f4, $f16
/* 70A50 8006FE50 C48A0038 */  lwc1       $f10, 0x38($a0)
/* 70A54 8006FE54 46104202 */  mul.s      $f8, $f8, $f16
/* 70A58 8006FE58 46020000 */  add.s      $f0, $f0, $f2
/* 70A5C 8006FE5C 46062100 */  add.s      $f4, $f4, $f6
/* 70A60 8006FE60 E4800030 */  swc1       $f0, 0x30($a0)
/* 70A64 8006FE64 460A4200 */  add.s      $f8, $f8, $f10
/* 70A68 8006FE68 E4840034 */  swc1       $f4, 0x34($a0)
/* 70A6C 8006FE6C 03E00008 */  jr         $ra
/* 70A70 8006FE70 E4880038 */   swc1      $f8, 0x38($a0)

glabel object_transform_to_matrix_2
/* 70A74 8006FE74 27BDFFF8 */  addiu      $sp, $sp, -0x8
/* 70A78 8006FE78 3C013780 */  lui        $at, (0x37800000 >> 16)
/* 70A7C 8006FE7C FFBF0000 */  sd         $ra, 0x0($sp)
/* 70A80 8006FE80 00803825 */  or         $a3, $a0, $zero
/* 70A84 8006FE84 44819000 */  mtc1       $at, $f18
/* 70A88 8006FE88 0C01C20C */  jal        sins_1
/* 70A8C 8006FE8C 84A40000 */   lh        $a0, 0x0($a1)
/* 70A90 8006FE90 44820000 */  mtc1       $v0, $f0
/* 70A94 8006FE94 84A40000 */  lh         $a0, 0x0($a1)
/* 70A98 8006FE98 46800020 */  cvt.s.w    $f0, $f0
/* 70A9C 8006FE9C 46120002 */  mul.s      $f0, $f0, $f18
/* 70AA0 8006FEA0 0C01C20B */  jal        coss_1
/* 70AA4 8006FEA4 00000000 */   nop
/* 70AA8 8006FEA8 44821000 */  mtc1       $v0, $f2
/* 70AAC 8006FEAC 84A40002 */  lh         $a0, 0x2($a1)
/* 70AB0 8006FEB0 468010A0 */  cvt.s.w    $f2, $f2
/* 70AB4 8006FEB4 46121082 */  mul.s      $f2, $f2, $f18
/* 70AB8 8006FEB8 0C01C20C */  jal        sins_1
/* 70ABC 8006FEBC 00000000 */   nop
/* 70AC0 8006FEC0 44822000 */  mtc1       $v0, $f4
/* 70AC4 8006FEC4 84A40002 */  lh         $a0, 0x2($a1)
/* 70AC8 8006FEC8 46802120 */  cvt.s.w    $f4, $f4
/* 70ACC 8006FECC 46122102 */  mul.s      $f4, $f4, $f18
/* 70AD0 8006FED0 0C01C20B */  jal        coss_1
/* 70AD4 8006FED4 00000000 */   nop
/* 70AD8 8006FED8 44823000 */  mtc1       $v0, $f6
/* 70ADC 8006FEDC 84A40004 */  lh         $a0, 0x4($a1)
/* 70AE0 8006FEE0 468031A0 */  cvt.s.w    $f6, $f6
/* 70AE4 8006FEE4 46123182 */  mul.s      $f6, $f6, $f18
/* 70AE8 8006FEE8 0C01C20C */  jal        sins_1
/* 70AEC 8006FEEC 00000000 */   nop
/* 70AF0 8006FEF0 44824000 */  mtc1       $v0, $f8
/* 70AF4 8006FEF4 84A40004 */  lh         $a0, 0x4($a1)
/* 70AF8 8006FEF8 46804220 */  cvt.s.w    $f8, $f8
/* 70AFC 8006FEFC 46124202 */  mul.s      $f8, $f8, $f18
/* 70B00 8006FF00 0C01C20B */  jal        coss_1
/* 70B04 8006FF04 00000000 */   nop
/* 70B08 8006FF08 44825000 */  mtc1       $v0, $f10
/* 70B0C 8006FF0C ACE0000C */  sw         $zero, 0xC($a3)
/* 70B10 8006FF10 E4E40018 */  swc1       $f4, 0x18($a3)
/* 70B14 8006FF14 468052A0 */  cvt.s.w    $f10, $f10
/* 70B18 8006FF18 ACE0001C */  sw         $zero, 0x1C($a3)
/* 70B1C 8006FF1C ACE0002C */  sw         $zero, 0x2C($a3)
/* 70B20 8006FF20 3C013F80 */  lui        $at, (0x3F800000 >> 16)
/* 70B24 8006FF24 46125282 */  mul.s      $f10, $f10, $f18
/* 70B28 8006FF28 00000000 */  nop
/* 70B2C 8006FF2C 46082402 */  mul.s      $f16, $f4, $f8
/* 70B30 8006FF30 00000000 */  nop
/* 70B34 8006FF34 46008402 */  mul.s      $f16, $f16, $f0
/* 70B38 8006FF38 00000000 */  nop
/* 70B3C 8006FF3C 460A1482 */  mul.s      $f18, $f2, $f10
/* 70B40 8006FF40 46109401 */  sub.s      $f16, $f18, $f16
/* 70B44 8006FF44 E4F00000 */  swc1       $f16, 0x0($a3)
/* 70B48 8006FF48 460A2402 */  mul.s      $f16, $f4, $f10
/* 70B4C 8006FF4C 00000000 */  nop
/* 70B50 8006FF50 46008402 */  mul.s      $f16, $f16, $f0
/* 70B54 8006FF54 00000000 */  nop
/* 70B58 8006FF58 46081482 */  mul.s      $f18, $f2, $f8
/* 70B5C 8006FF5C 46128400 */  add.s      $f16, $f16, $f18
/* 70B60 8006FF60 E4F00004 */  swc1       $f16, 0x4($a3)
/* 70B64 8006FF64 46060402 */  mul.s      $f16, $f0, $f6
/* 70B68 8006FF68 46008407 */  neg.s      $f16, $f16
/* 70B6C 8006FF6C E4F00008 */  swc1       $f16, 0x8($a3)
/* 70B70 8006FF70 46083402 */  mul.s      $f16, $f6, $f8
/* 70B74 8006FF74 46008407 */  neg.s      $f16, $f16
/* 70B78 8006FF78 E4F00010 */  swc1       $f16, 0x10($a3)
/* 70B7C 8006FF7C 460A3402 */  mul.s      $f16, $f6, $f10
/* 70B80 8006FF80 E4F00014 */  swc1       $f16, 0x14($a3)
/* 70B84 8006FF84 46082402 */  mul.s      $f16, $f4, $f8
/* 70B88 8006FF88 00000000 */  nop
/* 70B8C 8006FF8C 46028402 */  mul.s      $f16, $f16, $f2
/* 70B90 8006FF90 00000000 */  nop
/* 70B94 8006FF94 460A0482 */  mul.s      $f18, $f0, $f10
/* 70B98 8006FF98 46128400 */  add.s      $f16, $f16, $f18
/* 70B9C 8006FF9C E4F00020 */  swc1       $f16, 0x20($a3)
/* 70BA0 8006FFA0 460A2402 */  mul.s      $f16, $f4, $f10
/* 70BA4 8006FFA4 00000000 */  nop
/* 70BA8 8006FFA8 46028402 */  mul.s      $f16, $f16, $f2
/* 70BAC 8006FFAC 00000000 */  nop
/* 70BB0 8006FFB0 46080482 */  mul.s      $f18, $f0, $f8
/* 70BB4 8006FFB4 46109401 */  sub.s      $f16, $f18, $f16
/* 70BB8 8006FFB8 C4F20000 */  lwc1       $f18, 0x0($a3)
/* 70BBC 8006FFBC E4F00024 */  swc1       $f16, 0x24($a3)
/* 70BC0 8006FFC0 46061402 */  mul.s      $f16, $f2, $f6
/* 70BC4 8006FFC4 E4F00028 */  swc1       $f16, 0x28($a3)
/* 70BC8 8006FFC8 C4A0000C */  lwc1       $f0, 0xC($a1)
/* 70BCC 8006FFCC C4A20010 */  lwc1       $f2, 0x10($a1)
/* 70BD0 8006FFD0 C4F00010 */  lwc1       $f16, 0x10($a3)
/* 70BD4 8006FFD4 46009482 */  mul.s      $f18, $f18, $f0
/* 70BD8 8006FFD8 C4A40014 */  lwc1       $f4, 0x14($a1)
/* 70BDC 8006FFDC 46028402 */  mul.s      $f16, $f16, $f2
/* 70BE0 8006FFE0 46128400 */  add.s      $f16, $f16, $f18
/* 70BE4 8006FFE4 C4F20020 */  lwc1       $f18, 0x20($a3)
/* 70BE8 8006FFE8 46049482 */  mul.s      $f18, $f18, $f4
/* 70BEC 8006FFEC 46128400 */  add.s      $f16, $f16, $f18
/* 70BF0 8006FFF0 C4F20004 */  lwc1       $f18, 0x4($a3)
/* 70BF4 8006FFF4 E4F00030 */  swc1       $f16, 0x30($a3)
/* 70BF8 8006FFF8 46009482 */  mul.s      $f18, $f18, $f0
/* 70BFC 8006FFFC C4F00014 */  lwc1       $f16, 0x14($a3)
/* 70C00 80070000 46028402 */  mul.s      $f16, $f16, $f2
/* 70C04 80070004 46128400 */  add.s      $f16, $f16, $f18
/* 70C08 80070008 C4F20024 */  lwc1       $f18, 0x24($a3)
/* 70C0C 8007000C 46049482 */  mul.s      $f18, $f18, $f4
/* 70C10 80070010 46128400 */  add.s      $f16, $f16, $f18
/* 70C14 80070014 C4F20008 */  lwc1       $f18, 0x8($a3)
/* 70C18 80070018 E4F00034 */  swc1       $f16, 0x34($a3)
/* 70C1C 8007001C 46009482 */  mul.s      $f18, $f18, $f0
/* 70C20 80070020 C4F00018 */  lwc1       $f16, 0x18($a3)
/* 70C24 80070024 46028402 */  mul.s      $f16, $f16, $f2
/* 70C28 80070028 46128400 */  add.s      $f16, $f16, $f18
/* 70C2C 8007002C C4F20028 */  lwc1       $f18, 0x28($a3)
/* 70C30 80070030 46049482 */  mul.s      $f18, $f18, $f4
/* 70C34 80070034 46128400 */  add.s      $f16, $f16, $f18
/* 70C38 80070038 E4F00038 */  swc1       $f16, 0x38($a3)
/* 70C3C 8007003C 44818000 */  mtc1       $at, $f16
/* 70C40 80070040 00000000 */  nop
/* 70C44 80070044 E4F0003C */  swc1       $f16, 0x3C($a3)
/* 70C48 80070048 DFBF0000 */  ld         $ra, 0x0($sp)
/* 70C4C 8007004C 27BD0008 */  addiu      $sp, $sp, 0x8
/* 70C50 80070050 03E00008 */  jr         $ra
/* 70C54 80070054 00000000 */   nop

glabel func_80070058
/* 70C58 80070058 27BDFFF8 */  addiu      $sp, $sp, -0x8
/* 70C5C 8007005C 3C013780 */  lui        $at, (0x37800000 >> 16)
/* 70C60 80070060 FFBF0000 */  sd         $ra, 0x0($sp)
/* 70C64 80070064 00803825 */  or         $a3, $a0, $zero
/* 70C68 80070068 44819000 */  mtc1       $at, $f18
/* 70C6C 8007006C 0C01C20C */  jal        sins_1
/* 70C70 80070070 84A40000 */   lh        $a0, 0x0($a1)
/* 70C74 80070074 44820000 */  mtc1       $v0, $f0
/* 70C78 80070078 84A40000 */  lh         $a0, 0x0($a1)
/* 70C7C 8007007C 46800020 */  cvt.s.w    $f0, $f0
/* 70C80 80070080 46120002 */  mul.s      $f0, $f0, $f18
/* 70C84 80070084 0C01C20B */  jal        coss_1
/* 70C88 80070088 00000000 */   nop
/* 70C8C 8007008C 44821000 */  mtc1       $v0, $f2
/* 70C90 80070090 84A40002 */  lh         $a0, 0x2($a1)
/* 70C94 80070094 468010A0 */  cvt.s.w    $f2, $f2
/* 70C98 80070098 46121082 */  mul.s      $f2, $f2, $f18
/* 70C9C 8007009C 0C01C20C */  jal        sins_1
/* 70CA0 800700A0 00000000 */   nop
/* 70CA4 800700A4 44822000 */  mtc1       $v0, $f4
/* 70CA8 800700A8 84A40002 */  lh         $a0, 0x2($a1)
/* 70CAC 800700AC 46802120 */  cvt.s.w    $f4, $f4
/* 70CB0 800700B0 46122102 */  mul.s      $f4, $f4, $f18
/* 70CB4 800700B4 0C01C20B */  jal        coss_1
/* 70CB8 800700B8 00000000 */   nop
/* 70CBC 800700BC 44823000 */  mtc1       $v0, $f6
/* 70CC0 800700C0 84A40004 */  lh         $a0, 0x4($a1)
/* 70CC4 800700C4 468031A0 */  cvt.s.w    $f6, $f6
/* 70CC8 800700C8 46123182 */  mul.s      $f6, $f6, $f18
/* 70CCC 800700CC 0C01C20C */  jal        sins_1
/* 70CD0 800700D0 00000000 */   nop
/* 70CD4 800700D4 44824000 */  mtc1       $v0, $f8
/* 70CD8 800700D8 84A40004 */  lh         $a0, 0x4($a1)
/* 70CDC 800700DC 46804220 */  cvt.s.w    $f8, $f8
/* 70CE0 800700E0 46124202 */  mul.s      $f8, $f8, $f18
/* 70CE4 800700E4 0C01C20B */  jal        coss_1
/* 70CE8 800700E8 00000000 */   nop
/* 70CEC 800700EC 44825000 */  mtc1       $v0, $f10
/* 70CF0 800700F0 3C013F80 */  lui        $at, (0x3F800000 >> 16)
/* 70CF4 800700F4 ACE0000C */  sw         $zero, 0xC($a3)
/* 70CF8 800700F8 468052A0 */  cvt.s.w    $f10, $f10
/* 70CFC 800700FC ACE0001C */  sw         $zero, 0x1C($a3)
/* 70D00 80070100 ACE0002C */  sw         $zero, 0x2C($a3)
/* 70D04 80070104 46125282 */  mul.s      $f10, $f10, $f18
/* 70D08 80070108 44819000 */  mtc1       $at, $f18
/* 70D0C 8007010C 46060302 */  mul.s      $f12, $f0, $f6
/* 70D10 80070110 E4F2003C */  swc1       $f18, 0x3C($a3)
/* 70D14 80070114 DFBF0000 */  ld         $ra, 0x0($sp)
/* 70D18 80070118 27BD0008 */  addiu      $sp, $sp, 0x8
/* 70D1C 8007011C 460A1382 */  mul.s      $f14, $f2, $f10
/* 70D20 80070120 00000000 */  nop
/* 70D24 80070124 46080402 */  mul.s      $f16, $f0, $f8
/* 70D28 80070128 03E00008 */  jr         $ra
/* 70D2C 8007012C 00000000 */   nop

glabel f32_matrix_from_rotation_and_scale
/* 70D30 80070130 27BDFFF8 */  addiu      $sp, $sp, -0x8
/* 70D34 80070134 00E0C825 */  or         $t9, $a3, $zero
/* 70D38 80070138 3C013780 */  lui        $at, (0x37800000 >> 16)
/* 70D3C 8007013C FFBF0000 */  sd         $ra, 0x0($sp)
/* 70D40 80070140 00803825 */  or         $a3, $a0, $zero
/* 70D44 80070144 44819000 */  mtc1       $at, $f18
/* 70D48 80070148 0C01C20C */  jal        sins_1
/* 70D4C 8007014C 00A02025 */   or        $a0, $a1, $zero
/* 70D50 80070150 44824000 */  mtc1       $v0, $f8
/* 70D54 80070154 00A02025 */  or         $a0, $a1, $zero
/* 70D58 80070158 46804220 */  cvt.s.w    $f8, $f8
/* 70D5C 8007015C 46124202 */  mul.s      $f8, $f8, $f18
/* 70D60 80070160 0C01C20B */  jal        coss_1
/* 70D64 80070164 00000000 */   nop
/* 70D68 80070168 44825000 */  mtc1       $v0, $f10
/* 70D6C 8007016C 44868000 */  mtc1       $a2, $f16
/* 70D70 80070170 3C013F80 */  lui        $at, (0x3F800000 >> 16)
/* 70D74 80070174 468052A0 */  cvt.s.w    $f10, $f10
/* 70D78 80070178 E4F00028 */  swc1       $f16, 0x28($a3)
/* 70D7C 8007017C ACE00008 */  sw         $zero, 0x8($a3)
/* 70D80 80070180 ACE0000C */  sw         $zero, 0xC($a3)
/* 70D84 80070184 ACE00018 */  sw         $zero, 0x18($a3)
/* 70D88 80070188 ACE0001C */  sw         $zero, 0x1C($a3)
/* 70D8C 8007018C 46125282 */  mul.s      $f10, $f10, $f18
/* 70D90 80070190 44999000 */  mtc1       $t9, $f18
/* 70D94 80070194 ACE00020 */  sw         $zero, 0x20($a3)
/* 70D98 80070198 ACE00024 */  sw         $zero, 0x24($a3)
/* 70D9C 8007019C ACE0002C */  sw         $zero, 0x2C($a3)
/* 70DA0 800701A0 ACE00030 */  sw         $zero, 0x30($a3)
/* 70DA4 800701A4 ACE00034 */  sw         $zero, 0x34($a3)
/* 70DA8 800701A8 46105282 */  mul.s      $f10, $f10, $f16
/* 70DAC 800701AC ACE00038 */  sw         $zero, 0x38($a3)
/* 70DB0 800701B0 46104202 */  mul.s      $f8, $f8, $f16
/* 70DB4 800701B4 44818000 */  mtc1       $at, $f16
/* 70DB8 800701B8 E4EA0000 */  swc1       $f10, 0x0($a3)
/* 70DBC 800701BC 46125282 */  mul.s      $f10, $f10, $f18
/* 70DC0 800701C0 E4F0003C */  swc1       $f16, 0x3C($a3)
/* 70DC4 800701C4 E4E80004 */  swc1       $f8, 0x4($a3)
/* 70DC8 800701C8 46004207 */  neg.s      $f8, $f8
/* 70DCC 800701CC E4E80010 */  swc1       $f8, 0x10($a3)
/* 70DD0 800701D0 E4EA0014 */  swc1       $f10, 0x14($a3)
/* 70DD4 800701D4 DFBF0000 */  ld         $ra, 0x0($sp)
/* 70DD8 800701D8 27BD0008 */  addiu      $sp, $sp, 0x8
/* 70DDC 800701DC 03E00008 */  jr         $ra
/* 70DE0 800701E0 00000000 */   nop

/* Handwritten function */
glabel s16_vec3_apply_object_rotation
/* 70DE4 800701E4 27BDFFF8 */  addiu      $sp, $sp, -0x8
/* 70DE8 800701E8 FFBF0000 */  sd         $ra, 0x0($sp)
/* 70DEC 800701EC 00803025 */  or         $a2, $a0, $zero
/* 70DF0 800701F0 84AB0000 */  lh         $t3, 0x0($a1)
/* 70DF4 800701F4 84AC0002 */  lh         $t4, 0x2($a1)
/* 70DF8 800701F8 84AD0004 */  lh         $t5, 0x4($a1)
/* 70DFC 800701FC 0C01C20C */  jal        sins_1
/* 70E00 80070200 84C40000 */   lh        $a0, 0x0($a2)
/* 70E04 80070204 00407025 */  or         $t6, $v0, $zero
/* 70E08 80070208 0C01C20B */  jal        coss_1
/* 70E0C 8007020C 84C40000 */   lh        $a0, 0x0($a2)
/* 70E10 80070210 016E0018 */  mult       $t3, $t6
/* 70E14 80070214 00407825 */  or         $t7, $v0, $zero
/* 70E18 80070218 84C40002 */  lh         $a0, 0x2($a2)
/* 70E1C 8007021C 00004012 */  mflo       $t0
/* 70E20 80070220 00000000 */  nop
/* 70E24 80070224 00000000 */  nop
/* 70E28 80070228 018E0018 */  mult       $t4, $t6
/* 70E2C 8007022C 00004812 */  mflo       $t1
/* 70E30 80070230 00000000 */  nop
/* 70E34 80070234 00000000 */  nop
/* 70E38 80070238 016F0018 */  mult       $t3, $t7
/* 70E3C 8007023C 00005812 */  mflo       $t3
/* 70E40 80070240 01695822 */  sub        $t3, $t3, $t1 /* handwritten instruction */
/* 70E44 80070244 000B5C03 */  sra        $t3, $t3, 16
/* 70E48 80070248 018F0018 */  mult       $t4, $t7
/* 70E4C 8007024C 00006012 */  mflo       $t4
/* 70E50 80070250 01886020 */  add        $t4, $t4, $t0 /* handwritten instruction */
/* 70E54 80070254 0C01C20C */  jal        sins_1
/* 70E58 80070258 000C6403 */   sra       $t4, $t4, 16
/* 70E5C 8007025C 00407025 */  or         $t6, $v0, $zero
/* 70E60 80070260 0C01C20B */  jal        coss_1
/* 70E64 80070264 84C40002 */   lh        $a0, 0x2($a2)
/* 70E68 80070268 018E0018 */  mult       $t4, $t6
/* 70E6C 8007026C 00407825 */  or         $t7, $v0, $zero
/* 70E70 80070270 84C40004 */  lh         $a0, 0x4($a2)
/* 70E74 80070274 00004012 */  mflo       $t0
/* 70E78 80070278 00000000 */  nop
/* 70E7C 8007027C 00000000 */  nop
/* 70E80 80070280 01AE0018 */  mult       $t5, $t6
/* 70E84 80070284 00004812 */  mflo       $t1
/* 70E88 80070288 00000000 */  nop
/* 70E8C 8007028C 00000000 */  nop
/* 70E90 80070290 018F0018 */  mult       $t4, $t7
/* 70E94 80070294 00006012 */  mflo       $t4
/* 70E98 80070298 01896022 */  sub        $t4, $t4, $t1 /* handwritten instruction */
/* 70E9C 8007029C 000C6403 */  sra        $t4, $t4, 16
/* 70EA0 800702A0 01AF0018 */  mult       $t5, $t7
/* 70EA4 800702A4 00006812 */  mflo       $t5
/* 70EA8 800702A8 01A86820 */  add        $t5, $t5, $t0 /* handwritten instruction */
/* 70EAC 800702AC 0C01C20C */  jal        sins_1
/* 70EB0 800702B0 000D6C03 */   sra       $t5, $t5, 16
/* 70EB4 800702B4 00407025 */  or         $t6, $v0, $zero
/* 70EB8 800702B8 0C01C20B */  jal        coss_1
/* 70EBC 800702BC 84C40004 */   lh        $a0, 0x4($a2)
/* 70EC0 800702C0 016E0018 */  mult       $t3, $t6
/* 70EC4 800702C4 00407825 */  or         $t7, $v0, $zero
/* 70EC8 800702C8 A4AC0002 */  sh         $t4, 0x2($a1)
/* 70ECC 800702CC 00004012 */  mflo       $t0
/* 70ED0 800702D0 00000000 */  nop
/* 70ED4 800702D4 00000000 */  nop
/* 70ED8 800702D8 01AE0018 */  mult       $t5, $t6
/* 70EDC 800702DC 00004812 */  mflo       $t1
/* 70EE0 800702E0 00000000 */  nop
/* 70EE4 800702E4 00000000 */  nop
/* 70EE8 800702E8 016F0018 */  mult       $t3, $t7
/* 70EEC 800702EC 00005812 */  mflo       $t3
/* 70EF0 800702F0 01695820 */  add        $t3, $t3, $t1 /* handwritten instruction */
/* 70EF4 800702F4 000B5C03 */  sra        $t3, $t3, 16
/* 70EF8 800702F8 01AF0018 */  mult       $t5, $t7
/* 70EFC 800702FC A4AB0000 */  sh         $t3, 0x0($a1)
/* 70F00 80070300 00006812 */  mflo       $t5
/* 70F04 80070304 01A86822 */  sub        $t5, $t5, $t0 /* handwritten instruction */
/* 70F08 80070308 000D6C03 */  sra        $t5, $t5, 16
/* 70F0C 8007030C A4AD0004 */  sh         $t5, 0x4($a1)
/* 70F10 80070310 DFBF0000 */  ld         $ra, 0x0($sp)
/* 70F14 80070314 27BD0008 */  addiu      $sp, $sp, 0x8
/* 70F18 80070318 03E00008 */  jr         $ra
/* 70F1C 8007031C 00000000 */   nop

glabel f32_vec3_apply_object_rotation
/* 70F20 80070320 27BDFFF8 */  addiu      $sp, $sp, -0x8
/* 70F24 80070324 FFBF0000 */  sd         $ra, 0x0($sp)
/* 70F28 80070328 00803025 */  or         $a2, $a0, $zero
/* 70F2C 8007032C C4A40000 */  lwc1       $f4, 0x0($a1)
/* 70F30 80070330 C4A60004 */  lwc1       $f6, 0x4($a1)
/* 70F34 80070334 C4A80008 */  lwc1       $f8, 0x8($a1)
/* 70F38 80070338 0C01C1F1 */  jal        sins_f
/* 70F3C 8007033C 84C40004 */   lh        $a0, 0x4($a2)
/* 70F40 80070340 46002282 */  mul.s      $f10, $f4, $f0
/* 70F44 80070344 84C40004 */  lh         $a0, 0x4($a2)
/* 70F48 80070348 46003302 */  mul.s      $f12, $f6, $f0
/* 70F4C 8007034C 0C01C1FE */  jal        coss_f
/* 70F50 80070350 00000000 */   nop
/* 70F54 80070354 46002102 */  mul.s      $f4, $f4, $f0
/* 70F58 80070358 84C40002 */  lh         $a0, 0x2($a2)
/* 70F5C 8007035C 46003182 */  mul.s      $f6, $f6, $f0
/* 70F60 80070360 460C2101 */  sub.s      $f4, $f4, $f12
/* 70F64 80070364 0C01C1F1 */  jal        sins_f
/* 70F68 80070368 460A3180 */   add.s     $f6, $f6, $f10
/* 70F6C 8007036C 46003282 */  mul.s      $f10, $f6, $f0
/* 70F70 80070370 84C40002 */  lh         $a0, 0x2($a2)
/* 70F74 80070374 46004302 */  mul.s      $f12, $f8, $f0
/* 70F78 80070378 0C01C1FE */  jal        coss_f
/* 70F7C 8007037C 00000000 */   nop
/* 70F80 80070380 46003182 */  mul.s      $f6, $f6, $f0
/* 70F84 80070384 84C40000 */  lh         $a0, 0x0($a2)
/* 70F88 80070388 46004202 */  mul.s      $f8, $f8, $f0
/* 70F8C 8007038C 460C3181 */  sub.s      $f6, $f6, $f12
/* 70F90 80070390 0C01C1F1 */  jal        sins_f
/* 70F94 80070394 460A4200 */   add.s     $f8, $f8, $f10
/* 70F98 80070398 46002282 */  mul.s      $f10, $f4, $f0
/* 70F9C 8007039C 84C40000 */  lh         $a0, 0x0($a2)
/* 70FA0 800703A0 46004302 */  mul.s      $f12, $f8, $f0
/* 70FA4 800703A4 0C01C1FE */  jal        coss_f
/* 70FA8 800703A8 00000000 */   nop
/* 70FAC 800703AC 46002102 */  mul.s      $f4, $f4, $f0
/* 70FB0 800703B0 E4A60004 */  swc1       $f6, 0x4($a1)
/* 70FB4 800703B4 46004202 */  mul.s      $f8, $f8, $f0
/* 70FB8 800703B8 460C2100 */  add.s      $f4, $f4, $f12
/* 70FBC 800703BC 460A4201 */  sub.s      $f8, $f8, $f10
/* 70FC0 800703C0 E4A40000 */  swc1       $f4, 0x0($a1)
/* 70FC4 800703C4 E4A80008 */  swc1       $f8, 0x8($a1)
/* 70FC8 800703C8 DFBF0000 */  ld         $ra, 0x0($sp)
/* 70FCC 800703CC 27BD0008 */  addiu      $sp, $sp, 0x8
/* 70FD0 800703D0 03E00008 */  jr         $ra
/* 70FD4 800703D4 00000000 */   nop

glabel f32_vec3_apply_object_rotation2
/* 70FD8 800703D8 27BDFFF8 */  addiu      $sp, $sp, -0x8
/* 70FDC 800703DC FFBF0000 */  sd         $ra, 0x0($sp)
/* 70FE0 800703E0 00803025 */  or         $a2, $a0, $zero
/* 70FE4 800703E4 C4A40000 */  lwc1       $f4, 0x0($a1)
/* 70FE8 800703E8 C4A60004 */  lwc1       $f6, 0x4($a1)
/* 70FEC 800703EC C4A80008 */  lwc1       $f8, 0x8($a1)
/* 70FF0 800703F0 0C01C1F1 */  jal        sins_f
/* 70FF4 800703F4 84C40000 */   lh        $a0, 0x0($a2)
/* 70FF8 800703F8 46002282 */  mul.s      $f10, $f4, $f0
/* 70FFC 800703FC 84C40000 */  lh         $a0, 0x0($a2)
/* 71000 80070400 46004302 */  mul.s      $f12, $f8, $f0
/* 71004 80070404 0C01C1FE */  jal        coss_f
/* 71008 80070408 00000000 */   nop
/* 7100C 8007040C 46002102 */  mul.s      $f4, $f4, $f0
/* 71010 80070410 84C40002 */  lh         $a0, 0x2($a2)
/* 71014 80070414 46004202 */  mul.s      $f8, $f8, $f0
/* 71018 80070418 460C2100 */  add.s      $f4, $f4, $f12
/* 7101C 8007041C 0C01C1F1 */  jal        sins_f
/* 71020 80070420 460A4201 */   sub.s     $f8, $f8, $f10
/* 71024 80070424 46003282 */  mul.s      $f10, $f6, $f0
/* 71028 80070428 84C40002 */  lh         $a0, 0x2($a2)
/* 7102C 8007042C 46004302 */  mul.s      $f12, $f8, $f0
/* 71030 80070430 0C01C1FE */  jal        coss_f
/* 71034 80070434 00000000 */   nop
/* 71038 80070438 46003182 */  mul.s      $f6, $f6, $f0
/* 7103C 8007043C 84C40004 */  lh         $a0, 0x4($a2)
/* 71040 80070440 46004202 */  mul.s      $f8, $f8, $f0
/* 71044 80070444 460C3181 */  sub.s      $f6, $f6, $f12
/* 71048 80070448 0C01C1F1 */  jal        sins_f
/* 7104C 8007044C 460A4200 */   add.s     $f8, $f8, $f10
/* 71050 80070450 46002282 */  mul.s      $f10, $f4, $f0
/* 71054 80070454 84C40004 */  lh         $a0, 0x4($a2)
/* 71058 80070458 46003302 */  mul.s      $f12, $f6, $f0
/* 7105C 8007045C 0C01C1FE */  jal        coss_f
/* 71060 80070460 00000000 */   nop
/* 71064 80070464 46002102 */  mul.s      $f4, $f4, $f0
/* 71068 80070468 E4A80008 */  swc1       $f8, 0x8($a1)
/* 7106C 8007046C 46003182 */  mul.s      $f6, $f6, $f0
/* 71070 80070470 460C2101 */  sub.s      $f4, $f4, $f12
/* 71074 80070474 460A3180 */  add.s      $f6, $f6, $f10
/* 71078 80070478 E4A40000 */  swc1       $f4, 0x0($a1)
/* 7107C 8007047C E4A60004 */  swc1       $f6, 0x4($a1)
/* 71080 80070480 DFBF0000 */  ld         $ra, 0x0($sp)
/* 71084 80070484 27BD0008 */  addiu      $sp, $sp, 0x8
/* 71088 80070488 03E00008 */  jr         $ra
/* 7108C 8007048C 00000000 */   nop

glabel f32_vec3_apply_object_rotation3
/* 71090 80070490 27BDFFF8 */  addiu      $sp, $sp, -0x8
/* 71094 80070494 FFBF0000 */  sd         $ra, 0x0($sp)
/* 71098 80070498 00803025 */  or         $a2, $a0, $zero
/* 7109C 8007049C C4A80008 */  lwc1       $f8, 0x8($a1)
/* 710A0 800704A0 0C01C1F1 */  jal        sins_f
/* 710A4 800704A4 84C40002 */   lh        $a0, 0x2($a2)
/* 710A8 800704A8 46004182 */  mul.s      $f6, $f8, $f0
/* 710AC 800704AC 0C01C1FE */  jal        coss_f
/* 710B0 800704B0 84C40002 */   lh        $a0, 0x2($a2)
/* 710B4 800704B4 46004202 */  mul.s      $f8, $f8, $f0
/* 710B8 800704B8 46003187 */  neg.s      $f6, $f6
/* 710BC 800704BC 0C01C1F1 */  jal        sins_f
/* 710C0 800704C0 84C40000 */   lh        $a0, 0x0($a2)
/* 710C4 800704C4 46004102 */  mul.s      $f4, $f8, $f0
/* 710C8 800704C8 0C01C1FE */  jal        coss_f
/* 710CC 800704CC 84C40000 */   lh        $a0, 0x0($a2)
/* 710D0 800704D0 46004202 */  mul.s      $f8, $f8, $f0
/* 710D4 800704D4 E4A40000 */  swc1       $f4, 0x0($a1)
/* 710D8 800704D8 E4A60004 */  swc1       $f6, 0x4($a1)
/* 710DC 800704DC E4A80008 */  swc1       $f8, 0x8($a1)
/* 710E0 800704E0 DFBF0000 */  ld         $ra, 0x0($sp)
/* 710E4 800704E4 27BD0008 */  addiu      $sp, $sp, 0x8
/* 710E8 800704E8 03E00008 */  jr         $ra
/* 710EC 800704EC 00000000 */   nop

/* Handwritten function */
glabel point_triangle_2d_xz_intersection
/* 710F0 800704F0 8FAE0010 */  lw         $t6, 0x10($sp)
/* 710F4 800704F4 84C80000 */  lh         $t0, 0x0($a2)
/* 710F8 800704F8 84C90004 */  lh         $t1, 0x4($a2)
/* 710FC 800704FC 84EB0004 */  lh         $t3, 0x4($a3)
/* 71100 80070500 85CC0000 */  lh         $t4, 0x0($t6)
/* 71104 80070504 85CD0004 */  lh         $t5, 0x4($t6)
/* 71108 80070508 00887022 */  sub        $t6, $a0, $t0 /* handwritten instruction */
/* 7110C 8007050C 01697822 */  sub        $t7, $t3, $t1 /* handwritten instruction */
/* 71110 80070510 01CF0019 */  multu      $t6, $t7
/* 71114 80070514 84EA0000 */  lh         $t2, 0x0($a3)
/* 71118 80070518 00A9C822 */  sub        $t9, $a1, $t1 /* handwritten instruction */
/* 7111C 8007051C 24020000 */  addiu      $v0, $zero, 0x0
/* 71120 80070520 0148C022 */  sub        $t8, $t2, $t0 /* handwritten instruction */
/* 71124 80070524 34070001 */  ori        $a3, $zero, 0x1
/* 71128 80070528 00007012 */  mflo       $t6
/* 7112C 8007052C 00007012 */  mflo       $t6
/* 71130 80070530 00000000 */  nop
/* 71134 80070534 00000000 */  nop
/* 71138 80070538 03190019 */  multu      $t8, $t9
/* 7113C 8007053C 00007812 */  mflo       $t7
/* 71140 80070540 0000C012 */  mflo       $t8
/* 71144 80070544 01CF7022 */  sub        $t6, $t6, $t7 /* handwritten instruction */
/* 71148 80070548 05C30003 */  bgezl      $t6, .L80070558
/* 7114C 8007054C 008A7022 */   sub       $t6, $a0, $t2 /* handwritten instruction */
/* 71150 80070550 00E73826 */  xor        $a3, $a3, $a3
/* 71154 80070554 008A7022 */  sub        $t6, $a0, $t2 /* handwritten instruction */
.L80070558:
/* 71158 80070558 01AB7822 */  sub        $t7, $t5, $t3 /* handwritten instruction */
/* 7115C 8007055C 01CF0019 */  multu      $t6, $t7
/* 71160 80070560 018AC022 */  sub        $t8, $t4, $t2 /* handwritten instruction */
/* 71164 80070564 00ABC822 */  sub        $t9, $a1, $t3 /* handwritten instruction */
/* 71168 80070568 34060001 */  ori        $a2, $zero, 0x1
/* 7116C 8007056C 00007012 */  mflo       $t6
/* 71170 80070570 00007012 */  mflo       $t6
/* 71174 80070574 00000000 */  nop
/* 71178 80070578 00000000 */  nop
/* 7117C 8007057C 03190019 */  multu      $t8, $t9
/* 71180 80070580 00007812 */  mflo       $t7
/* 71184 80070584 0000C012 */  mflo       $t8
/* 71188 80070588 01CF7022 */  sub        $t6, $t6, $t7 /* handwritten instruction */
/* 7118C 8007058C 05C10002 */  bgez       $t6, .L80070598
/* 71190 80070590 00000000 */   nop
/* 71194 80070594 00C63026 */  xor        $a2, $a2, $a2
.L80070598:
/* 71198 80070598 14E60015 */  bne        $a3, $a2, .L800705F0
/* 7119C 8007059C 00000000 */   nop
/* 711A0 800705A0 008C7022 */  sub        $t6, $a0, $t4 /* handwritten instruction */
/* 711A4 800705A4 012D7822 */  sub        $t7, $t1, $t5 /* handwritten instruction */
/* 711A8 800705A8 01CF0019 */  multu      $t6, $t7
/* 711AC 800705AC 010CC022 */  sub        $t8, $t0, $t4 /* handwritten instruction */
/* 711B0 800705B0 00ADC822 */  sub        $t9, $a1, $t5 /* handwritten instruction */
/* 711B4 800705B4 34050001 */  ori        $a1, $zero, 0x1
/* 711B8 800705B8 00007012 */  mflo       $t6
/* 711BC 800705BC 00007012 */  mflo       $t6
/* 711C0 800705C0 00000000 */  nop
/* 711C4 800705C4 00000000 */  nop
/* 711C8 800705C8 03190019 */  multu      $t8, $t9
/* 711CC 800705CC 00007812 */  mflo       $t7
/* 711D0 800705D0 0000C012 */  mflo       $t8
/* 711D4 800705D4 01CF7022 */  sub        $t6, $t6, $t7 /* handwritten instruction */
/* 711D8 800705D8 05C10002 */  bgez       $t6, .L800705E4
/* 711DC 800705DC 00000000 */   nop
/* 711E0 800705E0 00A52826 */  xor        $a1, $a1, $a1
.L800705E4:
/* 711E4 800705E4 14A60002 */  bne        $a1, $a2, .L800705F0
/* 711E8 800705E8 00000000 */   nop
/* 711EC 800705EC 34020001 */  ori        $v0, $zero, 0x1
.L800705F0:
/* 711F0 800705F0 03E00008 */  jr         $ra
/* 711F4 800705F4 00000000 */   nop

glabel f32_matrix_from_position
/* 711F8 800705F8 00804025 */  or         $t0, $a0, $zero
/* 711FC 800705FC 25090040 */  addiu      $t1, $t0, 0x40
.L80070600:
/* 71200 80070600 25080004 */  addiu      $t0, $t0, 0x4
/* 71204 80070604 1528FFFE */  bne        $t1, $t0, .L80070600
/* 71208 80070608 AD00FFFC */   sw        $zero, -0x4($t0)
/* 7120C 8007060C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
/* 71210 80070610 44819000 */  mtc1       $at, $f18
/* 71214 80070614 00000000 */  nop
/* 71218 80070618 E4920000 */  swc1       $f18, 0x0($a0)
/* 7121C 8007061C E4920014 */  swc1       $f18, 0x14($a0)
/* 71220 80070620 E4920028 */  swc1       $f18, 0x28($a0)
/* 71224 80070624 E492003C */  swc1       $f18, 0x3C($a0)
/* 71228 80070628 AC850030 */  sw         $a1, 0x30($a0)
/* 7122C 8007062C AC860034 */  sw         $a2, 0x34($a0)
/* 71230 80070630 03E00008 */  jr         $ra
/* 71234 80070634 AC870038 */   sw        $a3, 0x38($a0)

glabel f32_matrix_from_scale
/* 71238 80070638 00804025 */  or         $t0, $a0, $zero
/* 7123C 8007063C 25090040 */  addiu      $t1, $t0, 0x40
.L80070640:
/* 71240 80070640 25080004 */  addiu      $t0, $t0, 0x4
/* 71244 80070644 1528FFFE */  bne        $t1, $t0, .L80070640
/* 71248 80070648 AD00FFFC */   sw        $zero, -0x4($t0)
/* 7124C 8007064C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
/* 71250 80070650 44819000 */  mtc1       $at, $f18
/* 71254 80070654 00000000 */  nop
/* 71258 80070658 E492003C */  swc1       $f18, 0x3C($a0)
/* 7125C 8007065C AC850000 */  sw         $a1, 0x0($a0)
/* 71260 80070660 AC860014 */  sw         $a2, 0x14($a0)
/* 71264 80070664 03E00008 */  jr         $ra
/* 71268 80070668 AC870028 */   sw        $a3, 0x28($a0)

glabel atan2s
/* 7126C 8007066C 00854025 */  or         $t0, $a0, $a1
/* 71270 80070670 14080003 */  bne        $zero, $t0, .L80070680
/* 71274 80070674 00000000 */   nop
/* 71278 80070678 03E00008 */  jr         $ra
/* 7127C 8007067C 24020000 */   addiu     $v0, $zero, 0x0
.L80070680:
/* 71280 80070680 04800005 */  bltz       $a0, .L80070698
/* 71284 80070684 00000000 */   nop
/* 71288 80070688 04A2000B */  bltzl      $a1, .L800706B8
/* 7128C 8007068C 00052823 */   negu      $a1, $a1
/* 71290 80070690 0801C1B2 */  j          .L800706C8
/* 71294 80070694 24020000 */   addiu     $v0, $zero, 0x0
.L80070698:
/* 71298 80070698 04A00003 */  bltz       $a1, .L800706A8
/* 7129C 8007069C 00042023 */   negu      $a0, $a0
/* 712A0 800706A0 0801C1AF */  j          .L800706BC
/* 712A4 800706A4 3402C000 */   ori       $v0, $zero, 0xC000
.L800706A8:
/* 712A8 800706A8 00052823 */  negu       $a1, $a1
/* 712AC 800706AC 0801C1B2 */  j          .L800706C8
/* 712B0 800706B0 34028000 */   ori       $v0, $zero, 0x8000
/* 712B4 800706B4 00052823 */  negu       $a1, $a1
.L800706B8:
/* 712B8 800706B8 24024000 */  addiu      $v0, $zero, 0x4000
.L800706BC:
/* 712BC 800706BC 00852026 */  xor        $a0, $a0, $a1
/* 712C0 800706C0 00852826 */  xor        $a1, $a0, $a1
/* 712C4 800706C4 00852026 */  xor        $a0, $a0, $a1
.L800706C8:
/* 712C8 800706C8 00854023 */  subu       $t0, $a0, $a1
/* 712CC 800706CC 05020012 */  bltzl      $t0, .L80070718
/* 712D0 800706D0 000442F8 */   dsll      $t0, $a0, 11
/* 712D4 800706D4 000542F8 */  dsll       $t0, $a1, 11
/* 712D8 800706D8 0104001F */  ddivu      $zero, $t0, $a0
/* 712DC 800706DC 3C09800E */  lui        $t1, %hi(gArcTanTable)
/* 712E0 800706E0 2529DCCE */  addiu      $t1, $t1, %lo(gArcTanTable)
/* 712E4 800706E4 24424000 */  addiu      $v0, $v0, 0x4000
/* 712E8 800706E8 14800002 */  bnez       $a0, .L800706F4
/* 712EC 800706EC 00000000 */   nop
/* 712F0 800706F0 0007000D */  break      7
.L800706F4:
/* 712F4 800706F4 00004012 */  mflo       $t0
/* 712F8 800706F8 00004012 */  mflo       $t0
/* 712FC 800706FC 31080FFE */  andi       $t0, $t0, 0xFFE
/* 71300 80070700 01284821 */  addu       $t1, $t1, $t0
/* 71304 80070704 85280000 */  lh         $t0, 0x0($t1)
/* 71308 80070708 00481023 */  subu       $v0, $v0, $t0
/* 7130C 8007070C 03E00008 */  jr         $ra
/* 71310 80070710 3042FFFF */   andi      $v0, $v0, 0xFFFF
/* 71314 80070714 000442F8 */  dsll       $t0, $a0, 11
.L80070718:
/* 71318 80070718 0105001F */  ddivu      $zero, $t0, $a1
/* 7131C 8007071C 3C09800E */  lui        $t1, %hi(gArcTanTable)
/* 71320 80070720 2529DCCE */  addiu      $t1, $t1, %lo(gArcTanTable)
/* 71324 80070724 14A00002 */  bnez       $a1, .L80070730
/* 71328 80070728 00000000 */   nop
/* 7132C 8007072C 0007000D */  break      7
.L80070730:
/* 71330 80070730 00004012 */  mflo       $t0
/* 71334 80070734 00004012 */  mflo       $t0
/* 71338 80070738 31080FFE */  andi       $t0, $t0, 0xFFE
/* 7133C 8007073C 01284821 */  addu       $t1, $t1, $t0
/* 71340 80070740 85280000 */  lh         $t0, 0x0($t1)
/* 71344 80070744 00481021 */  addu       $v0, $v0, $t0
/* 71348 80070748 03E00008 */  jr         $ra
/* 7134C 8007074C 3042FFFF */   andi      $v0, $v0, 0xFFFF

glabel arctan2_f
/* 71350 80070750 3C01437F */  lui        $at, (0x437F0000 >> 16)
/* 71354 80070754 44810000 */  mtc1       $at, $f0
/* 71358 80070758 00000000 */  nop
/* 7135C 8007075C 46006302 */  mul.s      $f12, $f12, $f0
/* 71360 80070760 00000000 */  nop
/* 71364 80070764 46007382 */  mul.s      $f14, $f14, $f0
/* 71368 80070768 46006324 */  cvt.w.s    $f12, $f12
/* 7136C 8007076C 460073A4 */  cvt.w.s    $f14, $f14
/* 71370 80070770 44046000 */  mfc1       $a0, $f12
/* 71374 80070774 44057000 */  mfc1       $a1, $f14
/* 71378 80070778 0801C19B */  j          atan2s
/* 7137C 8007077C 00000000 */   nop

glabel s32_matrix_cell_sqrt
/* 71380 80070780 44840000 */  mtc1       $a0, $f0
/* 71384 80070784 3C014780 */  lui        $at, (0x47800000 >> 16)
/* 71388 80070788 44811000 */  mtc1       $at, $f2
/* 7138C 8007078C 46800020 */  cvt.s.w    $f0, $f0
/* 71390 80070790 46020003 */  div.s      $f0, $f0, $f2
/* 71394 80070794 46000004 */  sqrt.s     $f0, $f0
/* 71398 80070798 46020002 */  mul.s      $f0, $f0, $f2
/* 7139C 8007079C 46000024 */  cvt.w.s    $f0, $f0
/* 713A0 800707A0 44020000 */  mfc1       $v0, $f0
/* 713A4 800707A4 03E00008 */  jr         $ra
/* 713A8 800707A8 00000000 */   nop

glabel bad_int_sqrt
/* 713AC 800707AC 44840000 */  mtc1       $a0, $f0
/* 713B0 800707B0 00000000 */  nop
/* 713B4 800707B4 46000004 */  sqrt.s     $f0, $f0
/* 713B8 800707B8 44020000 */  mfc1       $v0, $f0
/* 713BC 800707BC 03E00008 */  jr         $ra
/* 713C0 800707C0 00000000 */   nop

glabel sins_f
/* 713C4 800707C4 27BDFFF8 */  addiu      $sp, $sp, -0x8
/* 713C8 800707C8 FFBF0000 */  sd         $ra, 0x0($sp)
/* 713CC 800707CC 0C01C20C */  jal        sins_1
/* 713D0 800707D0 00000000 */   nop
/* 713D4 800707D4 44820000 */  mtc1       $v0, $f0
/* 713D8 800707D8 3C013780 */  lui        $at, (0x37800000 >> 16)
/* 713DC 800707DC 44811000 */  mtc1       $at, $f2
/* 713E0 800707E0 46800020 */  cvt.s.w    $f0, $f0
/* 713E4 800707E4 DFBF0000 */  ld         $ra, 0x0($sp)
/* 713E8 800707E8 27BD0008 */  addiu      $sp, $sp, 0x8
/* 713EC 800707EC 46020002 */  mul.s      $f0, $f0, $f2
/* 713F0 800707F0 03E00008 */  jr         $ra
/* 713F4 800707F4 00000000 */   nop

glabel coss_f
/* 713F8 800707F8 27BDFFF8 */  addiu      $sp, $sp, -0x8
/* 713FC 800707FC FFBF0000 */  sd         $ra, 0x0($sp)
/* 71400 80070800 0C01C20B */  jal        coss_1
/* 71404 80070804 00000000 */   nop
/* 71408 80070808 44820000 */  mtc1       $v0, $f0
/* 7140C 8007080C 3C013780 */  lui        $at, (0x37800000 >> 16)
/* 71410 80070810 44811000 */  mtc1       $at, $f2
/* 71414 80070814 46800020 */  cvt.s.w    $f0, $f0
/* 71418 80070818 DFBF0000 */  ld         $ra, 0x0($sp)
/* 7141C 8007081C 27BD0008 */  addiu      $sp, $sp, 0x8
/* 71420 80070820 46020002 */  mul.s      $f0, $f0, $f2
/* 71424 80070824 03E00008 */  jr         $ra
/* 71428 80070828 00000000 */   nop

glabel coss_1
/* 7142C 8007082C 24844000 */  addiu      $a0, $a0, 0x4000
glabel sins_1
/* 71430 80070830 00041440 */  sll        $v0, $a0, 17
/* 71434 80070834 04430003 */  bgezl      $v0, .L80070844
/* 71438 80070838 000450C2 */   srl       $t2, $a0, 3
/* 7143C 8007083C 38847FFF */  xori       $a0, $a0, 0x7FFF
/* 71440 80070840 000450C2 */  srl        $t2, $a0, 3
.L80070844:
/* 71444 80070844 3C02800E */  lui        $v0, %hi(gSineTable)
/* 71448 80070848 314A07FE */  andi       $t2, $t2, 0x7FE
/* 7144C 8007084C 2442D4CC */  addiu      $v0, $v0, %lo(gSineTable)
/* 71450 80070850 004A1021 */  addu       $v0, $v0, $t2
/* 71454 80070854 944A0002 */  lhu        $t2, 0x2($v0)
/* 71458 80070858 94420000 */  lhu        $v0, 0x0($v0)
/* 7145C 8007085C 3089000F */  andi       $t1, $a0, 0xF
/* 71460 80070860 00042400 */  sll        $a0, $a0, 16
/* 71464 80070864 01425023 */  subu       $t2, $t2, $v0
/* 71468 80070868 01490019 */  multu      $t2, $t1
/* 7146C 8007086C 00021040 */  sll        $v0, $v0, 1
/* 71470 80070870 00005012 */  mflo       $t2
/* 71474 80070874 000A50C2 */  srl        $t2, $t2, 3
/* 71478 80070878 04810002 */  bgez       $a0, .L80070884
/* 7147C 8007087C 004A1021 */   addu      $v0, $v0, $t2
/* 71480 80070880 00021023 */  negu       $v0, $v0
.L80070884:
/* 71484 80070884 03E00008 */  jr         $ra
/* 71488 80070888 00000000 */   nop

glabel coss_2
/* 7148C 8007088C 24844000 */  addiu      $a0, $a0, 0x4000
glabel sins_2
/* 71490 80070890 00041440 */  sll        $v0, $a0, 17
/* 71494 80070894 04430003 */  bgezl      $v0, .L800708A4
/* 71498 80070898 000450C2 */   srl       $t2, $a0, 3
/* 7149C 8007089C 38847FFF */  xori       $a0, $a0, 0x7FFF
/* 714A0 800708A0 000450C2 */  srl        $t2, $a0, 3
.L800708A4:
/* 714A4 800708A4 3C02800E */  lui        $v0, %hi(gSineTable)
/* 714A8 800708A8 314A07FE */  andi       $t2, $t2, 0x7FE
/* 714AC 800708AC 2442D4CC */  addiu      $v0, $v0, %lo(gSineTable)
/* 714B0 800708B0 004A1021 */  addu       $v0, $v0, $t2
/* 714B4 800708B4 94420000 */  lhu        $v0, 0x0($v0)
/* 714B8 800708B8 00042400 */  sll        $a0, $a0, 16
/* 714BC 800708BC 04810002 */  bgez       $a0, .L800708C8
/* 714C0 800708C0 00021040 */   sll       $v0, $v0, 1
/* 714C4 800708C4 00021023 */  negu       $v0, $v0
.L800708C8:
/* 714C8 800708C8 03E00008 */  jr         $ra
/* 714CC 800708CC 00000000 */   nop

/* Handwritten function */
glabel calc_dyn_lighting_for_level_segment
/* 714D0 800708D0 8CA90000 */  lw         $t1, 0x0($a1)
/* 714D4 800708D4 8CAA0004 */  lw         $t2, 0x4($a1)
/* 714D8 800708D8 8CAB0008 */  lw         $t3, 0x8($a1)
/* 714DC 800708DC 94880020 */  lhu        $t0, 0x20($a0)
/* 714E0 800708E0 8C86000C */  lw         $a2, 0xC($a0)
/* 714E4 800708E4 8C85002C */  lw         $a1, 0x2C($a0)
/* 714E8 800708E8 8C840000 */  lw         $a0, 0x0($a0)
/* 714EC 800708EC 00421026 */  xor        $v0, $v0, $v0
.L800708F0:
/* 714F0 800708F0 90CC0006 */  lbu        $t4, 0x6($a2)
/* 714F4 800708F4 258CFF01 */  addiu      $t4, $t4, -0xFF
/* 714F8 800708F8 51800043 */  beql       $t4, $zero, .L80070A08
/* 714FC 800708FC 94CC0002 */   lhu       $t4, 0x2($a2)
/* 71500 80070900 5040000C */  beql       $v0, $zero, .L80070934
/* 71504 80070904 00000000 */   nop
/* 71508 80070908 340C000A */  ori        $t4, $zero, 0xA
/* 7150C 8007090C 004C0019 */  multu      $v0, $t4
/* 71510 80070910 340D000A */  ori        $t5, $zero, 0xA
/* 71514 80070914 00006012 */  mflo       $t4
/* 71518 80070918 008C2021 */  addu       $a0, $a0, $t4
/* 7151C 8007091C 00000000 */  nop
/* 71520 80070920 004D0019 */  multu      $v0, $t5
/* 71524 80070924 00421026 */  xor        $v0, $v0, $v0
/* 71528 80070928 00006812 */  mflo       $t5
/* 7152C 8007092C 00AD2821 */  addu       $a1, $a1, $t5
/* 71530 80070930 00000000 */  nop
.L80070934:
/* 71534 80070934 94CD0002 */  lhu        $t5, 0x2($a2)
/* 71538 80070938 94CC000E */  lhu        $t4, 0xE($a2)
/* 7153C 8007093C 24C6000C */  addiu      $a2, $a2, 0xC
/* 71540 80070940 018D6023 */  subu       $t4, $t4, $t5
.L80070944:
/* 71544 80070944 84AD0000 */  lh         $t5, 0x0($a1)
/* 71548 80070948 84AE0002 */  lh         $t6, 0x2($a1)
/* 7154C 8007094C 84AF0004 */  lh         $t7, 0x4($a1)
/* 71550 80070950 01A90018 */  mult       $t5, $t1
/* 71554 80070954 90B80007 */  lbu        $t8, 0x7($a1)
/* 71558 80070958 90A70006 */  lbu        $a3, 0x6($a1)
/* 7155C 8007095C 90B90008 */  lbu        $t9, 0x8($a1)
/* 71560 80070960 0018C400 */  sll        $t8, $t8, 16
/* 71564 80070964 90A30009 */  lbu        $v1, 0x9($a1)
/* 71568 80070968 00F8C025 */  or         $t8, $a3, $t8
/* 7156C 8007096C 00006812 */  mflo       $t5
/* 71570 80070970 00000000 */  nop
/* 71574 80070974 00000000 */  nop
/* 71578 80070978 01CA0018 */  mult       $t6, $t2
/* 7157C 8007097C 00007012 */  mflo       $t6
/* 71580 80070980 01AE6820 */  add        $t5, $t5, $t6 /* handwritten instruction */
/* 71584 80070984 00000000 */  nop
/* 71588 80070988 01EB0018 */  mult       $t7, $t3
/* 7158C 8007098C 00007812 */  mflo       $t7
/* 71590 80070990 01AF6820 */  add        $t5, $t5, $t7 /* handwritten instruction */
/* 71594 80070994 19A00007 */  blez       $t5, .L800709B4
/* 71598 80070998 00000000 */   nop
/* 7159C 8007099C 000D6D82 */  srl        $t5, $t5, 22
/* 715A0 800709A0 006D1821 */  addu       $v1, $v1, $t5
/* 715A4 800709A4 2C6D0081 */  sltiu      $t5, $v1, 0x81
/* 715A8 800709A8 15A00002 */  bnez       $t5, .L800709B4
/* 715AC 800709AC 00000000 */   nop
/* 715B0 800709B0 34030080 */  ori        $v1, $zero, 0x80
.L800709B4:
/* 715B4 800709B4 00780019 */  multu      $v1, $t8
/* 715B8 800709B8 24A5000A */  addiu      $a1, $a1, 0xA
/* 715BC 800709BC 258CFFFF */  addiu      $t4, $t4, -0x1
/* 715C0 800709C0 2484000A */  addiu      $a0, $a0, 0xA
/* 715C4 800709C4 0000C012 */  mflo       $t8
/* 715C8 800709C8 0018C1C2 */  srl        $t8, $t8, 7
/* 715CC 800709CC A098FFFC */  sb         $t8, -0x4($a0)
/* 715D0 800709D0 00790019 */  multu      $v1, $t9
/* 715D4 800709D4 0018C402 */  srl        $t8, $t8, 16
/* 715D8 800709D8 A098FFFD */  sb         $t8, -0x3($a0)
/* 715DC 800709DC 0000C812 */  mflo       $t9
/* 715E0 800709E0 0019C9C2 */  srl        $t9, $t9, 7
/* 715E4 800709E4 A099FFFE */  sb         $t9, -0x2($a0)
/* 715E8 800709E8 5580FFD6 */  bnel       $t4, $zero, .L80070944
/* 715EC 800709EC 00000000 */   nop
/* 715F0 800709F0 2508FFFF */  addiu      $t0, $t0, -0x1
/* 715F4 800709F4 5500FFBE */  bnel       $t0, $zero, .L800708F0
/* 715F8 800709F8 00000000 */   nop
/* 715FC 800709FC 03E00008 */  jr         $ra
/* 71600 80070A00 00000000 */   nop

glabel func_80070A04
/* 71604 80070A04 94CC0002 */  lhu        $t4, 0x2($a2)
.L80070A08:
/* 71608 80070A08 94CD000E */  lhu        $t5, 0xE($a2)
/* 7160C 80070A0C 24C6000C */  addiu      $a2, $a2, 0xC
/* 71610 80070A10 2508FFFF */  addiu      $t0, $t0, -0x1
/* 71614 80070A14 01AC6023 */  subu       $t4, $t5, $t4
/* 71618 80070A18 004C1021 */  addu       $v0, $v0, $t4
/* 7161C 80070A1C 5500FFB4 */  bnel       $t0, $zero, .L800708F0
/* 71620 80070A20 00000000 */   nop
/* 71624 80070A24 03E00008 */  jr         $ra
/* 71628 80070A28 00000000 */   nop

glabel area_triangle_2d
/* 7162C 80070A2C 44862000 */  mtc1       $a2, $f4
/* 71630 80070A30 46006006 */  mov.s      $f0, $f12
/* 71634 80070A34 44873000 */  mtc1       $a3, $f6
/* 71638 80070A38 46002301 */  sub.s      $f12, $f4, $f0
/* 7163C 80070A3C 46007086 */  mov.s      $f2, $f14
/* 71640 80070A40 C7A80010 */  lwc1       $f8, 0x10($sp)
/* 71644 80070A44 46023381 */  sub.s      $f14, $f6, $f2
/* 71648 80070A48 460C6302 */  mul.s      $f12, $f12, $f12
/* 7164C 80070A4C C7AA0014 */  lwc1       $f10, 0x14($sp)
/* 71650 80070A50 46044401 */  sub.s      $f16, $f8, $f4
/* 71654 80070A54 460E7382 */  mul.s      $f14, $f14, $f14
/* 71658 80070A58 3C013F00 */  lui        $at, (0x3F000000 >> 16)
/* 7165C 80070A5C 46065481 */  sub.s      $f18, $f10, $f6
/* 71660 80070A60 46108402 */  mul.s      $f16, $f16, $f16
/* 71664 80070A64 46080001 */  sub.s      $f0, $f0, $f8
/* 71668 80070A68 46129482 */  mul.s      $f18, $f18, $f18
/* 7166C 80070A6C 460A1081 */  sub.s      $f2, $f2, $f10
/* 71670 80070A70 46000002 */  mul.s      $f0, $f0, $f0
/* 71674 80070A74 44815000 */  mtc1       $at, $f10
/* 71678 80070A78 460E6300 */  add.s      $f12, $f12, $f14
/* 7167C 80070A7C 46021082 */  mul.s      $f2, $f2, $f2
/* 71680 80070A80 46128400 */  add.s      $f16, $f16, $f18
/* 71684 80070A84 46006304 */  sqrt.s     $f12, $f12
/* 71688 80070A88 46008404 */  sqrt.s     $f16, $f16
/* 7168C 80070A8C 46020000 */  add.s      $f0, $f0, $f2
/* 71690 80070A90 44801000 */  mtc1       $zero, $f2
/* 71694 80070A94 46106480 */  add.s      $f18, $f12, $f16
/* 71698 80070A98 46000004 */  sqrt.s     $f0, $f0
/* 7169C 80070A9C 46009480 */  add.s      $f18, $f18, $f0
/* 716A0 80070AA0 46125482 */  mul.s      $f18, $f10, $f18
/* 716A4 80070AA4 460C9101 */  sub.s      $f4, $f18, $f12
/* 716A8 80070AA8 46009201 */  sub.s      $f8, $f18, $f0
/* 716AC 80070AAC 46122002 */  mul.s      $f0, $f4, $f18
/* 716B0 80070AB0 46109181 */  sub.s      $f6, $f18, $f16
/* 716B4 80070AB4 46083182 */  mul.s      $f6, $f6, $f8
/* 716B8 80070AB8 00000000 */  nop
/* 716BC 80070ABC 46060002 */  mul.s      $f0, $f0, $f6
/* 716C0 80070AC0 4602003C */  c.lt.s     $f0, $f2
/* 716C4 80070AC4 45020002 */  bc1fl      .L80070AD0
/* 716C8 80070AC8 00000000 */   nop
/* 716CC 80070ACC 46001006 */  mov.s      $f0, $f2
.L80070AD0:
/* 716D0 80070AD0 03E00008 */  jr         $ra
/* 716D4 80070AD4 46000004 */   sqrt.s    $f0, $f0

/* Handwritten function */
glabel set_breakpoint
/* 716D8 80070AD8 34840001 */  ori        $a0, $a0, 0x1
/* 716DC 80070ADC 40849000 */  mtc0       $a0, $18 /* handwritten instruction */
/* 716E0 80070AE0 2408000F */  addiu      $t0, $zero, 0xF
/* 716E4 80070AE4 40889800 */  mtc0       $t0, $19 /* handwritten instruction */
/* 716E8 80070AE8 00000000 */  nop
/* 716EC 80070AEC 00000000 */  nop
/* 716F0 80070AF0 00000000 */  nop
/* 716F4 80070AF4 00000000 */  nop
/* 716F8 80070AF8 00000000 */  nop
/* 716FC 80070AFC 03E00008 */  jr         $ra
/* 71700 80070B00 00000000 */   nop

/* Handwritten function */
glabel dmacopy_doubleword
/* 71704 80070B04 DC880000 */  ld         $t0, 0x0($a0)
/* 71708 80070B08 DC890008 */  ld         $t1, 0x8($a0)
/* 7170C 80070B0C 20A50010 */  addi       $a1, $a1, 0x10 /* handwritten instruction */
/* 71710 80070B10 20840010 */  addi       $a0, $a0, 0x10 /* handwritten instruction */
/* 71714 80070B14 FCA8FFF0 */  sd         $t0, -0x10($a1)
/* 71718 80070B18 14A6FFFA */  bne        $a1, $a2, dmacopy_doubleword
/* 7171C 80070B1C FCA9FFF8 */   sd        $t1, -0x8($a1)
/* 71720 80070B20 03E00008 */  jr         $ra
/* 71724 80070B24 00000000 */   nop
/* 71728 80070B28 00000000 */  nop
/* 7172C 80070B2C 00000000 */  nop
