.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

glabel bcmp
/* CECE0 800CE0E0 28C10010 */  slti       $at, $a2, 0x10
/* CECE4 800CE0E4 14200037 */  bnez       $at, .L800CE1C4_CEDC4
/* CECE8 800CE0E8 00851026 */   xor       $v0, $a0, $a1
/* CECEC 800CE0EC 30420003 */  andi       $v0, $v0, 0x3
/* CECF0 800CE0F0 14400019 */  bnez       $v0, .L800CE158_CED58
/* CECF4 800CE0F4 0004C023 */   negu      $t8, $a0
/* CECF8 800CE0F8 33180003 */  andi       $t8, $t8, 0x3
/* CECFC 800CE0FC 13000007 */  beqz       $t8, .L800CE11C_CED1C
/* CED00 800CE100 00D83023 */   subu      $a2, $a2, $t8
/* CED04 800CE104 00601025 */  or         $v0, $v1, $zero
/* CED08 800CE108 88820000 */  lwl        $v0, 0x0($a0)
/* CED0C 800CE10C 88A30000 */  lwl        $v1, 0x0($a1)
/* CED10 800CE110 00982021 */  addu       $a0, $a0, $t8
/* CED14 800CE114 00B82821 */  addu       $a1, $a1, $t8
/* CED18 800CE118 14430036 */  bne        $v0, $v1, .L800CE1F4_CEDF4
.L800CE11C_CED1C:
/* CED1C 800CE11C 2401FFFC */   addiu     $at, $zero, -0x4
/* CED20 800CE120 00C13824 */  and        $a3, $a2, $at
/* CED24 800CE124 10E00027 */  beqz       $a3, .L800CE1C4_CEDC4
/* CED28 800CE128 00C73023 */   subu      $a2, $a2, $a3
/* CED2C 800CE12C 00E43821 */  addu       $a3, $a3, $a0
/* CED30 800CE130 8C820000 */  lw         $v0, 0x0($a0)
.L800CE134_CED34:
/* CED34 800CE134 8CA30000 */  lw         $v1, 0x0($a1)
/* CED38 800CE138 24840004 */  addiu      $a0, $a0, 0x4
/* CED3C 800CE13C 24A50004 */  addiu      $a1, $a1, 0x4
/* CED40 800CE140 1443002C */  bne        $v0, $v1, .L800CE1F4_CEDF4
/* CED44 800CE144 00000000 */   nop
/* CED48 800CE148 5487FFFA */  bnel       $a0, $a3, .L800CE134_CED34
/* CED4C 800CE14C 8C820000 */   lw        $v0, 0x0($a0)
/* CED50 800CE150 1000001C */  b          .L800CE1C4_CEDC4
/* CED54 800CE154 00000000 */   nop
.L800CE158_CED58:
/* CED58 800CE158 00053823 */  negu       $a3, $a1
/* CED5C 800CE15C 30E70003 */  andi       $a3, $a3, 0x3
/* CED60 800CE160 10E0000A */  beqz       $a3, .L800CE18C_CED8C
/* CED64 800CE164 00C73023 */   subu      $a2, $a2, $a3
/* CED68 800CE168 00E43821 */  addu       $a3, $a3, $a0
/* CED6C 800CE16C 90820000 */  lbu        $v0, 0x0($a0)
.L800CE170_CED70:
/* CED70 800CE170 90A30000 */  lbu        $v1, 0x0($a1)
/* CED74 800CE174 24840001 */  addiu      $a0, $a0, 0x1
/* CED78 800CE178 24A50001 */  addiu      $a1, $a1, 0x1
/* CED7C 800CE17C 1443001D */  bne        $v0, $v1, .L800CE1F4_CEDF4
/* CED80 800CE180 00000000 */   nop
/* CED84 800CE184 5487FFFA */  bnel       $a0, $a3, .L800CE170_CED70
/* CED88 800CE188 90820000 */   lbu       $v0, 0x0($a0)
.L800CE18C_CED8C:
/* CED8C 800CE18C 2401FFFC */  addiu      $at, $zero, -0x4
/* CED90 800CE190 00C13824 */  and        $a3, $a2, $at
/* CED94 800CE194 10E0000B */  beqz       $a3, .L800CE1C4_CEDC4
/* CED98 800CE198 00C73023 */   subu      $a2, $a2, $a3
/* CED9C 800CE19C 00E43821 */  addu       $a3, $a3, $a0
/* CEDA0 800CE1A0 88820000 */  lwl        $v0, 0x0($a0)
.L800CE1A4_CEDA4:
/* CEDA4 800CE1A4 8CA30000 */  lw         $v1, 0x0($a1)
/* CEDA8 800CE1A8 98820003 */  lwr        $v0, 0x3($a0)
/* CEDAC 800CE1AC 24840004 */  addiu      $a0, $a0, 0x4
/* CEDB0 800CE1B0 24A50004 */  addiu      $a1, $a1, 0x4
/* CEDB4 800CE1B4 1443000F */  bne        $v0, $v1, .L800CE1F4_CEDF4
/* CEDB8 800CE1B8 00000000 */   nop
/* CEDBC 800CE1BC 5487FFF9 */  bnel       $a0, $a3, .L800CE1A4_CEDA4
/* CEDC0 800CE1C0 88820000 */   lwl       $v0, 0x0($a0)
.L800CE1C4_CEDC4:
/* CEDC4 800CE1C4 18C00009 */  blez       $a2, .L800CE1EC_CEDEC
/* CEDC8 800CE1C8 00C43821 */   addu      $a3, $a2, $a0
/* CEDCC 800CE1CC 90820000 */  lbu        $v0, 0x0($a0)
.L800CE1D0_CEDD0:
/* CEDD0 800CE1D0 90A30000 */  lbu        $v1, 0x0($a1)
/* CEDD4 800CE1D4 24840001 */  addiu      $a0, $a0, 0x1
/* CEDD8 800CE1D8 24A50001 */  addiu      $a1, $a1, 0x1
/* CEDDC 800CE1DC 14430005 */  bne        $v0, $v1, .L800CE1F4_CEDF4
/* CEDE0 800CE1E0 00000000 */   nop
/* CEDE4 800CE1E4 5487FFFA */  bnel       $a0, $a3, .L800CE1D0_CEDD0
/* CEDE8 800CE1E8 90820000 */   lbu       $v0, 0x0($a0)
.L800CE1EC_CEDEC:
/* CEDEC 800CE1EC 03E00008 */  jr         $ra
/* CEDF0 800CE1F0 00001025 */   or        $v0, $zero, $zero
.L800CE1F4_CEDF4:
/* CEDF4 800CE1F4 03E00008 */  jr         $ra
/* CEDF8 800CE1F8 24020001 */   addiu     $v0, $zero, 0x1
/* CEDFC 800CE1FC 00000000 */  nop
