.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

glabel get_stack_pointer
/* B8EC0 800B82C0 03E00008 */  jr         $ra
/* B8EC4 800B82C4 03A01025 */   or        $v0, $sp, $zero
/* B8EC8 800B82C8 00000000 */  nop
/* B8ECC 800B82CC 00000000 */  nop
