.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .rodata

glabel gzip_border
.byte 16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15

glabel gzip_cplens
.half 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 23, 27, 31, 35, 43, 51, 59, 67, 83, 99, 115, 131, 163, 195, 227, 258, 0, 0

glabel gzip_cplext
.byte 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0, 99, 99

glabel gzip_cpdist
.half 1, 2, 3, 4, 5, 7, 9, 13, 17, 25, 33, 49, 65, 97, 129, 193, 257, 385, 513, 769, 1025, 1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577

glabel gzip_cpdext
.byte 0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13

glabel gzip_mask_bits
.half 0x0000, 0x0001, 0x0003, 0x0007, 0x000f, 0x001f, 0x003f, 0x007f, 0x00ff, 0x01ff, 0x03ff, 0x07ff, 0x0fff, 0x1fff, 0x3fff, 0x7fff, 0xffff


.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel gzip_inflate_block
/* C7AB0 800C6EB0 3C0B8013 */  lui        $t3, %hi(gzip_num_bits)
/* C7AB4 800C6EB4 8D6BB124 */  lw         $t3, %lo(gzip_num_bits)($t3)
/* C7AB8 800C6EB8 3C018013 */  lui        $at, %hi(gHuftTablePos)
/* C7ABC 800C6EBC AC20B128 */  sw         $zero, %lo(gHuftTablePos)($at)
/* C7AC0 800C6EC0 24080001 */  addiu      $t0, $zero, 0x1
/* C7AC4 800C6EC4 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* C7AC8 800C6EC8 3C0C800E */  lui        $t4, %hi(gzip_inflate_input)
/* C7ACC 800C6ECC 3C0A8013 */  lui        $t2, %hi(gzip_bit_buffer)
/* C7AD0 800C6ED0 0168082B */  sltu       $at, $t3, $t0
/* C7AD4 800C6ED4 AFBF001C */  sw         $ra, 0x1C($sp)
/* C7AD8 800C6ED8 AFB00018 */  sw         $s0, 0x18($sp)
/* C7ADC 800C6EDC 8D8C3D88 */  lw         $t4, %lo(gzip_inflate_input)($t4)
/* C7AE0 800C6EE0 10200008 */  beqz       $at, .L800C6F04_C7B04
/* C7AE4 800C6EE4 8D4AB120 */   lw        $t2, %lo(gzip_bit_buffer)($t2)
.L800C6EE8_C7AE8:
/* C7AE8 800C6EE8 91820000 */  lbu        $v0, 0x0($t4)
/* C7AEC 800C6EEC 258C0001 */  addiu      $t4, $t4, 0x1
/* C7AF0 800C6EF0 01621004 */  sllv       $v0, $v0, $t3
/* C7AF4 800C6EF4 256B0008 */  addiu      $t3, $t3, 0x8
/* C7AF8 800C6EF8 0168082A */  slt        $at, $t3, $t0
/* C7AFC 800C6EFC 1420FFFA */  bnez       $at, .L800C6EE8_C7AE8
/* C7B00 800C6F00 01425025 */   or        $t2, $t2, $v0
.L800C6F04_C7B04:
/* C7B04 800C6F04 31500001 */  andi       $s0, $t2, 0x1
/* C7B08 800C6F08 010A5006 */  srlv       $t2, $t2, $t0
/* C7B0C 800C6F0C 01685822 */  sub        $t3, $t3, $t0 /* handwritten instruction */
/* C7B10 800C6F10 24080002 */  addiu      $t0, $zero, 0x2
/* C7B14 800C6F14 0168082B */  sltu       $at, $t3, $t0
/* C7B18 800C6F18 10200008 */  beqz       $at, .L800C6F3C_C7B3C
/* C7B1C 800C6F1C 00000000 */   nop
.L800C6F20_C7B20:
/* C7B20 800C6F20 91820000 */  lbu        $v0, 0x0($t4)
/* C7B24 800C6F24 258C0001 */  addiu      $t4, $t4, 0x1
/* C7B28 800C6F28 01621004 */  sllv       $v0, $v0, $t3
/* C7B2C 800C6F2C 256B0008 */  addiu      $t3, $t3, 0x8
/* C7B30 800C6F30 0168082A */  slt        $at, $t3, $t0
/* C7B34 800C6F34 1420FFFA */  bnez       $at, .L800C6F20_C7B20
/* C7B38 800C6F38 01425025 */   or        $t2, $t2, $v0
.L800C6F3C_C7B3C:
/* C7B3C 800C6F3C 3C01800E */  lui        $at, %hi(gzip_inflate_input)
/* C7B40 800C6F40 31490003 */  andi       $t1, $t2, 0x3
/* C7B44 800C6F44 AC2C3D88 */  sw         $t4, %lo(gzip_inflate_input)($at)
/* C7B48 800C6F48 010A5006 */  srlv       $t2, $t2, $t0
/* C7B4C 800C6F4C 3C018013 */  lui        $at, %hi(gzip_bit_buffer)
/* C7B50 800C6F50 AC2AB120 */  sw         $t2, %lo(gzip_bit_buffer)($at)
/* C7B54 800C6F54 01685822 */  sub        $t3, $t3, $t0 /* handwritten instruction */
/* C7B58 800C6F58 3C018013 */  lui        $at, %hi(gzip_num_bits)
/* C7B5C 800C6F5C AC2BB124 */  sw         $t3, %lo(gzip_num_bits)($at)
/* C7B60 800C6F60 24010002 */  addiu      $at, $zero, 0x2
/* C7B64 800C6F64 1121000B */  beq        $t1, $at, .L800C6F94_C7B94
/* C7B68 800C6F68 24010001 */   addiu     $at, $zero, 0x1
/* C7B6C 800C6F6C 11210005 */  beq        $t1, $at, .L800C6F84_C7B84
/* C7B70 800C6F70 00000000 */   nop
/* C7B74 800C6F74 0C031D49 */  jal        gzip_inflate_stored
/* C7B78 800C6F78 00000000 */   nop
/* C7B7C 800C6F7C 08031BE7 */  j          .L800C6F9C_C7B9C
/* C7B80 800C6F80 00000000 */   nop
.L800C6F84_C7B84:
/* C7B84 800C6F84 0C031CF3 */  jal        gzip_inflate_fixed
/* C7B88 800C6F88 00000000 */   nop
/* C7B8C 800C6F8C 08031BE7 */  j          .L800C6F9C_C7B9C
/* C7B90 800C6F90 00000000 */   nop
.L800C6F94_C7B94:
/* C7B94 800C6F94 0C031BED */  jal        gzip_inflate_dynamic
/* C7B98 800C6F98 00000000 */   nop
.L800C6F9C_C7B9C:
/* C7B9C 800C6F9C 8FBF001C */  lw         $ra, 0x1C($sp)
/* C7BA0 800C6FA0 24020001 */  addiu      $v0, $zero, 0x1
/* C7BA4 800C6FA4 00501022 */  sub        $v0, $v0, $s0 /* handwritten instruction */
/* C7BA8 800C6FA8 8FB00018 */  lw         $s0, 0x18($sp)
/* C7BAC 800C6FAC 03E00008 */  jr         $ra
/* C7BB0 800C6FB0 27BD0020 */   addiu     $sp, $sp, 0x20

/* Handwritten function */
glabel gzip_inflate_dynamic
/* C7BB4 800C6FB4 27BDFAC0 */  addiu      $sp, $sp, -0x540
/* C7BB8 800C6FB8 AFB30028 */  sw         $s3, 0x28($sp)
/* C7BBC 800C6FBC 3C138013 */  lui        $s3, %hi(gzip_num_bits)
/* C7BC0 800C6FC0 8E73B124 */  lw         $s3, %lo(gzip_num_bits)($s3)
/* C7BC4 800C6FC4 AFB4002C */  sw         $s4, 0x2C($sp)
/* C7BC8 800C6FC8 AFB20024 */  sw         $s2, 0x24($sp)
/* C7BCC 800C6FCC 24080005 */  addiu      $t0, $zero, 0x5
/* C7BD0 800C6FD0 3C14800E */  lui        $s4, %hi(gzip_inflate_input)
/* C7BD4 800C6FD4 3C128013 */  lui        $s2, %hi(gzip_bit_buffer)
/* C7BD8 800C6FD8 0268082B */  sltu       $at, $s3, $t0
/* C7BDC 800C6FDC AFBF0030 */  sw         $ra, 0x30($sp)
/* C7BE0 800C6FE0 AFB10020 */  sw         $s1, 0x20($sp)
/* C7BE4 800C6FE4 AFB0001C */  sw         $s0, 0x1C($sp)
/* C7BE8 800C6FE8 8E943D88 */  lw         $s4, %lo(gzip_inflate_input)($s4)
/* C7BEC 800C6FEC 10200008 */  beqz       $at, .L800C7010_C7C10
/* C7BF0 800C6FF0 8E52B120 */   lw        $s2, %lo(gzip_bit_buffer)($s2)
.L800C6FF4_C7BF4:
/* C7BF4 800C6FF4 92820000 */  lbu        $v0, 0x0($s4)
/* C7BF8 800C6FF8 26940001 */  addiu      $s4, $s4, 0x1
/* C7BFC 800C6FFC 02621004 */  sllv       $v0, $v0, $s3
/* C7C00 800C7000 26730008 */  addiu      $s3, $s3, 0x8
/* C7C04 800C7004 0268082A */  slt        $at, $s3, $t0
/* C7C08 800C7008 1420FFFA */  bnez       $at, .L800C6FF4_C7BF4
/* C7C0C 800C700C 02429025 */   or        $s2, $s2, $v0
.L800C7010_C7C10:
/* C7C10 800C7010 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7C14 800C7014 3251001F */  andi       $s1, $s2, 0x1F
/* C7C18 800C7018 0268082B */  sltu       $at, $s3, $t0
/* C7C1C 800C701C 26310101 */  addiu      $s1, $s1, 0x101
/* C7C20 800C7020 10200008 */  beqz       $at, .L800C7044_C7C44
/* C7C24 800C7024 01129006 */   srlv      $s2, $s2, $t0
.L800C7028_C7C28:
/* C7C28 800C7028 92820000 */  lbu        $v0, 0x0($s4)
/* C7C2C 800C702C 26940001 */  addiu      $s4, $s4, 0x1
/* C7C30 800C7030 02621004 */  sllv       $v0, $v0, $s3
/* C7C34 800C7034 26730008 */  addiu      $s3, $s3, 0x8
/* C7C38 800C7038 0268082A */  slt        $at, $s3, $t0
/* C7C3C 800C703C 1420FFFA */  bnez       $at, .L800C7028_C7C28
/* C7C40 800C7040 02429025 */   or        $s2, $s2, $v0
.L800C7044_C7C44:
/* C7C44 800C7044 3250001F */  andi       $s0, $s2, 0x1F
/* C7C48 800C7048 01129006 */  srlv       $s2, $s2, $t0
/* C7C4C 800C704C 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7C50 800C7050 24080004 */  addiu      $t0, $zero, 0x4
/* C7C54 800C7054 0268082B */  sltu       $at, $s3, $t0
/* C7C58 800C7058 10200008 */  beqz       $at, .L800C707C_C7C7C
/* C7C5C 800C705C 26100001 */   addiu     $s0, $s0, 0x1
.L800C7060_C7C60:
/* C7C60 800C7060 92820000 */  lbu        $v0, 0x0($s4)
/* C7C64 800C7064 26940001 */  addiu      $s4, $s4, 0x1
/* C7C68 800C7068 02621004 */  sllv       $v0, $v0, $s3
/* C7C6C 800C706C 26730008 */  addiu      $s3, $s3, 0x8
/* C7C70 800C7070 0268082A */  slt        $at, $s3, $t0
/* C7C74 800C7074 1420FFFA */  bnez       $at, .L800C7060_C7C60
/* C7C78 800C7078 02429025 */   or        $s2, $s2, $v0
.L800C707C_C7C7C:
/* C7C7C 800C707C 324A000F */  andi       $t2, $s2, 0xF
/* C7C80 800C7080 254A0004 */  addiu      $t2, $t2, 0x4
/* C7C84 800C7084 3C19800F */  lui        $t9, %hi(gzip_border)
/* C7C88 800C7088 01129006 */  srlv       $s2, $s2, $t0
/* C7C8C 800C708C 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7C90 800C7090 000A4825 */  or         $t1, $zero, $t2
/* C7C94 800C7094 273999D0 */  addiu      $t9, $t9, %lo(gzip_border)
/* C7C98 800C7098 11400019 */  beqz       $t2, .L800C7100_C7D00
/* C7C9C 800C709C 23AF0044 */   addi      $t7, $sp, 0x44 /* handwritten instruction */
.L800C70A0_C7CA0:
/* C7CA0 800C70A0 24080003 */  addiu      $t0, $zero, 0x3
/* C7CA4 800C70A4 0268082B */  sltu       $at, $s3, $t0
/* C7CA8 800C70A8 50200009 */  beql       $at, $zero, .L800C70D0_C7CD0
/* C7CAC 800C70AC 93230000 */   lbu       $v1, 0x0($t9)
.L800C70B0_C7CB0:
/* C7CB0 800C70B0 92820000 */  lbu        $v0, 0x0($s4)
/* C7CB4 800C70B4 26940001 */  addiu      $s4, $s4, 0x1
/* C7CB8 800C70B8 02621004 */  sllv       $v0, $v0, $s3
/* C7CBC 800C70BC 26730008 */  addiu      $s3, $s3, 0x8
/* C7CC0 800C70C0 0268082A */  slt        $at, $s3, $t0
/* C7CC4 800C70C4 1420FFFA */  bnez       $at, .L800C70B0_C7CB0
/* C7CC8 800C70C8 02429025 */   or        $s2, $s2, $v0
/* C7CCC 800C70CC 93230000 */  lbu        $v1, 0x0($t9)
.L800C70D0_C7CD0:
/* C7CD0 800C70D0 32420007 */  andi       $v0, $s2, 0x7
/* C7CD4 800C70D4 254AFFFF */  addiu      $t2, $t2, -0x1
/* C7CD8 800C70D8 00031880 */  sll        $v1, $v1, 2
/* C7CDC 800C70DC 006F1821 */  addu       $v1, $v1, $t7
/* C7CE0 800C70E0 AC620000 */  sw         $v0, 0x0($v1)
/* C7CE4 800C70E4 01129006 */  srlv       $s2, $s2, $t0
/* C7CE8 800C70E8 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7CEC 800C70EC 1540FFEC */  bnez       $t2, .L800C70A0_C7CA0
/* C7CF0 800C70F0 27390001 */   addiu     $t9, $t9, 0x1
/* C7CF4 800C70F4 2D210013 */  sltiu      $at, $t1, 0x13
/* C7CF8 800C70F8 5020000A */  beql       $at, $zero, .L800C7124_C7D24
/* C7CFC 800C70FC 240D0007 */   addiu     $t5, $zero, 0x7
.L800C7100_C7D00:
/* C7D00 800C7100 93230000 */  lbu        $v1, 0x0($t9)
/* C7D04 800C7104 25290001 */  addiu      $t1, $t1, 0x1
/* C7D08 800C7108 29210013 */  slti       $at, $t1, 0x13
/* C7D0C 800C710C 00031880 */  sll        $v1, $v1, 2
/* C7D10 800C7110 006F1821 */  addu       $v1, $v1, $t7
/* C7D14 800C7114 AC600000 */  sw         $zero, 0x0($v1)
/* C7D18 800C7118 1420FFF9 */  bnez       $at, .L800C7100_C7D00
/* C7D1C 800C711C 27390001 */   addiu     $t9, $t9, 0x1
/* C7D20 800C7120 240D0007 */  addiu      $t5, $zero, 0x7
.L800C7124_C7D24:
/* C7D24 800C7124 23A80034 */  addi       $t0, $sp, 0x34 /* handwritten instruction */
/* C7D28 800C7128 23A90038 */  addi       $t1, $sp, 0x38 /* handwritten instruction */
/* C7D2C 800C712C AFAD0038 */  sw         $t5, 0x38($sp)
/* C7D30 800C7130 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C7D34 800C7134 24050013 */  addiu      $a1, $zero, 0x13
/* C7D38 800C7138 24060013 */  addiu      $a2, $zero, 0x13
/* C7D3C 800C713C 24070000 */  addiu      $a3, $zero, 0x0
/* C7D40 800C7140 AFA00010 */  sw         $zero, 0x10($sp)
/* C7D44 800C7144 AFA80014 */  sw         $t0, 0x14($sp)
/* C7D48 800C7148 0C031A19 */  jal        gzip_huft_build
/* C7D4C 800C714C AFA90018 */   sw        $t1, 0x18($sp)
/* C7D50 800C7150 23A90038 */  addi       $t1, $sp, 0x38 /* handwritten instruction */
/* C7D54 800C7154 8D2D0000 */  lw         $t5, 0x0($t1)
/* C7D58 800C7158 3C02800F */  lui        $v0, %hi(gzip_mask_bits)
/* C7D5C 800C715C 24429A9C */  addiu      $v0, $v0, %lo(gzip_mask_bits)
/* C7D60 800C7160 000D1840 */  sll        $v1, $t5, 1
/* C7D64 800C7164 23A80034 */  addi       $t0, $sp, 0x34 /* handwritten instruction */
/* C7D68 800C7168 00431020 */  add        $v0, $v0, $v1 /* handwritten instruction */
/* C7D6C 800C716C 8D0E0000 */  lw         $t6, 0x0($t0)
/* C7D70 800C7170 0230C820 */  add        $t9, $s1, $s0 /* handwritten instruction */
/* C7D74 800C7174 84580000 */  lh         $t8, 0x0($v0)
/* C7D78 800C7178 23AF0044 */  addi       $t7, $sp, 0x44 /* handwritten instruction */
/* C7D7C 800C717C 240A0000 */  addiu      $t2, $zero, 0x0
.L800C7180_C7D80:
/* C7D80 800C7180 1320005F */  beqz       $t9, .L800C7300_C7F00
/* C7D84 800C7184 026D082B */   sltu      $at, $s3, $t5
/* C7D88 800C7188 50200009 */  beql       $at, $zero, .L800C71B0_C7DB0
/* C7D8C 800C718C 02581024 */   and       $v0, $s2, $t8
.L800C7190_C7D90:
/* C7D90 800C7190 92820000 */  lbu        $v0, 0x0($s4)
/* C7D94 800C7194 26940001 */  addiu      $s4, $s4, 0x1
/* C7D98 800C7198 02621004 */  sllv       $v0, $v0, $s3
/* C7D9C 800C719C 26730008 */  addiu      $s3, $s3, 0x8
/* C7DA0 800C71A0 026D082A */  slt        $at, $s3, $t5
/* C7DA4 800C71A4 1420FFFA */  bnez       $at, .L800C7190_C7D90
/* C7DA8 800C71A8 02429025 */   or        $s2, $s2, $v0
/* C7DAC 800C71AC 02581024 */  and        $v0, $s2, $t8
.L800C71B0_C7DB0:
/* C7DB0 800C71B0 000210C0 */  sll        $v0, $v0, 3
/* C7DB4 800C71B4 01C24821 */  addu       $t1, $t6, $v0
/* C7DB8 800C71B8 95280004 */  lhu        $t0, 0x4($t1)
/* C7DBC 800C71BC 91220001 */  lbu        $v0, 0x1($t1)
/* C7DC0 800C71C0 29010010 */  slti       $at, $t0, 0x10
/* C7DC4 800C71C4 00529006 */  srlv       $s2, $s2, $v0
/* C7DC8 800C71C8 1420001C */  bnez       $at, .L800C723C_C7E3C
/* C7DCC 800C71CC 02629822 */   sub       $s3, $s3, $v0 /* handwritten instruction */
/* C7DD0 800C71D0 24010010 */  addiu      $at, $zero, 0x10
/* C7DD4 800C71D4 1101001E */  beq        $t0, $at, .L800C7250_C7E50
/* C7DD8 800C71D8 24010011 */   addiu     $at, $zero, 0x11
/* C7DDC 800C71DC 51010033 */  beql       $t0, $at, .L800C72AC_C7EAC
/* C7DE0 800C71E0 24080003 */   addiu     $t0, $zero, 0x3
/* C7DE4 800C71E4 24080007 */  addiu      $t0, $zero, 0x7
/* C7DE8 800C71E8 0268082B */  sltu       $at, $s3, $t0
/* C7DEC 800C71EC 50200009 */  beql       $at, $zero, .L800C7214_C7E14
/* C7DF0 800C71F0 3249007F */   andi      $t1, $s2, 0x7F
.L800C71F4_C7DF4:
/* C7DF4 800C71F4 92820000 */  lbu        $v0, 0x0($s4)
/* C7DF8 800C71F8 26940001 */  addiu      $s4, $s4, 0x1
/* C7DFC 800C71FC 02621004 */  sllv       $v0, $v0, $s3
/* C7E00 800C7200 26730008 */  addiu      $s3, $s3, 0x8
/* C7E04 800C7204 0268082A */  slt        $at, $s3, $t0
/* C7E08 800C7208 1420FFFA */  bnez       $at, .L800C71F4_C7DF4
/* C7E0C 800C720C 02429025 */   or        $s2, $s2, $v0
/* C7E10 800C7210 3249007F */  andi       $t1, $s2, 0x7F
.L800C7214_C7E14:
/* C7E14 800C7214 2529000B */  addiu      $t1, $t1, 0xB
/* C7E18 800C7218 01129006 */  srlv       $s2, $s2, $t0
/* C7E1C 800C721C 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7E20 800C7220 0329C823 */  subu       $t9, $t9, $t1
.L800C7224_C7E24:
/* C7E24 800C7224 2529FFFF */  addiu      $t1, $t1, -0x1
/* C7E28 800C7228 ADE00000 */  sw         $zero, 0x0($t7)
/* C7E2C 800C722C 1520FFFD */  bnez       $t1, .L800C7224_C7E24
/* C7E30 800C7230 25EF0004 */   addiu     $t7, $t7, 0x4
/* C7E34 800C7234 08031C60 */  j          .L800C7180_C7D80
/* C7E38 800C7238 240A0000 */   addiu     $t2, $zero, 0x0
.L800C723C_C7E3C:
/* C7E3C 800C723C ADE80000 */  sw         $t0, 0x0($t7)
/* C7E40 800C7240 25EF0004 */  addiu      $t7, $t7, 0x4
/* C7E44 800C7244 2739FFFF */  addiu      $t9, $t9, -0x1
/* C7E48 800C7248 08031C60 */  j          .L800C7180_C7D80
/* C7E4C 800C724C 00085025 */   or        $t2, $zero, $t0
.L800C7250_C7E50:
/* C7E50 800C7250 24080002 */  addiu      $t0, $zero, 0x2
/* C7E54 800C7254 0268082B */  sltu       $at, $s3, $t0
/* C7E58 800C7258 50200009 */  beql       $at, $zero, .L800C7280_C7E80
/* C7E5C 800C725C 32490003 */   andi      $t1, $s2, 0x3
.L800C7260_C7E60:
/* C7E60 800C7260 92820000 */  lbu        $v0, 0x0($s4)
/* C7E64 800C7264 26940001 */  addiu      $s4, $s4, 0x1
/* C7E68 800C7268 02621004 */  sllv       $v0, $v0, $s3
/* C7E6C 800C726C 26730008 */  addiu      $s3, $s3, 0x8
/* C7E70 800C7270 0268082A */  slt        $at, $s3, $t0
/* C7E74 800C7274 1420FFFA */  bnez       $at, .L800C7260_C7E60
/* C7E78 800C7278 02429025 */   or        $s2, $s2, $v0
/* C7E7C 800C727C 32490003 */  andi       $t1, $s2, 0x3
.L800C7280_C7E80:
/* C7E80 800C7280 21290003 */  addi       $t1, $t1, 0x3 /* handwritten instruction */
/* C7E84 800C7284 01129006 */  srlv       $s2, $s2, $t0
/* C7E88 800C7288 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7E8C 800C728C 0329C823 */  subu       $t9, $t9, $t1
.L800C7290_C7E90:
/* C7E90 800C7290 2529FFFF */  addiu      $t1, $t1, -0x1
/* C7E94 800C7294 ADEA0000 */  sw         $t2, 0x0($t7)
/* C7E98 800C7298 1520FFFD */  bnez       $t1, .L800C7290_C7E90
/* C7E9C 800C729C 25EF0004 */   addiu     $t7, $t7, 0x4
/* C7EA0 800C72A0 08031C60 */  j          .L800C7180_C7D80
/* C7EA4 800C72A4 00000000 */   nop
/* C7EA8 800C72A8 24080003 */  addiu      $t0, $zero, 0x3
.L800C72AC_C7EAC:
/* C7EAC 800C72AC 0268082B */  sltu       $at, $s3, $t0
/* C7EB0 800C72B0 50200009 */  beql       $at, $zero, .L800C72D8_C7ED8
/* C7EB4 800C72B4 32490007 */   andi      $t1, $s2, 0x7
.L800C72B8_C7EB8:
/* C7EB8 800C72B8 92820000 */  lbu        $v0, 0x0($s4)
/* C7EBC 800C72BC 26940001 */  addiu      $s4, $s4, 0x1
/* C7EC0 800C72C0 02621004 */  sllv       $v0, $v0, $s3
/* C7EC4 800C72C4 26730008 */  addiu      $s3, $s3, 0x8
/* C7EC8 800C72C8 0268082A */  slt        $at, $s3, $t0
/* C7ECC 800C72CC 1420FFFA */  bnez       $at, .L800C72B8_C7EB8
/* C7ED0 800C72D0 02429025 */   or        $s2, $s2, $v0
/* C7ED4 800C72D4 32490007 */  andi       $t1, $s2, 0x7
.L800C72D8_C7ED8:
/* C7ED8 800C72D8 21290003 */  addi       $t1, $t1, 0x3 /* handwritten instruction */
/* C7EDC 800C72DC 01129006 */  srlv       $s2, $s2, $t0
/* C7EE0 800C72E0 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7EE4 800C72E4 0329C823 */  subu       $t9, $t9, $t1
.L800C72E8_C7EE8:
/* C7EE8 800C72E8 2529FFFF */  addiu      $t1, $t1, -0x1
/* C7EEC 800C72EC ADE00000 */  sw         $zero, 0x0($t7)
/* C7EF0 800C72F0 1520FFFD */  bnez       $t1, .L800C72E8_C7EE8
/* C7EF4 800C72F4 25EF0004 */   addiu     $t7, $t7, 0x4
/* C7EF8 800C72F8 08031C60 */  j          .L800C7180_C7D80
/* C7EFC 800C72FC 240A0000 */   addiu     $t2, $zero, 0x0
.L800C7300_C7F00:
/* C7F00 800C7300 3C01800E */  lui        $at, %hi(gzip_inflate_input)
/* C7F04 800C7304 AC343D88 */  sw         $s4, %lo(gzip_inflate_input)($at)
/* C7F08 800C7308 3C018013 */  lui        $at, %hi(gzip_bit_buffer)
/* C7F0C 800C730C 24080009 */  addiu      $t0, $zero, 0x9
/* C7F10 800C7310 AC32B120 */  sw         $s2, %lo(gzip_bit_buffer)($at)
/* C7F14 800C7314 AFA80038 */  sw         $t0, 0x38($sp)
/* C7F18 800C7318 3C02800F */  lui        $v0, %hi(gzip_cplext)
/* C7F1C 800C731C 3C018013 */  lui        $at, %hi(gzip_num_bits)
/* C7F20 800C7320 3C07800F */  lui        $a3, %hi(gzip_cplens)
/* C7F24 800C7324 24429A22 */  addiu      $v0, $v0, %lo(gzip_cplext)
/* C7F28 800C7328 23A30034 */  addi       $v1, $sp, 0x34 /* handwritten instruction */
/* C7F2C 800C732C 23A80038 */  addi       $t0, $sp, 0x38 /* handwritten instruction */
/* C7F30 800C7330 AC33B124 */  sw         $s3, %lo(gzip_num_bits)($at)
/* C7F34 800C7334 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C7F38 800C7338 00112825 */  or         $a1, $zero, $s1
/* C7F3C 800C733C 24060101 */  addiu      $a2, $zero, 0x101
/* C7F40 800C7340 24E799E4 */  addiu      $a3, $a3, %lo(gzip_cplens)
/* C7F44 800C7344 AFA20010 */  sw         $v0, 0x10($sp)
/* C7F48 800C7348 AFA30014 */  sw         $v1, 0x14($sp)
/* C7F4C 800C734C 0C031A19 */  jal        gzip_huft_build
/* C7F50 800C7350 AFA80018 */   sw        $t0, 0x18($sp)
/* C7F54 800C7354 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C7F58 800C7358 00111080 */  sll        $v0, $s1, 2
/* C7F5C 800C735C 24080006 */  addiu      $t0, $zero, 0x6
/* C7F60 800C7360 00822021 */  addu       $a0, $a0, $v0
/* C7F64 800C7364 AFA80040 */  sw         $t0, 0x40($sp)
/* C7F68 800C7368 3C02800F */  lui        $v0, %hi(gzip_cpdext)
/* C7F6C 800C736C 3C07800F */  lui        $a3, %hi(gzip_cpdist)
/* C7F70 800C7370 24429A7E */  addiu      $v0, $v0, %lo(gzip_cpdext)
/* C7F74 800C7374 23A3003C */  addi       $v1, $sp, 0x3C /* handwritten instruction */
/* C7F78 800C7378 23A80040 */  addi       $t0, $sp, 0x40 /* handwritten instruction */
/* C7F7C 800C737C 00102825 */  or         $a1, $zero, $s0
/* C7F80 800C7380 24060000 */  addiu      $a2, $zero, 0x0
/* C7F84 800C7384 24E79A42 */  addiu      $a3, $a3, %lo(gzip_cpdist)
/* C7F88 800C7388 AFA20010 */  sw         $v0, 0x10($sp)
/* C7F8C 800C738C AFA30014 */  sw         $v1, 0x14($sp)
/* C7F90 800C7390 0C031A19 */  jal        gzip_huft_build
/* C7F94 800C7394 AFA80018 */   sw        $t0, 0x18($sp)
/* C7F98 800C7398 8FA40034 */  lw         $a0, 0x34($sp)
/* C7F9C 800C739C 8FA5003C */  lw         $a1, 0x3C($sp)
/* C7FA0 800C73A0 8FA60038 */  lw         $a2, 0x38($sp)
/* C7FA4 800C73A4 0C031D8C */  jal        gzip_inflate_codes
/* C7FA8 800C73A8 8FA70040 */   lw        $a3, 0x40($sp)
/* C7FAC 800C73AC 8FBF0030 */  lw         $ra, 0x30($sp)
/* C7FB0 800C73B0 8FB4002C */  lw         $s4, 0x2C($sp)
/* C7FB4 800C73B4 8FB30028 */  lw         $s3, 0x28($sp)
/* C7FB8 800C73B8 8FB20024 */  lw         $s2, 0x24($sp)
/* C7FBC 800C73BC 8FB10020 */  lw         $s1, 0x20($sp)
/* C7FC0 800C73C0 8FB0001C */  lw         $s0, 0x1C($sp)
/* C7FC4 800C73C4 03E00008 */  jr         $ra
/* C7FC8 800C73C8 27BD0540 */   addiu     $sp, $sp, 0x540

/* Handwritten function */
glabel gzip_inflate_fixed
/* C7FCC 800C73CC 27BDFAD0 */  addiu      $sp, $sp, -0x530
/* C7FD0 800C73D0 AFBF001C */  sw         $ra, 0x1C($sp)
/* C7FD4 800C73D4 23AB0044 */  addi       $t3, $sp, 0x44 /* handwritten instruction */
/* C7FD8 800C73D8 24080024 */  addiu      $t0, $zero, 0x24
/* C7FDC 800C73DC 24090008 */  addiu      $t1, $zero, 0x8
.L800C73E0_C7FE0:
/* C7FE0 800C73E0 2508FFFF */  addiu      $t0, $t0, -0x1
/* C7FE4 800C73E4 AD690000 */  sw         $t1, 0x0($t3)
/* C7FE8 800C73E8 AD690004 */  sw         $t1, 0x4($t3)
/* C7FEC 800C73EC AD690008 */  sw         $t1, 0x8($t3)
/* C7FF0 800C73F0 AD69000C */  sw         $t1, 0xC($t3)
/* C7FF4 800C73F4 1500FFFA */  bnez       $t0, .L800C73E0_C7FE0
/* C7FF8 800C73F8 256B0010 */   addiu     $t3, $t3, 0x10
/* C7FFC 800C73FC 2408001C */  addiu      $t0, $zero, 0x1C
/* C8000 800C7400 24090009 */  addiu      $t1, $zero, 0x9
.L800C7404_C8004:
/* C8004 800C7404 2508FFFF */  addiu      $t0, $t0, -0x1
/* C8008 800C7408 AD690000 */  sw         $t1, 0x0($t3)
/* C800C 800C740C AD690004 */  sw         $t1, 0x4($t3)
/* C8010 800C7410 AD690008 */  sw         $t1, 0x8($t3)
/* C8014 800C7414 AD69000C */  sw         $t1, 0xC($t3)
/* C8018 800C7418 1500FFFA */  bnez       $t0, .L800C7404_C8004
/* C801C 800C741C 256B0010 */   addiu     $t3, $t3, 0x10
/* C8020 800C7420 24080006 */  addiu      $t0, $zero, 0x6
/* C8024 800C7424 24090007 */  addiu      $t1, $zero, 0x7
.L800C7428_C8028:
/* C8028 800C7428 2508FFFF */  addiu      $t0, $t0, -0x1
/* C802C 800C742C AD690000 */  sw         $t1, 0x0($t3)
/* C8030 800C7430 AD690004 */  sw         $t1, 0x4($t3)
/* C8034 800C7434 AD690008 */  sw         $t1, 0x8($t3)
/* C8038 800C7438 AD69000C */  sw         $t1, 0xC($t3)
/* C803C 800C743C 1500FFFA */  bnez       $t0, .L800C7428_C8028
/* C8040 800C7440 256B0010 */   addiu     $t3, $t3, 0x10
/* C8044 800C7444 24090008 */  addiu      $t1, $zero, 0x8
/* C8048 800C7448 AD690000 */  sw         $t1, 0x0($t3)
/* C804C 800C744C AD690004 */  sw         $t1, 0x4($t3)
/* C8050 800C7450 AD690008 */  sw         $t1, 0x8($t3)
/* C8054 800C7454 AD69000C */  sw         $t1, 0xC($t3)
/* C8058 800C7458 AD690010 */  sw         $t1, 0x10($t3)
/* C805C 800C745C AD690014 */  sw         $t1, 0x14($t3)
/* C8060 800C7460 AD690018 */  sw         $t1, 0x18($t3)
/* C8064 800C7464 AD69001C */  sw         $t1, 0x1C($t3)
/* C8068 800C7468 24080007 */  addiu      $t0, $zero, 0x7
/* C806C 800C746C AFA80038 */  sw         $t0, 0x38($sp)
/* C8070 800C7470 3C02800F */  lui        $v0, %hi(gzip_cplext)
/* C8074 800C7474 3C07800F */  lui        $a3, %hi(gzip_cplens)
/* C8078 800C7478 24429A22 */  addiu      $v0, $v0, %lo(gzip_cplext)
/* C807C 800C747C 23A30020 */  addi       $v1, $sp, 0x20 /* handwritten instruction */
/* C8080 800C7480 23A80024 */  addi       $t0, $sp, 0x24 /* handwritten instruction */
/* C8084 800C7484 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C8088 800C7488 24050120 */  addiu      $a1, $zero, 0x120
/* C808C 800C748C 24060101 */  addiu      $a2, $zero, 0x101
/* C8090 800C7490 24E799E4 */  addiu      $a3, $a3, %lo(gzip_cplens)
/* C8094 800C7494 AFA20010 */  sw         $v0, 0x10($sp)
/* C8098 800C7498 AFA30014 */  sw         $v1, 0x14($sp)
/* C809C 800C749C 0C031A19 */  jal        gzip_huft_build
/* C80A0 800C74A0 AFA80018 */   sw        $t0, 0x18($sp)
/* C80A4 800C74A4 23AB0044 */  addi       $t3, $sp, 0x44 /* handwritten instruction */
/* C80A8 800C74A8 2408000A */  addiu      $t0, $zero, 0xA
/* C80AC 800C74AC 24090005 */  addiu      $t1, $zero, 0x5
.L800C74B0_C80B0:
/* C80B0 800C74B0 2508FFFF */  addiu      $t0, $t0, -0x1
/* C80B4 800C74B4 AD690000 */  sw         $t1, 0x0($t3)
/* C80B8 800C74B8 AD690004 */  sw         $t1, 0x4($t3)
/* C80BC 800C74BC AD690008 */  sw         $t1, 0x8($t3)
/* C80C0 800C74C0 1500FFFB */  bnez       $t0, .L800C74B0_C80B0
/* C80C4 800C74C4 256B000C */   addiu     $t3, $t3, 0xC
/* C80C8 800C74C8 3C02800F */  lui        $v0, %hi(gzip_cpdext)
/* C80CC 800C74CC 3C07800F */  lui        $a3, %hi(gzip_cpdist)
/* C80D0 800C74D0 24429A7E */  addiu      $v0, $v0, %lo(gzip_cpdext)
/* C80D4 800C74D4 23A30028 */  addi       $v1, $sp, 0x28 /* handwritten instruction */
/* C80D8 800C74D8 23A8002C */  addi       $t0, $sp, 0x2C /* handwritten instruction */
/* C80DC 800C74DC AFA90040 */  sw         $t1, 0x40($sp)
/* C80E0 800C74E0 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C80E4 800C74E4 2405001E */  addiu      $a1, $zero, 0x1E
/* C80E8 800C74E8 24060000 */  addiu      $a2, $zero, 0x0
/* C80EC 800C74EC 24E79A42 */  addiu      $a3, $a3, %lo(gzip_cpdist)
/* C80F0 800C74F0 AFA20010 */  sw         $v0, 0x10($sp)
/* C80F4 800C74F4 AFA30014 */  sw         $v1, 0x14($sp)
/* C80F8 800C74F8 0C031A19 */  jal        gzip_huft_build
/* C80FC 800C74FC AFA80018 */   sw        $t0, 0x18($sp)
/* C8100 800C7500 8FA40020 */  lw         $a0, 0x20($sp)
/* C8104 800C7504 8FA50028 */  lw         $a1, 0x28($sp)
/* C8108 800C7508 8FA60024 */  lw         $a2, 0x24($sp)
/* C810C 800C750C 0C031D8C */  jal        gzip_inflate_codes
/* C8110 800C7510 8FA7002C */   lw        $a3, 0x2C($sp)
/* C8114 800C7514 8FBF001C */  lw         $ra, 0x1C($sp)
/* C8118 800C7518 27BD0530 */  addiu      $sp, $sp, 0x530
/* C811C 800C751C 03E00008 */  jr         $ra
/* C8120 800C7520 00000000 */   nop

/* Handwritten function */
glabel gzip_inflate_stored
/* C8124 800C7524 3C0D8013 */  lui        $t5, %hi(gzip_num_bits)
/* C8128 800C7528 8DADB124 */  lw         $t5, %lo(gzip_num_bits)($t5)
/* C812C 800C752C 3C0C8013 */  lui        $t4, %hi(gzip_bit_buffer)
/* C8130 800C7530 8D8CB120 */  lw         $t4, %lo(gzip_bit_buffer)($t4)
/* C8134 800C7534 31A80007 */  andi       $t0, $t5, 0x7
/* C8138 800C7538 01A86822 */  sub        $t5, $t5, $t0 /* handwritten instruction */
/* C813C 800C753C 010C6006 */  srlv       $t4, $t4, $t0
/* C8140 800C7540 24080010 */  addiu      $t0, $zero, 0x10
/* C8144 800C7544 3C0F800E */  lui        $t7, %hi(gzip_inflate_input)
/* C8148 800C7548 3C0E800E */  lui        $t6, %hi(gzip_inflate_output)
/* C814C 800C754C 01A8082B */  sltu       $at, $t5, $t0
/* C8150 800C7550 8DEF3D88 */  lw         $t7, %lo(gzip_inflate_input)($t7)
/* C8154 800C7554 10200008 */  beqz       $at, .L800C7578_C8178
/* C8158 800C7558 8DCE3D8C */   lw        $t6, %lo(gzip_inflate_output)($t6)
.L800C755C_C815C:
/* C815C 800C755C 91E20000 */  lbu        $v0, 0x0($t7)
/* C8160 800C7560 25EF0001 */  addiu      $t7, $t7, 0x1
/* C8164 800C7564 01A21004 */  sllv       $v0, $v0, $t5
/* C8168 800C7568 25AD0008 */  addiu      $t5, $t5, 0x8
/* C816C 800C756C 01A8082A */  slt        $at, $t5, $t0
/* C8170 800C7570 1420FFFA */  bnez       $at, .L800C755C_C815C
/* C8174 800C7574 01826025 */   or        $t4, $t4, $v0
.L800C7578_C8178:
/* C8178 800C7578 01A86822 */  sub        $t5, $t5, $t0 /* handwritten instruction */
/* C817C 800C757C 3189FFFF */  andi       $t1, $t4, 0xFFFF
/* C8180 800C7580 01A8082B */  sltu       $at, $t5, $t0
/* C8184 800C7584 10200008 */  beqz       $at, .L800C75A8_C81A8
/* C8188 800C7588 010C6006 */   srlv      $t4, $t4, $t0
.L800C758C_C818C:
/* C818C 800C758C 91E20000 */  lbu        $v0, 0x0($t7)
/* C8190 800C7590 25EF0001 */  addiu      $t7, $t7, 0x1
/* C8194 800C7594 01A21004 */  sllv       $v0, $v0, $t5
/* C8198 800C7598 25AD0008 */  addiu      $t5, $t5, 0x8
/* C819C 800C759C 01A8082A */  slt        $at, $t5, $t0
/* C81A0 800C75A0 1420FFFA */  bnez       $at, .L800C758C_C818C
/* C81A4 800C75A4 01826025 */   or        $t4, $t4, $v0
.L800C75A8_C81A8:
/* C81A8 800C75A8 31220003 */  andi       $v0, $t1, 0x3
/* C81AC 800C75AC 010C6006 */  srlv       $t4, $t4, $t0
/* C81B0 800C75B0 1040000A */  beqz       $v0, .L800C75DC_C81DC
/* C81B4 800C75B4 01A86822 */   sub       $t5, $t5, $t0 /* handwritten instruction */
/* C81B8 800C75B8 01224822 */  sub        $t1, $t1, $v0 /* handwritten instruction */
.L800C75BC_C81BC:
/* C81BC 800C75BC 91EA0000 */  lbu        $t2, 0x0($t7)
/* C81C0 800C75C0 2042FFFF */  addi       $v0, $v0, -0x1 /* handwritten instruction */
/* C81C4 800C75C4 21EF0001 */  addi       $t7, $t7, 0x1 /* handwritten instruction */
/* C81C8 800C75C8 21CE0001 */  addi       $t6, $t6, 0x1 /* handwritten instruction */
/* C81CC 800C75CC 1440FFFB */  bnez       $v0, .L800C75BC_C81BC
/* C81D0 800C75D0 A1CAFFFF */   sb        $t2, -0x1($t6)
/* C81D4 800C75D4 1120000D */  beqz       $t1, .L800C760C_C820C
/* C81D8 800C75D8 00000000 */   nop
.L800C75DC_C81DC:
/* C81DC 800C75DC 91E20000 */  lbu        $v0, 0x0($t7)
/* C81E0 800C75E0 2529FFFC */  addiu      $t1, $t1, -0x4
/* C81E4 800C75E4 25EF0004 */  addiu      $t7, $t7, 0x4
/* C81E8 800C75E8 A1C20000 */  sb         $v0, 0x0($t6)
/* C81EC 800C75EC 91E3FFFD */  lbu        $v1, -0x3($t7)
/* C81F0 800C75F0 25CE0004 */  addiu      $t6, $t6, 0x4
/* C81F4 800C75F4 A1C3FFFD */  sb         $v1, -0x3($t6)
/* C81F8 800C75F8 91EAFFFE */  lbu        $t2, -0x2($t7)
/* C81FC 800C75FC A1CAFFFE */  sb         $t2, -0x2($t6)
/* C8200 800C7600 91EBFFFF */  lbu        $t3, -0x1($t7)
/* C8204 800C7604 1520FFF5 */  bnez       $t1, .L800C75DC_C81DC
/* C8208 800C7608 A1CBFFFF */   sb        $t3, -0x1($t6)
.L800C760C_C820C:
/* C820C 800C760C 3C01800E */  lui        $at, %hi(gzip_inflate_input)
/* C8210 800C7610 AC2F3D88 */  sw         $t7, %lo(gzip_inflate_input)($at)
/* C8214 800C7614 3C01800E */  lui        $at, %hi(gzip_inflate_output)
/* C8218 800C7618 AC2E3D8C */  sw         $t6, %lo(gzip_inflate_output)($at)
/* C821C 800C761C 3C018013 */  lui        $at, %hi(gzip_bit_buffer)
/* C8220 800C7620 AC2CB120 */  sw         $t4, %lo(gzip_bit_buffer)($at)
/* C8224 800C7624 3C018013 */  lui        $at, %hi(gzip_num_bits)
/* C8228 800C7628 03E00008 */  jr         $ra
/* C822C 800C762C AC2DB124 */   sw        $t5, %lo(gzip_num_bits)($at)

/* Handwritten function */
glabel gzip_inflate_codes
/* C8230 800C7630 27BDFFF0 */  addiu      $sp, $sp, -0x10
/* C8234 800C7634 3C0B800F */  lui        $t3, %hi(gzip_mask_bits)
/* C8238 800C7638 AFB20008 */  sw         $s2, 0x8($sp)
/* C823C 800C763C AFB10004 */  sw         $s1, 0x4($sp)
/* C8240 800C7640 AFB00000 */  sw         $s0, 0x0($sp)
/* C8244 800C7644 256B9A9C */  addiu      $t3, $t3, %lo(gzip_mask_bits)
/* C8248 800C7648 00061040 */  sll        $v0, $a2, 1
/* C824C 800C764C 00074040 */  sll        $t0, $a3, 1
/* C8250 800C7650 3C12800E */  lui        $s2, %hi(gzip_inflate_input)
/* C8254 800C7654 3C11800E */  lui        $s1, %hi(gzip_inflate_output)
/* C8258 800C7658 3C198013 */  lui        $t9, %hi(gzip_bit_buffer)
/* C825C 800C765C 3C108013 */  lui        $s0, %hi(gzip_num_bits)
/* C8260 800C7660 01621821 */  addu       $v1, $t3, $v0
/* C8264 800C7664 01684821 */  addu       $t1, $t3, $t0
/* C8268 800C7668 8E523D88 */  lw         $s2, %lo(gzip_inflate_input)($s2)
/* C826C 800C766C 8E313D8C */  lw         $s1, %lo(gzip_inflate_output)($s1)
/* C8270 800C7670 8F39B120 */  lw         $t9, %lo(gzip_bit_buffer)($t9)
/* C8274 800C7674 8E10B124 */  lw         $s0, %lo(gzip_num_bits)($s0)
/* C8278 800C7678 946D0000 */  lhu        $t5, 0x0($v1)
/* C827C 800C767C 952C0000 */  lhu        $t4, 0x0($t1)
.L800C7680_C8280:
/* C8280 800C7680 0206082B */  sltu       $at, $s0, $a2
.L800C7684_C8284:
/* C8284 800C7684 50200009 */  beql       $at, $zero, .L800C76AC_C82AC
/* C8288 800C7688 032D1024 */   and       $v0, $t9, $t5
.L800C768C_C828C:
/* C828C 800C768C 92420000 */  lbu        $v0, 0x0($s2)
/* C8290 800C7690 26520001 */  addiu      $s2, $s2, 0x1
/* C8294 800C7694 02021004 */  sllv       $v0, $v0, $s0
/* C8298 800C7698 26100008 */  addiu      $s0, $s0, 0x8
/* C829C 800C769C 0206082A */  slt        $at, $s0, $a2
/* C82A0 800C76A0 1420FFFA */  bnez       $at, .L800C768C_C828C
/* C82A4 800C76A4 0322C825 */   or        $t9, $t9, $v0
/* C82A8 800C76A8 032D1024 */  and        $v0, $t9, $t5
.L800C76AC_C82AC:
/* C82AC 800C76AC 000210C0 */  sll        $v0, $v0, 3
/* C82B0 800C76B0 00827821 */  addu       $t7, $a0, $v0
/* C82B4 800C76B4 91F80000 */  lbu        $t8, 0x0($t7)
/* C82B8 800C76B8 2B010011 */  slti       $at, $t8, 0x11
/* C82BC 800C76BC 5420001A */  bnel       $at, $zero, .L800C7728_C8328
/* C82C0 800C76C0 91E20001 */   lbu       $v0, 0x1($t7)
/* C82C4 800C76C4 81E30001 */  lb         $v1, 0x1($t7)
.L800C76C8_C82C8:
/* C82C8 800C76C8 2318FFF0 */  addi       $t8, $t8, -0x10 /* handwritten instruction */
/* C82CC 800C76CC 02038022 */  sub        $s0, $s0, $v1 /* handwritten instruction */
/* C82D0 800C76D0 0218082B */  sltu       $at, $s0, $t8
/* C82D4 800C76D4 10200008 */  beqz       $at, .L800C76F8_C82F8
/* C82D8 800C76D8 0079C806 */   srlv      $t9, $t9, $v1
.L800C76DC_C82DC:
/* C82DC 800C76DC 92420000 */  lbu        $v0, 0x0($s2)
/* C82E0 800C76E0 26520001 */  addiu      $s2, $s2, 0x1
/* C82E4 800C76E4 02021004 */  sllv       $v0, $v0, $s0
/* C82E8 800C76E8 26100008 */  addiu      $s0, $s0, 0x8
/* C82EC 800C76EC 0218082A */  slt        $at, $s0, $t8
/* C82F0 800C76F0 1420FFFA */  bnez       $at, .L800C76DC_C82DC
/* C82F4 800C76F4 0322C825 */   or        $t9, $t9, $v0
.L800C76F8_C82F8:
/* C82F8 800C76F8 00181040 */  sll        $v0, $t8, 1
/* C82FC 800C76FC 004B1021 */  addu       $v0, $v0, $t3
/* C8300 800C7700 94490000 */  lhu        $t1, 0x0($v0)
/* C8304 800C7704 8DE80004 */  lw         $t0, 0x4($t7)
/* C8308 800C7708 01394824 */  and        $t1, $t1, $t9
/* C830C 800C770C 000948C0 */  sll        $t1, $t1, 3
/* C8310 800C7710 01097820 */  add        $t7, $t0, $t1 /* handwritten instruction */
/* C8314 800C7714 91F80000 */  lbu        $t8, 0x0($t7)
/* C8318 800C7718 2F010011 */  sltiu      $at, $t8, 0x11
/* C831C 800C771C 5020FFEA */  beql       $at, $zero, .L800C76C8_C82C8
/* C8320 800C7720 81E30001 */   lb        $v1, 0x1($t7)
/* C8324 800C7724 91E20001 */  lbu        $v0, 0x1($t7)
.L800C7728_C8328:
/* C8328 800C7728 24010010 */  addiu      $at, $zero, 0x10
/* C832C 800C772C 0059C806 */  srlv       $t9, $t9, $v0
/* C8330 800C7730 17010005 */  bne        $t8, $at, .L800C7748_C8348
/* C8334 800C7734 02028022 */   sub       $s0, $s0, $v0 /* handwritten instruction */
/* C8338 800C7738 95E20004 */  lhu        $v0, 0x4($t7)
/* C833C 800C773C 26310001 */  addiu      $s1, $s1, 0x1
/* C8340 800C7740 08031DA0 */  j          .L800C7680_C8280
/* C8344 800C7744 A222FFFF */   sb        $v0, -0x1($s1)
.L800C7748_C8348:
/* C8348 800C7748 2401000F */  addiu      $at, $zero, 0xF
/* C834C 800C774C 13010068 */  beq        $t8, $at, .L800C78F0_C84F0
/* C8350 800C7750 0218082B */   sltu      $at, $s0, $t8
/* C8354 800C7754 50200009 */  beql       $at, $zero, .L800C777C_C837C
/* C8358 800C7758 00181040 */   sll       $v0, $t8, 1
.L800C775C_C835C:
/* C835C 800C775C 92420000 */  lbu        $v0, 0x0($s2)
/* C8360 800C7760 26520001 */  addiu      $s2, $s2, 0x1
/* C8364 800C7764 02021004 */  sllv       $v0, $v0, $s0
/* C8368 800C7768 26100008 */  addiu      $s0, $s0, 0x8
/* C836C 800C776C 0218082A */  slt        $at, $s0, $t8
/* C8370 800C7770 1420FFFA */  bnez       $at, .L800C775C_C835C
/* C8374 800C7774 0322C825 */   or        $t9, $t9, $v0
/* C8378 800C7778 00181040 */  sll        $v0, $t8, 1
.L800C777C_C837C:
/* C837C 800C777C 004B1021 */  addu       $v0, $v0, $t3
/* C8380 800C7780 94490000 */  lhu        $t1, 0x0($v0)
/* C8384 800C7784 95E80004 */  lhu        $t0, 0x4($t7)
/* C8388 800C7788 02188022 */  sub        $s0, $s0, $t8 /* handwritten instruction */
/* C838C 800C778C 0207082B */  sltu       $at, $s0, $a3
/* C8390 800C7790 01394824 */  and        $t1, $t1, $t9
/* C8394 800C7794 0319C806 */  srlv       $t9, $t9, $t8
/* C8398 800C7798 10200008 */  beqz       $at, .L800C77BC_C83BC
/* C839C 800C779C 01097021 */   addu      $t6, $t0, $t1
.L800C77A0_C83A0:
/* C83A0 800C77A0 92420000 */  lbu        $v0, 0x0($s2)
/* C83A4 800C77A4 26520001 */  addiu      $s2, $s2, 0x1
/* C83A8 800C77A8 02021004 */  sllv       $v0, $v0, $s0
/* C83AC 800C77AC 26100008 */  addiu      $s0, $s0, 0x8
/* C83B0 800C77B0 0207082A */  slt        $at, $s0, $a3
/* C83B4 800C77B4 1420FFFA */  bnez       $at, .L800C77A0_C83A0
/* C83B8 800C77B8 0322C825 */   or        $t9, $t9, $v0
.L800C77BC_C83BC:
/* C83BC 800C77BC 01991024 */  and        $v0, $t4, $t9
/* C83C0 800C77C0 000210C0 */  sll        $v0, $v0, 3
/* C83C4 800C77C4 00A27821 */  addu       $t7, $a1, $v0
/* C83C8 800C77C8 91F80000 */  lbu        $t8, 0x0($t7)
/* C83CC 800C77CC 2B010011 */  slti       $at, $t8, 0x11
/* C83D0 800C77D0 5420001A */  bnel       $at, $zero, .L800C783C_C843C
/* C83D4 800C77D4 91E20001 */   lbu       $v0, 0x1($t7)
/* C83D8 800C77D8 91E80001 */  lbu        $t0, 0x1($t7)
.L800C77DC_C83DC:
/* C83DC 800C77DC 2318FFF0 */  addi       $t8, $t8, -0x10 /* handwritten instruction */
/* C83E0 800C77E0 02088022 */  sub        $s0, $s0, $t0 /* handwritten instruction */
/* C83E4 800C77E4 0218082B */  sltu       $at, $s0, $t8
/* C83E8 800C77E8 10200008 */  beqz       $at, .L800C780C_C840C
/* C83EC 800C77EC 0119C806 */   srlv      $t9, $t9, $t0
.L800C77F0_C83F0:
/* C83F0 800C77F0 92420000 */  lbu        $v0, 0x0($s2)
/* C83F4 800C77F4 26520001 */  addiu      $s2, $s2, 0x1
/* C83F8 800C77F8 02021004 */  sllv       $v0, $v0, $s0
/* C83FC 800C77FC 26100008 */  addiu      $s0, $s0, 0x8
/* C8400 800C7800 0218082A */  slt        $at, $s0, $t8
/* C8404 800C7804 1420FFFA */  bnez       $at, .L800C77F0_C83F0
/* C8408 800C7808 0322C825 */   or        $t9, $t9, $v0
.L800C780C_C840C:
/* C840C 800C780C 00181040 */  sll        $v0, $t8, 1
/* C8410 800C7810 004B1021 */  addu       $v0, $v0, $t3
/* C8414 800C7814 94490000 */  lhu        $t1, 0x0($v0)
/* C8418 800C7818 8DE80004 */  lw         $t0, 0x4($t7)
/* C841C 800C781C 01394824 */  and        $t1, $t1, $t9
/* C8420 800C7820 000948C0 */  sll        $t1, $t1, 3
/* C8424 800C7824 01097821 */  addu       $t7, $t0, $t1
/* C8428 800C7828 91F80000 */  lbu        $t8, 0x0($t7)
/* C842C 800C782C 2F010011 */  sltiu      $at, $t8, 0x11
/* C8430 800C7830 5020FFEA */  beql       $at, $zero, .L800C77DC_C83DC
/* C8434 800C7834 91E80001 */   lbu       $t0, 0x1($t7)
/* C8438 800C7838 91E20001 */  lbu        $v0, 0x1($t7)
.L800C783C_C843C:
/* C843C 800C783C 02028022 */  sub        $s0, $s0, $v0 /* handwritten instruction */
/* C8440 800C7840 0218082B */  sltu       $at, $s0, $t8
/* C8444 800C7844 10200008 */  beqz       $at, .L800C7868_C8468
/* C8448 800C7848 0059C806 */   srlv      $t9, $t9, $v0
.L800C784C_C844C:
/* C844C 800C784C 92420000 */  lbu        $v0, 0x0($s2)
/* C8450 800C7850 26520001 */  addiu      $s2, $s2, 0x1
/* C8454 800C7854 02021004 */  sllv       $v0, $v0, $s0
/* C8458 800C7858 26100008 */  addiu      $s0, $s0, 0x8
/* C845C 800C785C 0218082A */  slt        $at, $s0, $t8
/* C8460 800C7860 1420FFFA */  bnez       $at, .L800C784C_C844C
/* C8464 800C7864 0322C825 */   or        $t9, $t9, $v0
.L800C7868_C8468:
/* C8468 800C7868 00181040 */  sll        $v0, $t8, 1
/* C846C 800C786C 004B1021 */  addu       $v0, $v0, $t3
/* C8470 800C7870 94490000 */  lhu        $t1, 0x0($v0)
/* C8474 800C7874 95E30004 */  lhu        $v1, 0x4($t7)
/* C8478 800C7878 31C20003 */  andi       $v0, $t6, 0x3
/* C847C 800C787C 01394824 */  and        $t1, $t1, $t9
/* C8480 800C7880 02234022 */  sub        $t0, $s1, $v1 /* handwritten instruction */
/* C8484 800C7884 01094022 */  sub        $t0, $t0, $t1 /* handwritten instruction */
/* C8488 800C7888 0319C806 */  srlv       $t9, $t9, $t8
/* C848C 800C788C 1040000A */  beqz       $v0, .L800C78B8_C84B8
/* C8490 800C7890 02188022 */   sub       $s0, $s0, $t8 /* handwritten instruction */
/* C8494 800C7894 01C27022 */  sub        $t6, $t6, $v0 /* handwritten instruction */
.L800C7898_C8498:
/* C8498 800C7898 910A0000 */  lbu        $t2, 0x0($t0)
/* C849C 800C789C 2042FFFF */  addi       $v0, $v0, -0x1 /* handwritten instruction */
/* C84A0 800C78A0 21080001 */  addi       $t0, $t0, 0x1 /* handwritten instruction */
/* C84A4 800C78A4 22310001 */  addi       $s1, $s1, 0x1 /* handwritten instruction */
/* C84A8 800C78A8 1440FFFB */  bnez       $v0, .L800C7898_C8498
/* C84AC 800C78AC A22AFFFF */   sb        $t2, -0x1($s1)
/* C84B0 800C78B0 51C0FF74 */  beql       $t6, $zero, .L800C7684_C8284
/* C84B4 800C78B4 0206082B */   sltu      $at, $s0, $a2
.L800C78B8_C84B8:
/* C84B8 800C78B8 91020000 */  lbu        $v0, 0x0($t0)
/* C84BC 800C78BC 25CEFFFC */  addiu      $t6, $t6, -0x4
/* C84C0 800C78C0 25080004 */  addiu      $t0, $t0, 0x4
/* C84C4 800C78C4 A2220000 */  sb         $v0, 0x0($s1)
/* C84C8 800C78C8 9103FFFD */  lbu        $v1, -0x3($t0)
/* C84CC 800C78CC 26310004 */  addiu      $s1, $s1, 0x4
/* C84D0 800C78D0 A223FFFD */  sb         $v1, -0x3($s1)
/* C84D4 800C78D4 9109FFFE */  lbu        $t1, -0x2($t0)
/* C84D8 800C78D8 A229FFFE */  sb         $t1, -0x2($s1)
/* C84DC 800C78DC 910AFFFF */  lbu        $t2, -0x1($t0)
/* C84E0 800C78E0 15C0FFF5 */  bnez       $t6, .L800C78B8_C84B8
/* C84E4 800C78E4 A22AFFFF */   sb        $t2, -0x1($s1)
/* C84E8 800C78E8 08031DA0 */  j          .L800C7680_C8280
/* C84EC 800C78EC 00000000 */   nop
.L800C78F0_C84F0:
/* C84F0 800C78F0 3C01800E */  lui        $at, %hi(gzip_inflate_input)
/* C84F4 800C78F4 AC323D88 */  sw         $s2, %lo(gzip_inflate_input)($at)
/* C84F8 800C78F8 3C01800E */  lui        $at, %hi(gzip_inflate_output)
/* C84FC 800C78FC AC313D8C */  sw         $s1, %lo(gzip_inflate_output)($at)
/* C8500 800C7900 3C018013 */  lui        $at, %hi(gzip_bit_buffer)
/* C8504 800C7904 AC39B120 */  sw         $t9, %lo(gzip_bit_buffer)($at)
/* C8508 800C7908 3C018013 */  lui        $at, %hi(gzip_num_bits)
/* C850C 800C790C AC30B124 */  sw         $s0, %lo(gzip_num_bits)($at)
/* C8510 800C7910 8FB20008 */  lw         $s2, 0x8($sp)
/* C8514 800C7914 8FB10004 */  lw         $s1, 0x4($sp)
/* C8518 800C7918 8FB00000 */  lw         $s0, 0x0($sp)
/* C851C 800C791C 03E00008 */  jr         $ra
/* C8520 800C7920 27BD0010 */   addiu     $sp, $sp, 0x10
/* C8524 800C7924 00000000 */  nop
/* C8528 800C7928 00000000 */  nop
/* C852C 800C792C 00000000 */  nop
