.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel func_800D2D40
/* D3940 800D2D40 3C1A800D */  lui        $k0, %hi(__osException) /* handwritten instruction */
/* D3944 800D2D44 275A2D50 */  addiu      $k0, $k0, %lo(__osException) /* handwritten instruction */
/* D3948 800D2D48 03400008 */  jr         $k0
/* D394C 800D2D4C 00000000 */   nop

/* Handwritten function */
glabel __osException
/* D3950 800D2D50 3C1A8013 */  lui        $k0, %hi(__osThreadSave) /* handwritten instruction */
/* D3954 800D2D54 275AD2D0 */  addiu      $k0, $k0, %lo(__osThreadSave) /* handwritten instruction */
/* D3958 800D2D58 FF410020 */  sd         $at, 0x20($k0) /* handwritten instruction */
/* D395C 800D2D5C 401B6000 */  mfc0       $k1, $12 /* handwritten instruction */
/* D3960 800D2D60 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
/* D3964 800D2D64 2401FFFC */  addiu      $at, $zero, -0x4
/* D3968 800D2D68 0361D824 */  and        $k1, $k1, $at
/* D396C 800D2D6C 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
/* D3970 800D2D70 FF480058 */  sd         $t0, 0x58($k0) /* handwritten instruction */
/* D3974 800D2D74 FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
/* D3978 800D2D78 FF4A0068 */  sd         $t2, 0x68($k0) /* handwritten instruction */
/* D397C 800D2D7C AF400018 */  sw         $zero, 0x18($k0) /* handwritten instruction */
/* D3980 800D2D80 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
/* D3984 800D2D84 03404025 */  or         $t0, $k0, $zero
/* D3988 800D2D88 3C1A800E */  lui        $k0, %hi(D_800E4920) /* handwritten instruction */
/* D398C 800D2D8C 8F5A4920 */  lw         $k0, %lo(D_800E4920)($k0) /* handwritten instruction */
/* D3990 800D2D90 DD090020 */  ld         $t1, 0x20($t0)
/* D3994 800D2D94 FF490020 */  sd         $t1, 0x20($k0) /* handwritten instruction */
/* D3998 800D2D98 DD090118 */  ld         $t1, 0x118($t0)
/* D399C 800D2D9C FF490118 */  sd         $t1, 0x118($k0) /* handwritten instruction */
/* D39A0 800D2DA0 DD090058 */  ld         $t1, 0x58($t0)
/* D39A4 800D2DA4 FF490058 */  sd         $t1, 0x58($k0) /* handwritten instruction */
/* D39A8 800D2DA8 DD090060 */  ld         $t1, 0x60($t0)
/* D39AC 800D2DAC FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
/* D39B0 800D2DB0 DD090068 */  ld         $t1, 0x68($t0)
/* D39B4 800D2DB4 FF490068 */  sd         $t1, 0x68($k0) /* handwritten instruction */
/* D39B8 800D2DB8 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
/* D39BC 800D2DBC 00004012 */  mflo       $t0
/* D39C0 800D2DC0 FF480108 */  sd         $t0, 0x108($k0) /* handwritten instruction */
/* D39C4 800D2DC4 00004010 */  mfhi       $t0
/* D39C8 800D2DC8 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
/* D39CC 800D2DCC FF420028 */  sd         $v0, 0x28($k0) /* handwritten instruction */
/* D39D0 800D2DD0 FF430030 */  sd         $v1, 0x30($k0) /* handwritten instruction */
/* D39D4 800D2DD4 FF440038 */  sd         $a0, 0x38($k0) /* handwritten instruction */
/* D39D8 800D2DD8 FF450040 */  sd         $a1, 0x40($k0) /* handwritten instruction */
/* D39DC 800D2DDC FF460048 */  sd         $a2, 0x48($k0) /* handwritten instruction */
/* D39E0 800D2DE0 FF470050 */  sd         $a3, 0x50($k0) /* handwritten instruction */
/* D39E4 800D2DE4 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
/* D39E8 800D2DE8 FF4C0078 */  sd         $t4, 0x78($k0) /* handwritten instruction */
/* D39EC 800D2DEC FF4D0080 */  sd         $t5, 0x80($k0) /* handwritten instruction */
/* D39F0 800D2DF0 FF4E0088 */  sd         $t6, 0x88($k0) /* handwritten instruction */
/* D39F4 800D2DF4 FF4F0090 */  sd         $t7, 0x90($k0) /* handwritten instruction */
/* D39F8 800D2DF8 FF500098 */  sd         $s0, 0x98($k0) /* handwritten instruction */
/* D39FC 800D2DFC FF5100A0 */  sd         $s1, 0xA0($k0) /* handwritten instruction */
/* D3A00 800D2E00 FF5200A8 */  sd         $s2, 0xA8($k0) /* handwritten instruction */
/* D3A04 800D2E04 FF5300B0 */  sd         $s3, 0xB0($k0) /* handwritten instruction */
/* D3A08 800D2E08 FF5400B8 */  sd         $s4, 0xB8($k0) /* handwritten instruction */
/* D3A0C 800D2E0C FF5500C0 */  sd         $s5, 0xC0($k0) /* handwritten instruction */
/* D3A10 800D2E10 FF5600C8 */  sd         $s6, 0xC8($k0) /* handwritten instruction */
/* D3A14 800D2E14 FF5700D0 */  sd         $s7, 0xD0($k0) /* handwritten instruction */
/* D3A18 800D2E18 FF5800D8 */  sd         $t8, 0xD8($k0) /* handwritten instruction */
/* D3A1C 800D2E1C FF5900E0 */  sd         $t9, 0xE0($k0) /* handwritten instruction */
/* D3A20 800D2E20 FF5C00E8 */  sd         $gp, 0xE8($k0) /* handwritten instruction */
/* D3A24 800D2E24 FF5D00F0 */  sd         $sp, 0xF0($k0) /* handwritten instruction */
/* D3A28 800D2E28 FF5E00F8 */  sd         $fp, 0xF8($k0) /* handwritten instruction */
/* D3A2C 800D2E2C FF5F0100 */  sd         $ra, 0x100($k0) /* handwritten instruction */
/* D3A30 800D2E30 1120000D */  beqz       $t1, .L800D2E68
/* D3A34 800D2E34 FF480110 */   sd        $t0, 0x110($k0) /* handwritten instruction */
/* D3A38 800D2E38 3C08800E */  lui        $t0, %hi(D_800E393C)
/* D3A3C 800D2E3C 2508393C */  addiu      $t0, $t0, %lo(D_800E393C)
/* D3A40 800D2E40 8D080000 */  lw         $t0, 0x0($t0)
/* D3A44 800D2E44 2401FFFF */  addiu      $at, $zero, -0x1
/* D3A48 800D2E48 01014026 */  xor        $t0, $t0, $at
/* D3A4C 800D2E4C 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
/* D3A50 800D2E50 3108FF00 */  andi       $t0, $t0, 0xFF00
/* D3A54 800D2E54 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
/* D3A58 800D2E58 01284825 */  or         $t1, $t1, $t0
/* D3A5C 800D2E5C 0361D824 */  and        $k1, $k1, $at
/* D3A60 800D2E60 0369D825 */  or         $k1, $k1, $t1
/* D3A64 800D2E64 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
.L800D2E68:
/* D3A68 800D2E68 3C09A430 */  lui        $t1, %hi(MI_INTR_MASK_REG)
/* D3A6C 800D2E6C 8D29000C */  lw         $t1, %lo(MI_INTR_MASK_REG)($t1)
/* D3A70 800D2E70 1120000B */  beqz       $t1, .L800D2EA0
/* D3A74 800D2E74 00000000 */   nop
/* D3A78 800D2E78 3C08800E */  lui        $t0, %hi(D_800E393C)
/* D3A7C 800D2E7C 2508393C */  addiu      $t0, $t0, %lo(D_800E393C)
/* D3A80 800D2E80 8D080000 */  lw         $t0, 0x0($t0)
/* D3A84 800D2E84 8F4C0128 */  lw         $t4, 0x128($k0) /* handwritten instruction */
/* D3A88 800D2E88 2401FFFF */  addiu      $at, $zero, -0x1
/* D3A8C 800D2E8C 00084402 */  srl        $t0, $t0, 16
/* D3A90 800D2E90 01014026 */  xor        $t0, $t0, $at
/* D3A94 800D2E94 3108003F */  andi       $t0, $t0, 0x3F
/* D3A98 800D2E98 010C4024 */  and        $t0, $t0, $t4
/* D3A9C 800D2E9C 01284825 */  or         $t1, $t1, $t0
.L800D2EA0:
/* D3AA0 800D2EA0 AF490128 */  sw         $t1, 0x128($k0) /* handwritten instruction */
/* D3AA4 800D2EA4 40087000 */  mfc0       $t0, $14 /* handwritten instruction */
/* D3AA8 800D2EA8 AF48011C */  sw         $t0, 0x11C($k0) /* handwritten instruction */
/* D3AAC 800D2EAC 8F480018 */  lw         $t0, 0x18($k0) /* handwritten instruction */
/* D3AB0 800D2EB0 11000014 */  beqz       $t0, .L800D2F04
/* D3AB4 800D2EB4 00000000 */   nop
/* D3AB8 800D2EB8 4448F800 */  cfc1       $t0, $31
/* D3ABC 800D2EBC 00000000 */  nop
/* D3AC0 800D2EC0 AF48012C */  sw         $t0, 0x12C($k0) /* handwritten instruction */
/* D3AC4 800D2EC4 F7400130 */  sdc1       $f0, 0x130($k0)
/* D3AC8 800D2EC8 F7420138 */  sdc1       $f2, 0x138($k0)
/* D3ACC 800D2ECC F7440140 */  sdc1       $f4, 0x140($k0)
/* D3AD0 800D2ED0 F7460148 */  sdc1       $f6, 0x148($k0)
/* D3AD4 800D2ED4 F7480150 */  sdc1       $f8, 0x150($k0)
/* D3AD8 800D2ED8 F74A0158 */  sdc1       $f10, 0x158($k0)
/* D3ADC 800D2EDC F74C0160 */  sdc1       $f12, 0x160($k0)
/* D3AE0 800D2EE0 F74E0168 */  sdc1       $f14, 0x168($k0)
/* D3AE4 800D2EE4 F7500170 */  sdc1       $f16, 0x170($k0)
/* D3AE8 800D2EE8 F7520178 */  sdc1       $f18, 0x178($k0)
/* D3AEC 800D2EEC F7540180 */  sdc1       $f20, 0x180($k0)
/* D3AF0 800D2EF0 F7560188 */  sdc1       $f22, 0x188($k0)
/* D3AF4 800D2EF4 F7580190 */  sdc1       $f24, 0x190($k0)
/* D3AF8 800D2EF8 F75A0198 */  sdc1       $f26, 0x198($k0)
/* D3AFC 800D2EFC F75C01A0 */  sdc1       $f28, 0x1A0($k0)
/* D3B00 800D2F00 F75E01A8 */  sdc1       $f30, 0x1A8($k0)
.L800D2F04:
/* D3B04 800D2F04 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
/* D3B08 800D2F08 AF480120 */  sw         $t0, 0x120($k0) /* handwritten instruction */
/* D3B0C 800D2F0C 24090002 */  addiu      $t1, $zero, 0x2
/* D3B10 800D2F10 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
/* D3B14 800D2F14 3109007C */  andi       $t1, $t0, 0x7C
/* D3B18 800D2F18 240A0024 */  addiu      $t2, $zero, 0x24
/* D3B1C 800D2F1C 112A00B0 */  beq        $t1, $t2, .L800D31E0
/* D3B20 800D2F20 00000000 */   nop
/* D3B24 800D2F24 240A002C */  addiu      $t2, $zero, 0x2C
/* D3B28 800D2F28 112A00FF */  beq        $t1, $t2, .L800D3328
/* D3B2C 800D2F2C 00000000 */   nop
/* D3B30 800D2F30 240A0000 */  addiu      $t2, $zero, 0x0
/* D3B34 800D2F34 152A00C3 */  bne        $t1, $t2, .L800D3244
/* D3B38 800D2F38 00000000 */   nop
/* D3B3C 800D2F3C 03688024 */  and        $s0, $k1, $t0
.L800D2F40:
/* D3B40 800D2F40 3209FF00 */  andi       $t1, $s0, 0xFF00
/* D3B44 800D2F44 00095302 */  srl        $t2, $t1, 12
/* D3B48 800D2F48 15400003 */  bnez       $t2, .L800D2F58
/* D3B4C 800D2F4C 00000000 */   nop
/* D3B50 800D2F50 00095202 */  srl        $t2, $t1, 8
/* D3B54 800D2F54 214A0010 */  addi       $t2, $t2, 0x10 /* handwritten instruction */
.L800D2F58:
/* D3B58 800D2F58 3C01800F */  lui        $at, %hi(D_800E9700)
/* D3B5C 800D2F5C 002A0821 */  addu       $at, $at, $t2
/* D3B60 800D2F60 902A9700 */  lbu        $t2, %lo(D_800E9700)($at)
/* D3B64 800D2F64 3C01800F */  lui        $at, %hi(jtbl_800E9720)
/* D3B68 800D2F68 002A0821 */  addu       $at, $at, $t2
/* D3B6C 800D2F6C 8C2A9720 */  lw         $t2, %lo(jtbl_800E9720)($at)
/* D3B70 800D2F70 01400008 */  jr         $t2
/* D3B74 800D2F74 00000000 */   nop
glabel .L800D2F78
/* D3B78 800D2F78 2401DFFF */  addiu      $at, $zero, -0x2001
/* D3B7C 800D2F7C 1000FFF0 */  b          .L800D2F40
/* D3B80 800D2F80 02018024 */   and       $s0, $s0, $at
glabel .L800D2F84
/* D3B84 800D2F84 2401BFFF */  addiu      $at, $zero, -0x4001
/* D3B88 800D2F88 1000FFED */  b          .L800D2F40
/* D3B8C 800D2F8C 02018024 */   and       $s0, $s0, $at
glabel .L800D2F90
/* D3B90 800D2F90 40095800 */  mfc0       $t1, $11 /* handwritten instruction */
/* D3B94 800D2F94 40895800 */  mtc0       $t1, $11 /* handwritten instruction */
/* D3B98 800D2F98 0C034C9D */  jal        func_800D3274
/* D3B9C 800D2F9C 24040018 */   addiu     $a0, $zero, 0x18
/* D3BA0 800D2FA0 3C01FFFF */  lui        $at, (0xFFFF7FFF >> 16)
/* D3BA4 800D2FA4 34217FFF */  ori        $at, $at, (0xFFFF7FFF & 0xFFFF)
/* D3BA8 800D2FA8 1000FFE5 */  b          .L800D2F40
/* D3BAC 800D2FAC 02018024 */   and       $s0, $s0, $at
glabel .L800D2FB0
/* D3BB0 800D2FB0 2401F7FF */  addiu      $at, $zero, -0x801
/* D3BB4 800D2FB4 02018024 */  and        $s0, $s0, $at
/* D3BB8 800D2FB8 240A0004 */  addiu      $t2, $zero, 0x4
/* D3BBC 800D2FBC 3C01800E */  lui        $at, %hi(D_800E4930)
/* D3BC0 800D2FC0 002A0821 */  addu       $at, $at, $t2
/* D3BC4 800D2FC4 8C2A4930 */  lw         $t2, %lo(D_800E4930)($at)
/* D3BC8 800D2FC8 3C1D8013 */  lui        $sp, %hi(D_8012AB70)
/* D3BCC 800D2FCC 27BDAB70 */  addiu      $sp, $sp, %lo(D_8012AB70)
/* D3BD0 800D2FD0 24040010 */  addiu      $a0, $zero, 0x10
/* D3BD4 800D2FD4 11400007 */  beqz       $t2, .L800D2FF4
/* D3BD8 800D2FD8 27BD0FF0 */   addiu     $sp, $sp, 0xFF0
/* D3BDC 800D2FDC 0140F809 */  jalr       $t2
/* D3BE0 800D2FE0 00000000 */   nop
/* D3BE4 800D2FE4 10400003 */  beqz       $v0, .L800D2FF4
/* D3BE8 800D2FE8 00000000 */   nop
/* D3BEC 800D2FEC 10000082 */  b          .L800D31F8
/* D3BF0 800D2FF0 00000000 */   nop
.L800D2FF4:
/* D3BF4 800D2FF4 0C034C9D */  jal        func_800D3274
/* D3BF8 800D2FF8 00000000 */   nop
/* D3BFC 800D2FFC 1000FFD0 */  b          .L800D2F40
/* D3C00 800D3000 00000000 */   nop
glabel .L800D3004
/* D3C04 800D3004 3C08800E */  lui        $t0, %hi(D_800E393C)
/* D3C08 800D3008 2508393C */  addiu      $t0, $t0, %lo(D_800E393C)
/* D3C0C 800D300C 8D080000 */  lw         $t0, 0x0($t0)
/* D3C10 800D3010 3C11A430 */  lui        $s1, %hi(MI_INTR_REG)
/* D3C14 800D3014 8E310008 */  lw         $s1, %lo(MI_INTR_REG)($s1)
/* D3C18 800D3018 00084402 */  srl        $t0, $t0, 16
/* D3C1C 800D301C 02288824 */  and        $s1, $s1, $t0
/* D3C20 800D3020 32290001 */  andi       $t1, $s1, 0x1
/* D3C24 800D3024 11200013 */  beqz       $t1, .L800D3074
/* D3C28 800D3028 00000000 */   nop
/* D3C2C 800D302C 3C0CA404 */  lui        $t4, %hi(SP_STATUS_REG)
/* D3C30 800D3030 8D8C0010 */  lw         $t4, %lo(SP_STATUS_REG)($t4)
/* D3C34 800D3034 24090008 */  addiu      $t1, $zero, 0x8
/* D3C38 800D3038 3C01A404 */  lui        $at, %hi(SP_STATUS_REG)
/* D3C3C 800D303C 318C0300 */  andi       $t4, $t4, 0x300
/* D3C40 800D3040 3231003E */  andi       $s1, $s1, 0x3E
/* D3C44 800D3044 11800007 */  beqz       $t4, .L800D3064
/* D3C48 800D3048 AC290010 */   sw        $t1, %lo(SP_STATUS_REG)($at)
/* D3C4C 800D304C 0C034C9D */  jal        func_800D3274
/* D3C50 800D3050 24040020 */   addiu     $a0, $zero, 0x20
/* D3C54 800D3054 12200038 */  beqz       $s1, .L800D3138
/* D3C58 800D3058 00000000 */   nop
/* D3C5C 800D305C 10000005 */  b          .L800D3074
/* D3C60 800D3060 00000000 */   nop
.L800D3064:
/* D3C64 800D3064 0C034C9D */  jal        func_800D3274
/* D3C68 800D3068 24040058 */   addiu     $a0, $zero, 0x58
/* D3C6C 800D306C 12200032 */  beqz       $s1, .L800D3138
/* D3C70 800D3070 00000000 */   nop
.L800D3074:
/* D3C74 800D3074 32290008 */  andi       $t1, $s1, 0x8
/* D3C78 800D3078 11200007 */  beqz       $t1, .L800D3098
/* D3C7C 800D307C 3C01A440 */   lui       $at, %hi(VI_V_CURRENT_LINE_REG)
/* D3C80 800D3080 32310037 */  andi       $s1, $s1, 0x37
/* D3C84 800D3084 AC200010 */  sw         $zero, %lo(VI_V_CURRENT_LINE_REG)($at)
/* D3C88 800D3088 0C034C9D */  jal        func_800D3274
/* D3C8C 800D308C 24040038 */   addiu     $a0, $zero, 0x38
/* D3C90 800D3090 12200029 */  beqz       $s1, .L800D3138
/* D3C94 800D3094 00000000 */   nop
.L800D3098:
/* D3C98 800D3098 32290004 */  andi       $t1, $s1, 0x4
/* D3C9C 800D309C 11200009 */  beqz       $t1, .L800D30C4
/* D3CA0 800D30A0 00000000 */   nop
/* D3CA4 800D30A4 24090001 */  addiu      $t1, $zero, 0x1
/* D3CA8 800D30A8 3C01A450 */  lui        $at, %hi(AI_STATUS_REG)
/* D3CAC 800D30AC 3231003B */  andi       $s1, $s1, 0x3B
/* D3CB0 800D30B0 AC29000C */  sw         $t1, %lo(AI_STATUS_REG)($at)
/* D3CB4 800D30B4 0C034C9D */  jal        func_800D3274
/* D3CB8 800D30B8 24040030 */   addiu     $a0, $zero, 0x30
/* D3CBC 800D30BC 1220001E */  beqz       $s1, .L800D3138
/* D3CC0 800D30C0 00000000 */   nop
.L800D30C4:
/* D3CC4 800D30C4 32290002 */  andi       $t1, $s1, 0x2
/* D3CC8 800D30C8 11200007 */  beqz       $t1, .L800D30E8
/* D3CCC 800D30CC 3C01A480 */   lui       $at, %hi(SI_STATUS_REG)
/* D3CD0 800D30D0 3231003D */  andi       $s1, $s1, 0x3D
/* D3CD4 800D30D4 AC200018 */  sw         $zero, %lo(SI_STATUS_REG)($at)
/* D3CD8 800D30D8 0C034C9D */  jal        func_800D3274
/* D3CDC 800D30DC 24040028 */   addiu     $a0, $zero, 0x28
/* D3CE0 800D30E0 12200015 */  beqz       $s1, .L800D3138
/* D3CE4 800D30E4 00000000 */   nop
.L800D30E8:
/* D3CE8 800D30E8 32290010 */  andi       $t1, $s1, 0x10
/* D3CEC 800D30EC 11200009 */  beqz       $t1, .L800D3114
/* D3CF0 800D30F0 00000000 */   nop
/* D3CF4 800D30F4 24090002 */  addiu      $t1, $zero, 0x2
/* D3CF8 800D30F8 3C01A460 */  lui        $at, %hi(PI_STATUS_REG)
/* D3CFC 800D30FC 3231002F */  andi       $s1, $s1, 0x2F
/* D3D00 800D3100 AC290010 */  sw         $t1, %lo(PI_STATUS_REG)($at)
/* D3D04 800D3104 0C034C9D */  jal        func_800D3274
/* D3D08 800D3108 24040040 */   addiu     $a0, $zero, 0x40
/* D3D0C 800D310C 1220000A */  beqz       $s1, .L800D3138
/* D3D10 800D3110 00000000 */   nop
.L800D3114:
/* D3D14 800D3114 32290020 */  andi       $t1, $s1, 0x20
/* D3D18 800D3118 11200007 */  beqz       $t1, .L800D3138
/* D3D1C 800D311C 00000000 */   nop
/* D3D20 800D3120 24090800 */  addiu      $t1, $zero, 0x800
/* D3D24 800D3124 3C01A430 */  lui        $at, %hi(MI_MODE_REG)
/* D3D28 800D3128 3231001F */  andi       $s1, $s1, 0x1F
/* D3D2C 800D312C AC290000 */  sw         $t1, %lo(MI_MODE_REG)($at)
/* D3D30 800D3130 0C034C9D */  jal        func_800D3274
/* D3D34 800D3134 24040048 */   addiu     $a0, $zero, 0x48
.L800D3138:
/* D3D38 800D3138 2401FBFF */  addiu      $at, $zero, -0x401
/* D3D3C 800D313C 1000FF80 */  b          .L800D2F40
/* D3D40 800D3140 02018024 */   and       $s0, $s0, $at
glabel .L800D3144
/* D3D44 800D3144 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
/* D3D48 800D3148 2401EFFF */  addiu      $at, $zero, -0x1001
/* D3D4C 800D314C 3C09800E */  lui        $t1, %hi(D_800E3938)
/* D3D50 800D3150 0361D824 */  and        $k1, $k1, $at
/* D3D54 800D3154 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
/* D3D58 800D3158 25293938 */  addiu      $t1, $t1, %lo(D_800E3938)
/* D3D5C 800D315C 8D2A0000 */  lw         $t2, 0x0($t1)
/* D3D60 800D3160 11400003 */  beqz       $t2, .L800D3170
/* D3D64 800D3164 2401EFFF */   addiu     $at, $zero, -0x1001
/* D3D68 800D3168 10000023 */  b          .L800D31F8
/* D3D6C 800D316C 02018024 */   and       $s0, $s0, $at
.L800D3170:
/* D3D70 800D3170 240A0001 */  addiu      $t2, $zero, 0x1
/* D3D74 800D3174 AD2A0000 */  sw         $t2, 0x0($t1)
/* D3D78 800D3178 0C034C9D */  jal        func_800D3274
/* D3D7C 800D317C 24040070 */   addiu     $a0, $zero, 0x70
/* D3D80 800D3180 3C0A800E */  lui        $t2, %hi(D_800E4918)
/* D3D84 800D3184 8D4A4918 */  lw         $t2, %lo(D_800E4918)($t2)
/* D3D88 800D3188 2401EFFF */  addiu      $at, $zero, -0x1001
/* D3D8C 800D318C 02018024 */  and        $s0, $s0, $at
/* D3D90 800D3190 8D5B0118 */  lw         $k1, 0x118($t2) /* handwritten instruction */
/* D3D94 800D3194 0361D824 */  and        $k1, $k1, $at
/* D3D98 800D3198 10000017 */  b          .L800D31F8
/* D3D9C 800D319C AD5B0118 */   sw        $k1, 0x118($t2) /* handwritten instruction */
glabel .L800D31A0
/* D3DA0 800D31A0 2401FDFF */  addiu      $at, $zero, -0x201
/* D3DA4 800D31A4 01014024 */  and        $t0, $t0, $at
/* D3DA8 800D31A8 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
/* D3DAC 800D31AC 0C034C9D */  jal        func_800D3274
/* D3DB0 800D31B0 24040008 */   addiu     $a0, $zero, 0x8
/* D3DB4 800D31B4 2401FDFF */  addiu      $at, $zero, -0x201
/* D3DB8 800D31B8 1000FF61 */  b          .L800D2F40
/* D3DBC 800D31BC 02018024 */   and       $s0, $s0, $at
glabel .L800D31C0
/* D3DC0 800D31C0 2401FEFF */  addiu      $at, $zero, -0x101
/* D3DC4 800D31C4 01014024 */  and        $t0, $t0, $at
/* D3DC8 800D31C8 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
/* D3DCC 800D31CC 0C034C9D */  jal        func_800D3274
/* D3DD0 800D31D0 24040000 */   addiu     $a0, $zero, 0x0
/* D3DD4 800D31D4 2401FEFF */  addiu      $at, $zero, -0x101
/* D3DD8 800D31D8 1000FF59 */  b          .L800D2F40
/* D3DDC 800D31DC 02018024 */   and       $s0, $s0, $at
.L800D31E0:
/* D3DE0 800D31E0 24090001 */  addiu      $t1, $zero, 0x1
/* D3DE4 800D31E4 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
/* D3DE8 800D31E8 0C034C9D */  jal        func_800D3274
/* D3DEC 800D31EC 24040050 */   addiu     $a0, $zero, 0x50
/* D3DF0 800D31F0 10000001 */  b          .L800D31F8
/* D3DF4 800D31F4 00000000 */   nop
glabel .L800D31F8
/* D3DF8 800D31F8 3C0A800E */  lui        $t2, %hi(D_800E4918)
/* D3DFC 800D31FC 8D4A4918 */  lw         $t2, %lo(D_800E4918)($t2)
/* D3E00 800D3200 8F490004 */  lw         $t1, 0x4($k0) /* handwritten instruction */
/* D3E04 800D3204 8D4B0004 */  lw         $t3, 0x4($t2)
/* D3E08 800D3208 012B082A */  slt        $at, $t1, $t3
/* D3E0C 800D320C 10200007 */  beqz       $at, .L800D322C
/* D3E10 800D3210 00000000 */   nop
/* D3E14 800D3214 3C04800E */  lui        $a0, %hi(D_800E4918)
/* D3E18 800D3218 03402825 */  or         $a1, $k0, $zero
/* D3E1C 800D321C 0C034D17 */  jal        func_800D345C
/* D3E20 800D3220 24844918 */   addiu     $a0, $a0, %lo(D_800E4918)
/* D3E24 800D3224 08034D2D */  j          func_800D34B4
/* D3E28 800D3228 00000000 */   nop
.L800D322C:
/* D3E2C 800D322C 3C09800E */  lui        $t1, %hi(D_800E4918)
/* D3E30 800D3230 25294918 */  addiu      $t1, $t1, %lo(D_800E4918)
/* D3E34 800D3234 8D2A0000 */  lw         $t2, 0x0($t1)
/* D3E38 800D3238 AF4A0000 */  sw         $t2, 0x0($k0) /* handwritten instruction */
/* D3E3C 800D323C 08034D2D */  j          func_800D34B4
/* D3E40 800D3240 AD3A0000 */   sw        $k0, 0x0($t1) /* handwritten instruction */
.L800D3244:
/* D3E44 800D3244 3C01800E */  lui        $at, %hi(D_800E4924)
/* D3E48 800D3248 AC3A4924 */  sw         $k0, %lo(D_800E4924)($at) /* handwritten instruction */
/* D3E4C 800D324C 24090001 */  addiu      $t1, $zero, 0x1
/* D3E50 800D3250 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
/* D3E54 800D3254 24090002 */  addiu      $t1, $zero, 0x2
/* D3E58 800D3258 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
/* D3E5C 800D325C 400A4000 */  mfc0       $t2, $8 /* handwritten instruction */
/* D3E60 800D3260 AF4A0124 */  sw         $t2, 0x124($k0) /* handwritten instruction */
/* D3E64 800D3264 0C034C9D */  jal        func_800D3274
/* D3E68 800D3268 24040060 */   addiu     $a0, $zero, 0x60
/* D3E6C 800D326C 08034D2D */  j          func_800D34B4
/* D3E70 800D3270 00000000 */   nop
glabel func_800D3274
/* D3E74 800D3274 3C0A8013 */  lui        $t2, %hi(D_8012CD60)
/* D3E78 800D3278 254ACD60 */  addiu      $t2, $t2, %lo(D_8012CD60)
/* D3E7C 800D327C 01445021 */  addu       $t2, $t2, $a0
/* D3E80 800D3280 8D490000 */  lw         $t1, 0x0($t2)
/* D3E84 800D3284 03E09025 */  or         $s2, $ra, $zero
/* D3E88 800D3288 11200025 */  beqz       $t1, .L800D3320
/* D3E8C 800D328C 00000000 */   nop
/* D3E90 800D3290 8D2B0008 */  lw         $t3, 0x8($t1)
/* D3E94 800D3294 8D2C0010 */  lw         $t4, 0x10($t1)
/* D3E98 800D3298 016C082A */  slt        $at, $t3, $t4
/* D3E9C 800D329C 10200020 */  beqz       $at, .L800D3320
/* D3EA0 800D32A0 00000000 */   nop
/* D3EA4 800D32A4 8D2D000C */  lw         $t5, 0xC($t1)
/* D3EA8 800D32A8 01AB6821 */  addu       $t5, $t5, $t3
/* D3EAC 800D32AC 01AC001A */  div        $zero, $t5, $t4
/* D3EB0 800D32B0 15800002 */  bnez       $t4, .L800D32BC
/* D3EB4 800D32B4 00000000 */   nop
/* D3EB8 800D32B8 0007000D */  break      7
.L800D32BC:
/* D3EBC 800D32BC 2401FFFF */  addiu      $at, $zero, -0x1
/* D3EC0 800D32C0 15810004 */  bne        $t4, $at, .L800D32D4
/* D3EC4 800D32C4 3C018000 */   lui       $at, (0x80000000 >> 16)
/* D3EC8 800D32C8 15A10002 */  bne        $t5, $at, .L800D32D4
/* D3ECC 800D32CC 00000000 */   nop
/* D3ED0 800D32D0 0006000D */  break      6
.L800D32D4:
/* D3ED4 800D32D4 8D2C0014 */  lw         $t4, 0x14($t1)
/* D3ED8 800D32D8 00006810 */  mfhi       $t5
/* D3EDC 800D32DC 000D6880 */  sll        $t5, $t5, 2
/* D3EE0 800D32E0 018D6021 */  addu       $t4, $t4, $t5
/* D3EE4 800D32E4 8D4D0004 */  lw         $t5, 0x4($t2)
/* D3EE8 800D32E8 256A0001 */  addiu      $t2, $t3, 0x1
/* D3EEC 800D32EC AD8D0000 */  sw         $t5, 0x0($t4)
/* D3EF0 800D32F0 AD2A0008 */  sw         $t2, 0x8($t1)
/* D3EF4 800D32F4 8D2A0000 */  lw         $t2, 0x0($t1)
/* D3EF8 800D32F8 8D4B0000 */  lw         $t3, 0x0($t2)
/* D3EFC 800D32FC 11600008 */  beqz       $t3, .L800D3320
/* D3F00 800D3300 00000000 */   nop
/* D3F04 800D3304 0C034D29 */  jal        func_800D34A4
/* D3F08 800D3308 01202025 */   or        $a0, $t1, $zero
/* D3F0C 800D330C 00405025 */  or         $t2, $v0, $zero
/* D3F10 800D3310 3C04800E */  lui        $a0, %hi(D_800E4918)
/* D3F14 800D3314 01402825 */  or         $a1, $t2, $zero
/* D3F18 800D3318 0C034D17 */  jal        func_800D345C
/* D3F1C 800D331C 24844918 */   addiu     $a0, $a0, %lo(D_800E4918)
.L800D3320:
/* D3F20 800D3320 02400008 */  jr         $s2
/* D3F24 800D3324 00000000 */   nop
.L800D3328:
/* D3F28 800D3328 3C013000 */  lui        $at, (0x30000000 >> 16)
/* D3F2C 800D332C 01014824 */  and        $t1, $t0, $at
/* D3F30 800D3330 00094F02 */  srl        $t1, $t1, 28
/* D3F34 800D3334 240A0001 */  addiu      $t2, $zero, 0x1
/* D3F38 800D3338 152AFFC2 */  bne        $t1, $t2, .L800D3244
/* D3F3C 800D333C 00000000 */   nop
/* D3F40 800D3340 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
/* D3F44 800D3344 3C012000 */  lui        $at, (0x20000000 >> 16)
/* D3F48 800D3348 24090001 */  addiu      $t1, $zero, 0x1
/* D3F4C 800D334C 0361D825 */  or         $k1, $k1, $at
/* D3F50 800D3350 AF490018 */  sw         $t1, 0x18($k0) /* handwritten instruction */
/* D3F54 800D3354 1000FFB5 */  b          .L800D322C
/* D3F58 800D3358 AF5B0118 */   sw        $k1, 0x118($k0) /* handwritten instruction */

/* Handwritten function */
glabel func_800D335C
/* D3F5C 800D335C 3C05800E */  lui        $a1, %hi(D_800E4920)
/* D3F60 800D3360 8CA54920 */  lw         $a1, %lo(D_800E4920)($a1)
/* D3F64 800D3364 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
/* D3F68 800D3368 8CBB0018 */  lw         $k1, 0x18($a1) /* handwritten instruction */
/* D3F6C 800D336C 35080002 */  ori        $t0, $t0, 0x2
/* D3F70 800D3370 ACA80118 */  sw         $t0, 0x118($a1)
/* D3F74 800D3374 FCB00098 */  sd         $s0, 0x98($a1)
/* D3F78 800D3378 FCB100A0 */  sd         $s1, 0xA0($a1)
/* D3F7C 800D337C FCB200A8 */  sd         $s2, 0xA8($a1)
/* D3F80 800D3380 FCB300B0 */  sd         $s3, 0xB0($a1)
/* D3F84 800D3384 FCB400B8 */  sd         $s4, 0xB8($a1)
/* D3F88 800D3388 FCB500C0 */  sd         $s5, 0xC0($a1)
/* D3F8C 800D338C FCB600C8 */  sd         $s6, 0xC8($a1)
/* D3F90 800D3390 FCB700D0 */  sd         $s7, 0xD0($a1)
/* D3F94 800D3394 FCBC00E8 */  sd         $gp, 0xE8($a1)
/* D3F98 800D3398 FCBD00F0 */  sd         $sp, 0xF0($a1)
/* D3F9C 800D339C FCBE00F8 */  sd         $fp, 0xF8($a1)
/* D3FA0 800D33A0 FCBF0100 */  sd         $ra, 0x100($a1)
/* D3FA4 800D33A4 13600009 */  beqz       $k1, .L800D33CC /* handwritten instruction */
/* D3FA8 800D33A8 ACBF011C */   sw        $ra, 0x11C($a1)
/* D3FAC 800D33AC 445BF800 */  cfc1       $k1, $31
/* D3FB0 800D33B0 F4B40180 */  sdc1       $f20, 0x180($a1)
/* D3FB4 800D33B4 F4B60188 */  sdc1       $f22, 0x188($a1)
/* D3FB8 800D33B8 F4B80190 */  sdc1       $f24, 0x190($a1)
/* D3FBC 800D33BC F4BA0198 */  sdc1       $f26, 0x198($a1)
/* D3FC0 800D33C0 F4BC01A0 */  sdc1       $f28, 0x1A0($a1)
/* D3FC4 800D33C4 F4BE01A8 */  sdc1       $f30, 0x1A8($a1)
/* D3FC8 800D33C8 ACBB012C */  sw         $k1, 0x12C($a1) /* handwritten instruction */
.L800D33CC:
/* D3FCC 800D33CC 8CBB0118 */  lw         $k1, 0x118($a1) /* handwritten instruction */
/* D3FD0 800D33D0 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
/* D3FD4 800D33D4 1120000D */  beqz       $t1, .L800D340C
/* D3FD8 800D33D8 00000000 */   nop
/* D3FDC 800D33DC 3C08800E */  lui        $t0, %hi(D_800E393C)
/* D3FE0 800D33E0 2508393C */  addiu      $t0, $t0, %lo(D_800E393C)
/* D3FE4 800D33E4 8D080000 */  lw         $t0, 0x0($t0)
/* D3FE8 800D33E8 2401FFFF */  addiu      $at, $zero, -0x1
/* D3FEC 800D33EC 01014026 */  xor        $t0, $t0, $at
/* D3FF0 800D33F0 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
/* D3FF4 800D33F4 3108FF00 */  andi       $t0, $t0, 0xFF00
/* D3FF8 800D33F8 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
/* D3FFC 800D33FC 01284825 */  or         $t1, $t1, $t0
/* D4000 800D3400 0361D824 */  and        $k1, $k1, $at
/* D4004 800D3404 0369D825 */  or         $k1, $k1, $t1
/* D4008 800D3408 ACBB0118 */  sw         $k1, 0x118($a1) /* handwritten instruction */
.L800D340C:
/* D400C 800D340C 3C1BA430 */  lui        $k1, %hi(MI_INTR_MASK_REG) /* handwritten instruction */
/* D4010 800D3410 8F7B000C */  lw         $k1, %lo(MI_INTR_MASK_REG)($k1) /* handwritten instruction */
/* D4014 800D3414 1360000B */  beqz       $k1, .L800D3444 /* handwritten instruction */
/* D4018 800D3418 00000000 */   nop
/* D401C 800D341C 3C1A800E */  lui        $k0, %hi(D_800E393C) /* handwritten instruction */
/* D4020 800D3420 275A393C */  addiu      $k0, $k0, %lo(D_800E393C) /* handwritten instruction */
/* D4024 800D3424 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
/* D4028 800D3428 8CA80128 */  lw         $t0, 0x128($a1)
/* D402C 800D342C 2401FFFF */  addiu      $at, $zero, -0x1
/* D4030 800D3430 001AD402 */  srl        $k0, $k0, 16
/* D4034 800D3434 0341D026 */  xor        $k0, $k0, $at
/* D4038 800D3438 335A003F */  andi       $k0, $k0, 0x3F /* handwritten instruction */
/* D403C 800D343C 0348D024 */  and        $k0, $k0, $t0
/* D4040 800D3440 037AD825 */  or         $k1, $k1, $k0
.L800D3444:
/* D4044 800D3444 10800003 */  beqz       $a0, .L800D3454
/* D4048 800D3448 ACBB0128 */   sw        $k1, 0x128($a1) /* handwritten instruction */
/* D404C 800D344C 0C034D17 */  jal        func_800D345C
/* D4050 800D3450 00000000 */   nop
.L800D3454:
/* D4054 800D3454 08034D2D */  j          func_800D34B4
/* D4058 800D3458 00000000 */   nop

glabel func_800D345C
/* D405C 800D345C 8C980000 */  lw         $t8, 0x0($a0)
/* D4060 800D3460 8CAF0004 */  lw         $t7, 0x4($a1)
/* D4064 800D3464 0080C825 */  or         $t9, $a0, $zero
/* D4068 800D3468 8F0E0004 */  lw         $t6, 0x4($t8)
/* D406C 800D346C 01CF082A */  slt        $at, $t6, $t7
/* D4070 800D3470 14200007 */  bnez       $at, .L800D3490
/* D4074 800D3474 00000000 */   nop
.L800D3478:
/* D4078 800D3478 0300C825 */  or         $t9, $t8, $zero
/* D407C 800D347C 8F180000 */  lw         $t8, 0x0($t8)
/* D4080 800D3480 8F0E0004 */  lw         $t6, 0x4($t8)
/* D4084 800D3484 01CF082A */  slt        $at, $t6, $t7
/* D4088 800D3488 1020FFFB */  beqz       $at, .L800D3478
/* D408C 800D348C 00000000 */   nop
.L800D3490:
/* D4090 800D3490 8F380000 */  lw         $t8, 0x0($t9)
/* D4094 800D3494 ACB80000 */  sw         $t8, 0x0($a1)
/* D4098 800D3498 AF250000 */  sw         $a1, 0x0($t9)
/* D409C 800D349C 03E00008 */  jr         $ra
/* D40A0 800D34A0 ACA40008 */   sw        $a0, 0x8($a1)

glabel func_800D34A4
/* D40A4 800D34A4 8C820000 */  lw         $v0, 0x0($a0)
/* D40A8 800D34A8 8C590000 */  lw         $t9, 0x0($v0)
/* D40AC 800D34AC 03E00008 */  jr         $ra
/* D40B0 800D34B0 AC990000 */   sw        $t9, 0x0($a0)

/* Handwritten function */
glabel func_800D34B4
/* D40B4 800D34B4 3C04800E */  lui        $a0, %hi(D_800E4918)
/* D40B8 800D34B8 0C034D29 */  jal        func_800D34A4
/* D40BC 800D34BC 24844918 */   addiu     $a0, $a0, %lo(D_800E4918)
/* D40C0 800D34C0 3C01800E */  lui        $at, %hi(D_800E4920)
/* D40C4 800D34C4 AC224920 */  sw         $v0, %lo(D_800E4920)($at)
/* D40C8 800D34C8 24080004 */  addiu      $t0, $zero, 0x4
/* D40CC 800D34CC A4480010 */  sh         $t0, 0x10($v0)
/* D40D0 800D34D0 0040D025 */  or         $k0, $v0, $zero
/* D40D4 800D34D4 3C08800E */  lui        $t0, %hi(D_800E393C)
/* D40D8 800D34D8 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
/* D40DC 800D34DC 2508393C */  addiu      $t0, $t0, %lo(D_800E393C)
/* D40E0 800D34E0 8D080000 */  lw         $t0, 0x0($t0)
/* D40E4 800D34E4 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
/* D40E8 800D34E8 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
/* D40EC 800D34EC 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
/* D40F0 800D34F0 3108FF00 */  andi       $t0, $t0, 0xFF00
/* D40F4 800D34F4 01284824 */  and        $t1, $t1, $t0
/* D40F8 800D34F8 0361D824 */  and        $k1, $k1, $at
/* D40FC 800D34FC 0369D825 */  or         $k1, $k1, $t1
/* D4100 800D3500 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
/* D4104 800D3504 DF5B0108 */  ld         $k1, 0x108($k0) /* handwritten instruction */
/* D4108 800D3508 DF410020 */  ld         $at, 0x20($k0) /* handwritten instruction */
/* D410C 800D350C DF420028 */  ld         $v0, 0x28($k0) /* handwritten instruction */
/* D4110 800D3510 03600013 */  mtlo       $k1
/* D4114 800D3514 DF5B0110 */  ld         $k1, 0x110($k0) /* handwritten instruction */
/* D4118 800D3518 DF430030 */  ld         $v1, 0x30($k0) /* handwritten instruction */
/* D411C 800D351C DF440038 */  ld         $a0, 0x38($k0) /* handwritten instruction */
/* D4120 800D3520 DF450040 */  ld         $a1, 0x40($k0) /* handwritten instruction */
/* D4124 800D3524 DF460048 */  ld         $a2, 0x48($k0) /* handwritten instruction */
/* D4128 800D3528 DF470050 */  ld         $a3, 0x50($k0) /* handwritten instruction */
/* D412C 800D352C DF480058 */  ld         $t0, 0x58($k0) /* handwritten instruction */
/* D4130 800D3530 DF490060 */  ld         $t1, 0x60($k0) /* handwritten instruction */
/* D4134 800D3534 DF4A0068 */  ld         $t2, 0x68($k0) /* handwritten instruction */
/* D4138 800D3538 DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
/* D413C 800D353C DF4C0078 */  ld         $t4, 0x78($k0) /* handwritten instruction */
/* D4140 800D3540 DF4D0080 */  ld         $t5, 0x80($k0) /* handwritten instruction */
/* D4144 800D3544 DF4E0088 */  ld         $t6, 0x88($k0) /* handwritten instruction */
/* D4148 800D3548 DF4F0090 */  ld         $t7, 0x90($k0) /* handwritten instruction */
/* D414C 800D354C DF500098 */  ld         $s0, 0x98($k0) /* handwritten instruction */
/* D4150 800D3550 DF5100A0 */  ld         $s1, 0xA0($k0) /* handwritten instruction */
/* D4154 800D3554 DF5200A8 */  ld         $s2, 0xA8($k0) /* handwritten instruction */
/* D4158 800D3558 DF5300B0 */  ld         $s3, 0xB0($k0) /* handwritten instruction */
/* D415C 800D355C DF5400B8 */  ld         $s4, 0xB8($k0) /* handwritten instruction */
/* D4160 800D3560 DF5500C0 */  ld         $s5, 0xC0($k0) /* handwritten instruction */
/* D4164 800D3564 DF5600C8 */  ld         $s6, 0xC8($k0) /* handwritten instruction */
/* D4168 800D3568 DF5700D0 */  ld         $s7, 0xD0($k0) /* handwritten instruction */
/* D416C 800D356C DF5800D8 */  ld         $t8, 0xD8($k0) /* handwritten instruction */
/* D4170 800D3570 DF5900E0 */  ld         $t9, 0xE0($k0) /* handwritten instruction */
/* D4174 800D3574 DF5C00E8 */  ld         $gp, 0xE8($k0) /* handwritten instruction */
/* D4178 800D3578 03600011 */  mthi       $k1
/* D417C 800D357C DF5D00F0 */  ld         $sp, 0xF0($k0) /* handwritten instruction */
/* D4180 800D3580 DF5E00F8 */  ld         $fp, 0xF8($k0) /* handwritten instruction */
/* D4184 800D3584 DF5F0100 */  ld         $ra, 0x100($k0) /* handwritten instruction */
/* D4188 800D3588 8F5B011C */  lw         $k1, 0x11C($k0) /* handwritten instruction */
/* D418C 800D358C 409B7000 */  mtc0       $k1, $14 /* handwritten instruction */
/* D4190 800D3590 8F5B0018 */  lw         $k1, 0x18($k0) /* handwritten instruction */
/* D4194 800D3594 13600013 */  beqz       $k1, .L800D35E4 /* handwritten instruction */
/* D4198 800D3598 00000000 */   nop
/* D419C 800D359C 8F5B012C */  lw         $k1, 0x12C($k0) /* handwritten instruction */
/* D41A0 800D35A0 44DBF800 */  ctc1       $k1, $31
/* D41A4 800D35A4 D7400130 */  ldc1       $f0, 0x130($k0)
/* D41A8 800D35A8 D7420138 */  ldc1       $f2, 0x138($k0)
/* D41AC 800D35AC D7440140 */  ldc1       $f4, 0x140($k0)
/* D41B0 800D35B0 D7460148 */  ldc1       $f6, 0x148($k0)
/* D41B4 800D35B4 D7480150 */  ldc1       $f8, 0x150($k0)
/* D41B8 800D35B8 D74A0158 */  ldc1       $f10, 0x158($k0)
/* D41BC 800D35BC D74C0160 */  ldc1       $f12, 0x160($k0)
/* D41C0 800D35C0 D74E0168 */  ldc1       $f14, 0x168($k0)
/* D41C4 800D35C4 D7500170 */  ldc1       $f16, 0x170($k0)
/* D41C8 800D35C8 D7520178 */  ldc1       $f18, 0x178($k0)
/* D41CC 800D35CC D7540180 */  ldc1       $f20, 0x180($k0)
/* D41D0 800D35D0 D7560188 */  ldc1       $f22, 0x188($k0)
/* D41D4 800D35D4 D7580190 */  ldc1       $f24, 0x190($k0)
/* D41D8 800D35D8 D75A0198 */  ldc1       $f26, 0x198($k0)
/* D41DC 800D35DC D75C01A0 */  ldc1       $f28, 0x1A0($k0)
/* D41E0 800D35E0 D75E01A8 */  ldc1       $f30, 0x1A8($k0)
.L800D35E4:
/* D41E4 800D35E4 8F5B0128 */  lw         $k1, 0x128($k0) /* handwritten instruction */
/* D41E8 800D35E8 3C1A800E */  lui        $k0, %hi(D_800E393C) /* handwritten instruction */
/* D41EC 800D35EC 275A393C */  addiu      $k0, $k0, %lo(D_800E393C) /* handwritten instruction */
/* D41F0 800D35F0 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
/* D41F4 800D35F4 001AD402 */  srl        $k0, $k0, 16
/* D41F8 800D35F8 037AD824 */  and        $k1, $k1, $k0
/* D41FC 800D35FC 001BD840 */  sll        $k1, $k1, 1
/* D4200 800D3600 3C1A800F */  lui        $k0, %hi(D_800E9560) /* handwritten instruction */
/* D4204 800D3604 275A9560 */  addiu      $k0, $k0, %lo(D_800E9560) /* handwritten instruction */
/* D4208 800D3608 037AD821 */  addu       $k1, $k1, $k0
/* D420C 800D360C 977B0000 */  lhu        $k1, 0x0($k1) /* handwritten instruction */
/* D4210 800D3610 3C1AA430 */  lui        $k0, %hi(MI_INTR_MASK_REG) /* handwritten instruction */
/* D4214 800D3614 275A000C */  addiu      $k0, $k0, %lo(MI_INTR_MASK_REG) /* handwritten instruction */
/* D4218 800D3618 AF5B0000 */  sw         $k1, 0x0($k0) /* handwritten instruction */
/* D421C 800D361C 00000000 */  nop
/* D4220 800D3620 00000000 */  nop
/* D4224 800D3624 00000000 */  nop
/* D4228 800D3628 00000000 */  nop
/* D422C 800D362C 42000018 */  eret /* handwritten instruction */
glabel D_800D3630
/* D4230 800D3630 0C0359A4 */  jal        func_800D6690
/* D4234 800D3634 00002025 */   or        $a0, $zero, $zero
/* D4238 800D3638 00000000 */  nop
/* D423C 800D363C 00000000 */  nop
