.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel __osGetSR
/* D5200 800D4600 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
/* D5204 800D4604 03E00008 */  jr         $ra
/* D5208 800D4608 00000000 */   nop
/* D520C 800D460C 00000000 */  nop
