.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel osInvalDCache
/* D2480 800D1880 18A0001F */  blez       $a1, .L800D1900_D2500
/* D2484 800D1884 00000000 */   nop
/* D2488 800D1888 240B2000 */  addiu      $t3, $zero, 0x2000
/* D248C 800D188C 00AB082B */  sltu       $at, $a1, $t3
/* D2490 800D1890 1020001D */  beqz       $at, .L800D1908_D2508
/* D2494 800D1894 00000000 */   nop
/* D2498 800D1898 00804025 */  or         $t0, $a0, $zero
/* D249C 800D189C 00854821 */  addu       $t1, $a0, $a1
/* D24A0 800D18A0 0109082B */  sltu       $at, $t0, $t1
/* D24A4 800D18A4 10200016 */  beqz       $at, .L800D1900_D2500
/* D24A8 800D18A8 00000000 */   nop
/* D24AC 800D18AC 310A000F */  andi       $t2, $t0, 0xF
/* D24B0 800D18B0 11400007 */  beqz       $t2, .L800D18D0_D24D0
/* D24B4 800D18B4 2529FFF0 */   addiu     $t1, $t1, -0x10
/* D24B8 800D18B8 010A4023 */  subu       $t0, $t0, $t2
/* D24BC 800D18BC BD150000 */  cache      0x15, 0x0($t0) /* handwritten instruction */
/* D24C0 800D18C0 0109082B */  sltu       $at, $t0, $t1
/* D24C4 800D18C4 1020000E */  beqz       $at, .L800D1900_D2500
/* D24C8 800D18C8 00000000 */   nop
/* D24CC 800D18CC 25080010 */  addiu      $t0, $t0, 0x10
.L800D18D0_D24D0:
/* D24D0 800D18D0 312A000F */  andi       $t2, $t1, 0xF
/* D24D4 800D18D4 11400006 */  beqz       $t2, .L800D18F0_D24F0
/* D24D8 800D18D8 00000000 */   nop
/* D24DC 800D18DC 012A4823 */  subu       $t1, $t1, $t2
/* D24E0 800D18E0 BD350010 */  cache      0x15, 0x10($t1) /* handwritten instruction */
/* D24E4 800D18E4 0128082B */  sltu       $at, $t1, $t0
/* D24E8 800D18E8 14200005 */  bnez       $at, .L800D1900_D2500
/* D24EC 800D18EC 00000000 */   nop
.L800D18F0_D24F0:
/* D24F0 800D18F0 BD110000 */  cache      0x11, 0x0($t0) /* handwritten instruction */
/* D24F4 800D18F4 0109082B */  sltu       $at, $t0, $t1
/* D24F8 800D18F8 1420FFFD */  bnez       $at, .L800D18F0_D24F0
/* D24FC 800D18FC 25080010 */   addiu     $t0, $t0, 0x10
.L800D1900_D2500:
/* D2500 800D1900 03E00008 */  jr         $ra
/* D2504 800D1904 00000000 */   nop
.L800D1908_D2508:
/* D2508 800D1908 3C088000 */  lui        $t0, 0x8000
/* D250C 800D190C 010B4821 */  addu       $t1, $t0, $t3
/* D2510 800D1910 2529FFF0 */  addiu      $t1, $t1, -0x10
.L800D1914_D2514:
/* D2514 800D1914 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
/* D2518 800D1918 0109082B */  sltu       $at, $t0, $t1
/* D251C 800D191C 1420FFFD */  bnez       $at, .L800D1914_D2514
/* D2520 800D1920 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
/* D2524 800D1924 03E00008 */  jr         $ra
/* D2528 800D1928 00000000 */   nop
/* D252C 800D192C 00000000 */  nop
