.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel func_800D4740
/* D5340 800D4740 18A00011 */  blez       $a1, .L800D4788
/* D5344 800D4744 00000000 */   nop
/* D5348 800D4748 240B4000 */  addiu      $t3, $zero, 0x4000
/* D534C 800D474C 00AB082B */  sltu       $at, $a1, $t3
/* D5350 800D4750 1020000F */  beqz       $at, .L800D4790
/* D5354 800D4754 00000000 */   nop
/* D5358 800D4758 00804025 */  or         $t0, $a0, $zero
/* D535C 800D475C 00854821 */  addu       $t1, $a0, $a1
/* D5360 800D4760 0109082B */  sltu       $at, $t0, $t1
/* D5364 800D4764 10200008 */  beqz       $at, .L800D4788
/* D5368 800D4768 00000000 */   nop
/* D536C 800D476C 310A001F */  andi       $t2, $t0, 0x1F
/* D5370 800D4770 2529FFE0 */  addiu      $t1, $t1, -0x20
/* D5374 800D4774 010A4023 */  subu       $t0, $t0, $t2
.L800D4778:
/* D5378 800D4778 BD100000 */  cache      0x10, 0x0($t0) /* handwritten instruction */
/* D537C 800D477C 0109082B */  sltu       $at, $t0, $t1
/* D5380 800D4780 1420FFFD */  bnez       $at, .L800D4778
/* D5384 800D4784 25080020 */   addiu     $t0, $t0, 0x20
.L800D4788:
/* D5388 800D4788 03E00008 */  jr         $ra
/* D538C 800D478C 00000000 */   nop
.L800D4790:
/* D5390 800D4790 3C088000 */  lui        $t0, 0x8000
/* D5394 800D4794 010B4821 */  addu       $t1, $t0, $t3
/* D5398 800D4798 2529FFE0 */  addiu      $t1, $t1, -0x20
.L800D479C:
/* D539C 800D479C BD000000 */  cache      0x00, 0x0($t0) /* handwritten instruction */
/* D53A0 800D47A0 0109082B */  sltu       $at, $t0, $t1
/* D53A4 800D47A4 1420FFFD */  bnez       $at, .L800D479C
/* D53A8 800D47A8 25080020 */   addiu     $t0, $t0, (0x80000020 & 0xFFFF)
/* D53AC 800D47AC 03E00008 */  jr         $ra
/* D53B0 800D47B0 00000000 */   nop
/* D53B4 800D47B4 00000000 */  nop
/* D53B8 800D47B8 00000000 */  nop
/* D53BC 800D47BC 00000000 */  nop
