.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel osMapTLBRdb
/* D53C0 800D47C0 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
/* D53C4 800D47C4 2409001F */  addiu      $t1, $zero, 0x1F
/* D53C8 800D47C8 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
/* D53CC 800D47CC 40802800 */  mtc0       $zero, $5 /* handwritten instruction */
/* D53D0 800D47D0 240A0017 */  addiu      $t2, $zero, 0x17
/* D53D4 800D47D4 3C09C000 */  lui        $t1, (0xC0000000 >> 16)
/* D53D8 800D47D8 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
/* D53DC 800D47DC 3C098000 */  lui        $t1, (0x80000000 >> 16)
/* D53E0 800D47E0 00095982 */  srl        $t3, $t1, 6
/* D53E4 800D47E4 016A5825 */  or         $t3, $t3, $t2
/* D53E8 800D47E8 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
/* D53EC 800D47EC 24090001 */  addiu      $t1, $zero, 0x1
/* D53F0 800D47F0 40891800 */  mtc0       $t1, $3 /* handwritten instruction */
/* D53F4 800D47F4 00000000 */  nop
/* D53F8 800D47F8 42000002 */  tlbwi /* handwritten instruction */
/* D53FC 800D47FC 00000000 */  nop
/* D5400 800D4800 00000000 */  nop
/* D5404 800D4804 00000000 */  nop
/* D5408 800D4808 00000000 */  nop
/* D540C 800D480C 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
/* D5410 800D4810 03E00008 */  jr         $ra
/* D5414 800D4814 00000000 */   nop
/* D5418 800D4818 00000000 */  nop
/* D541C 800D481C 00000000 */  nop
