.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel osSetIntMask
/* CA6C0 800C9AC0 400C6000 */  mfc0       $t4, $12 /* handwritten instruction */
/* CA6C4 800C9AC4 3182FF01 */  andi       $v0, $t4, 0xFF01
/* CA6C8 800C9AC8 3C08800E */  lui        $t0, %hi(__OSGlobalIntMask)
/* CA6CC 800C9ACC 2508393C */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
/* CA6D0 800C9AD0 8D0B0000 */  lw         $t3, 0x0($t0)
/* CA6D4 800C9AD4 2401FFFF */  addiu      $at, $zero, -0x1
/* CA6D8 800C9AD8 01614026 */  xor        $t0, $t3, $at
/* CA6DC 800C9ADC 3108FF00 */  andi       $t0, $t0, 0xFF00
/* CA6E0 800C9AE0 00481025 */  or         $v0, $v0, $t0
/* CA6E4 800C9AE4 3C0AA430 */  lui        $t2, %hi(MI_INTR_MASK_REG)
/* CA6E8 800C9AE8 8D4A000C */  lw         $t2, %lo(MI_INTR_MASK_REG)($t2)
/* CA6EC 800C9AEC 11400005 */  beqz       $t2, .L800C9B04_CA704
/* CA6F0 800C9AF0 000B4C02 */   srl       $t1, $t3, 16
/* CA6F4 800C9AF4 2401FFFF */  addiu      $at, $zero, -0x1
/* CA6F8 800C9AF8 01214826 */  xor        $t1, $t1, $at
/* CA6FC 800C9AFC 3129003F */  andi       $t1, $t1, 0x3F
/* CA700 800C9B00 01495025 */  or         $t2, $t2, $t1
.L800C9B04_CA704:
/* CA704 800C9B04 000A5400 */  sll        $t2, $t2, 16
/* CA708 800C9B08 004A1025 */  or         $v0, $v0, $t2
/* CA70C 800C9B0C 3C01003F */  lui        $at, (0x3F0000 >> 16)
/* CA710 800C9B10 00814024 */  and        $t0, $a0, $at
/* CA714 800C9B14 010B4024 */  and        $t0, $t0, $t3
/* CA718 800C9B18 000843C2 */  srl        $t0, $t0, 15
/* CA71C 800C9B1C 3C0A800F */  lui        $t2, %hi(__osRcpImTable)
/* CA720 800C9B20 01485021 */  addu       $t2, $t2, $t0
/* CA724 800C9B24 954A9560 */  lhu        $t2, %lo(__osRcpImTable)($t2)
/* CA728 800C9B28 3C01A430 */  lui        $at, %hi(MI_INTR_MASK_REG)
/* CA72C 800C9B2C AC2A000C */  sw         $t2, %lo(MI_INTR_MASK_REG)($at)
/* CA730 800C9B30 3088FF01 */  andi       $t0, $a0, 0xFF01
/* CA734 800C9B34 3169FF00 */  andi       $t1, $t3, 0xFF00
/* CA738 800C9B38 01094024 */  and        $t0, $t0, $t1
/* CA73C 800C9B3C 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
/* CA740 800C9B40 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
/* CA744 800C9B44 01816024 */  and        $t4, $t4, $at
/* CA748 800C9B48 01886025 */  or         $t4, $t4, $t0
/* CA74C 800C9B4C 408C6000 */  mtc0       $t4, $12 /* handwritten instruction */
/* CA750 800C9B50 00000000 */  nop
/* CA754 800C9B54 00000000 */  nop
/* CA758 800C9B58 03E00008 */  jr         $ra
/* CA75C 800C9B5C 00000000 */   nop
