.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel __osSetSR
/* D51F0 800D45F0 40846000 */  mtc0       $a0, $12 /* handwritten instruction */
/* D51F4 800D45F4 00000000 */  nop
/* D51F8 800D45F8 03E00008 */  jr         $ra
/* D51FC 800D45FC 00000000 */   nop
