.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel osWritebackDCacheAll
/* D2530 800D1930 3C088000 */  lui        $t0, 0x8000
/* D2534 800D1934 240A2000 */  addiu      $t2, $zero, 0x2000
/* D2538 800D1938 010A4821 */  addu       $t1, $t0, $t2
/* D253C 800D193C 2529FFF0 */  addiu      $t1, $t1, -0x10
.L800D1940_D2540:
/* D2540 800D1940 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
/* D2544 800D1944 0109082B */  sltu       $at, $t0, $t1
/* D2548 800D1948 1420FFFD */  bnez       $at, .L800D1940_D2540
/* D254C 800D194C 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
/* D2550 800D1950 03E00008 */  jr         $ra
/* D2554 800D1954 00000000 */   nop
/* D2558 800D1958 00000000 */  nop
/* D255C 800D195C 00000000 */  nop
