.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel func_800D46C0
/* D52C0 800D46C0 18A00011 */  blez       $a1, .L800D4708
/* D52C4 800D46C4 00000000 */   nop
/* D52C8 800D46C8 240B2000 */  addiu      $t3, $zero, 0x2000
/* D52CC 800D46CC 00AB082B */  sltu       $at, $a1, $t3
/* D52D0 800D46D0 1020000F */  beqz       $at, .L800D4710
/* D52D4 800D46D4 00000000 */   nop
/* D52D8 800D46D8 00804025 */  or         $t0, $a0, $zero
/* D52DC 800D46DC 00854821 */  addu       $t1, $a0, $a1
/* D52E0 800D46E0 0109082B */  sltu       $at, $t0, $t1
/* D52E4 800D46E4 10200008 */  beqz       $at, .L800D4708
/* D52E8 800D46E8 00000000 */   nop
/* D52EC 800D46EC 310A000F */  andi       $t2, $t0, 0xF
/* D52F0 800D46F0 2529FFF0 */  addiu      $t1, $t1, -0x10
/* D52F4 800D46F4 010A4023 */  subu       $t0, $t0, $t2
.L800D46F8:
/* D52F8 800D46F8 BD190000 */  cache      0x19, 0x0($t0) /* handwritten instruction */
/* D52FC 800D46FC 0109082B */  sltu       $at, $t0, $t1
/* D5300 800D4700 1420FFFD */  bnez       $at, .L800D46F8
/* D5304 800D4704 25080010 */   addiu     $t0, $t0, 0x10
.L800D4708:
/* D5308 800D4708 03E00008 */  jr         $ra
/* D530C 800D470C 00000000 */   nop
.L800D4710:
/* D5310 800D4710 3C088000 */  lui        $t0, 0x8000
/* D5314 800D4714 010B4821 */  addu       $t1, $t0, $t3
/* D5318 800D4718 2529FFF0 */  addiu      $t1, $t1, -0x10
.L800D471C:
/* D531C 800D471C BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
/* D5320 800D4720 0109082B */  sltu       $at, $t0, $t1
/* D5324 800D4724 1420FFFD */  bnez       $at, .L800D471C
/* D5328 800D4728 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
/* D532C 800D472C 03E00008 */  jr         $ra
/* D5330 800D4730 00000000 */   nop
/* D5334 800D4734 00000000 */  nop
/* D5338 800D4738 00000000 */  nop
/* D533C 800D473C 00000000 */  nop
