.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

glabel get_stack_pointer
/* B8910 800B7D10 03E00008 */  jr         $ra
/* B8914 800B7D14 03A01025 */   or        $v0, $sp, $zero
/* B8918 800B7D18 00000000 */  nop
/* B891C 800B7D1C 00000000 */  nop
