.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

glabel get_stack_pointer
/* B8E30 800B8230 03E00008 */  jr         $ra
/* B8E34 800B8234 03A01025 */   or        $v0, $sp, $zero
/* B8E38 800B8238 00000000 */  nop
/* B8E3C 800B823C 00000000 */  nop
