.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .rodata

glabel gzip_border
.byte 16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15

glabel gzip_cplens
.half 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 23, 27, 31, 35, 43, 51, 59, 67, 83, 99, 115, 131, 163, 195, 227, 258, 0, 0

glabel gzip_cplext
.byte 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0, 99, 99

glabel gzip_cpdist
.half 1, 2, 3, 4, 5, 7, 9, 13, 17, 25, 33, 49, 65, 97, 129, 193, 257, 385, 513, 769, 1025, 1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577

glabel gzip_cpdext
.byte 0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13

glabel gzip_mask_bits
.half 0x0000, 0x0001, 0x0003, 0x0007, 0x000f, 0x001f, 0x003f, 0x007f, 0x00ff, 0x01ff, 0x03ff, 0x07ff, 0x0fff, 0x1fff, 0x3fff, 0x7fff, 0xffff


.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel gzip_inflate_block
/* C7A20 800C6E20 3C0B8013 */  lui        $t3, %hi(gzip_num_bits)
/* C7A24 800C6E24 8D6BB094 */  lw         $t3, %lo(gzip_num_bits)($t3)
/* C7A28 800C6E28 3C018013 */  lui        $at, %hi(gHuftTablePos)
/* C7A2C 800C6E2C AC20B098 */  sw         $zero, %lo(gHuftTablePos)($at)
/* C7A30 800C6E30 24080001 */  addiu      $t0, $zero, 0x1
/* C7A34 800C6E34 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* C7A38 800C6E38 3C0C800E */  lui        $t4, %hi(gzip_inflate_input)
/* C7A3C 800C6E3C 3C0A8013 */  lui        $t2, %hi(gzip_bit_buffer)
/* C7A40 800C6E40 0168082B */  sltu       $at, $t3, $t0
/* C7A44 800C6E44 AFBF001C */  sw         $ra, 0x1C($sp)
/* C7A48 800C6E48 AFB00018 */  sw         $s0, 0x18($sp)
/* C7A4C 800C6E4C 8D8C3CF8 */  lw         $t4, %lo(gzip_inflate_input)($t4)
/* C7A50 800C6E50 10200008 */  beqz       $at, .L800C6E74_C7A74
/* C7A54 800C6E54 8D4AB090 */   lw        $t2, %lo(gzip_bit_buffer)($t2)
.L800C6E58_C7A58:
/* C7A58 800C6E58 91820000 */  lbu        $v0, 0x0($t4)
/* C7A5C 800C6E5C 258C0001 */  addiu      $t4, $t4, 0x1
/* C7A60 800C6E60 01621004 */  sllv       $v0, $v0, $t3
/* C7A64 800C6E64 256B0008 */  addiu      $t3, $t3, 0x8
/* C7A68 800C6E68 0168082A */  slt        $at, $t3, $t0
/* C7A6C 800C6E6C 1420FFFA */  bnez       $at, .L800C6E58_C7A58
/* C7A70 800C6E70 01425025 */   or        $t2, $t2, $v0
.L800C6E74_C7A74:
/* C7A74 800C6E74 31500001 */  andi       $s0, $t2, 0x1
/* C7A78 800C6E78 010A5006 */  srlv       $t2, $t2, $t0
/* C7A7C 800C6E7C 01685822 */  sub        $t3, $t3, $t0 /* handwritten instruction */
/* C7A80 800C6E80 24080002 */  addiu      $t0, $zero, 0x2
/* C7A84 800C6E84 0168082B */  sltu       $at, $t3, $t0
/* C7A88 800C6E88 10200008 */  beqz       $at, .L800C6EAC_C7AAC
/* C7A8C 800C6E8C 00000000 */   nop
.L800C6E90_C7A90:
/* C7A90 800C6E90 91820000 */  lbu        $v0, 0x0($t4)
/* C7A94 800C6E94 258C0001 */  addiu      $t4, $t4, 0x1
/* C7A98 800C6E98 01621004 */  sllv       $v0, $v0, $t3
/* C7A9C 800C6E9C 256B0008 */  addiu      $t3, $t3, 0x8
/* C7AA0 800C6EA0 0168082A */  slt        $at, $t3, $t0
/* C7AA4 800C6EA4 1420FFFA */  bnez       $at, .L800C6E90_C7A90
/* C7AA8 800C6EA8 01425025 */   or        $t2, $t2, $v0
.L800C6EAC_C7AAC:
/* C7AAC 800C6EAC 3C01800E */  lui        $at, %hi(gzip_inflate_input)
/* C7AB0 800C6EB0 31490003 */  andi       $t1, $t2, 0x3
/* C7AB4 800C6EB4 AC2C3CF8 */  sw         $t4, %lo(gzip_inflate_input)($at)
/* C7AB8 800C6EB8 010A5006 */  srlv       $t2, $t2, $t0
/* C7ABC 800C6EBC 3C018013 */  lui        $at, %hi(gzip_bit_buffer)
/* C7AC0 800C6EC0 AC2AB090 */  sw         $t2, %lo(gzip_bit_buffer)($at)
/* C7AC4 800C6EC4 01685822 */  sub        $t3, $t3, $t0 /* handwritten instruction */
/* C7AC8 800C6EC8 3C018013 */  lui        $at, %hi(gzip_num_bits)
/* C7ACC 800C6ECC AC2BB094 */  sw         $t3, %lo(gzip_num_bits)($at)
/* C7AD0 800C6ED0 24010002 */  addiu      $at, $zero, 0x2
/* C7AD4 800C6ED4 1121000B */  beq        $t1, $at, .L800C6F04_C7B04
/* C7AD8 800C6ED8 24010001 */   addiu     $at, $zero, 0x1
/* C7ADC 800C6EDC 11210005 */  beq        $t1, $at, .L800C6EF4_C7AF4
/* C7AE0 800C6EE0 00000000 */   nop
/* C7AE4 800C6EE4 0C031D25 */  jal        gzip_inflate_stored
/* C7AE8 800C6EE8 00000000 */   nop
/* C7AEC 800C6EEC 08031BC3 */  j          .L800C6F0C_C7B0C
/* C7AF0 800C6EF0 00000000 */   nop
.L800C6EF4_C7AF4:
/* C7AF4 800C6EF4 0C031CCF */  jal        gzip_inflate_fixed
/* C7AF8 800C6EF8 00000000 */   nop
/* C7AFC 800C6EFC 08031BC3 */  j          .L800C6F0C_C7B0C
/* C7B00 800C6F00 00000000 */   nop
.L800C6F04_C7B04:
/* C7B04 800C6F04 0C031BC9 */  jal        gzip_inflate_dynamic
/* C7B08 800C6F08 00000000 */   nop
.L800C6F0C_C7B0C:
/* C7B0C 800C6F0C 8FBF001C */  lw         $ra, 0x1C($sp)
/* C7B10 800C6F10 24020001 */  addiu      $v0, $zero, 0x1
/* C7B14 800C6F14 00501022 */  sub        $v0, $v0, $s0 /* handwritten instruction */
/* C7B18 800C6F18 8FB00018 */  lw         $s0, 0x18($sp)
/* C7B1C 800C6F1C 03E00008 */  jr         $ra
/* C7B20 800C6F20 27BD0020 */   addiu     $sp, $sp, 0x20

/* Handwritten function */
glabel gzip_inflate_dynamic
/* C7B24 800C6F24 27BDFAC0 */  addiu      $sp, $sp, -0x540
/* C7B28 800C6F28 AFB30028 */  sw         $s3, 0x28($sp)
/* C7B2C 800C6F2C 3C138013 */  lui        $s3, %hi(gzip_num_bits)
/* C7B30 800C6F30 8E73B094 */  lw         $s3, %lo(gzip_num_bits)($s3)
/* C7B34 800C6F34 AFB4002C */  sw         $s4, 0x2C($sp)
/* C7B38 800C6F38 AFB20024 */  sw         $s2, 0x24($sp)
/* C7B3C 800C6F3C 24080005 */  addiu      $t0, $zero, 0x5
/* C7B40 800C6F40 3C14800E */  lui        $s4, %hi(gzip_inflate_input)
/* C7B44 800C6F44 3C128013 */  lui        $s2, %hi(gzip_bit_buffer)
/* C7B48 800C6F48 0268082B */  sltu       $at, $s3, $t0
/* C7B4C 800C6F4C AFBF0030 */  sw         $ra, 0x30($sp)
/* C7B50 800C6F50 AFB10020 */  sw         $s1, 0x20($sp)
/* C7B54 800C6F54 AFB0001C */  sw         $s0, 0x1C($sp)
/* C7B58 800C6F58 8E943CF8 */  lw         $s4, %lo(gzip_inflate_input)($s4)
/* C7B5C 800C6F5C 10200008 */  beqz       $at, .L800C6F80_C7B80
/* C7B60 800C6F60 8E52B090 */   lw        $s2, %lo(gzip_bit_buffer)($s2)
.L800C6F64_C7B64:
/* C7B64 800C6F64 92820000 */  lbu        $v0, 0x0($s4)
/* C7B68 800C6F68 26940001 */  addiu      $s4, $s4, 0x1
/* C7B6C 800C6F6C 02621004 */  sllv       $v0, $v0, $s3
/* C7B70 800C6F70 26730008 */  addiu      $s3, $s3, 0x8
/* C7B74 800C6F74 0268082A */  slt        $at, $s3, $t0
/* C7B78 800C6F78 1420FFFA */  bnez       $at, .L800C6F64_C7B64
/* C7B7C 800C6F7C 02429025 */   or        $s2, $s2, $v0
.L800C6F80_C7B80:
/* C7B80 800C6F80 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7B84 800C6F84 3251001F */  andi       $s1, $s2, 0x1F
/* C7B88 800C6F88 0268082B */  sltu       $at, $s3, $t0
/* C7B8C 800C6F8C 26310101 */  addiu      $s1, $s1, 0x101
/* C7B90 800C6F90 10200008 */  beqz       $at, .L800C6FB4_C7BB4
/* C7B94 800C6F94 01129006 */   srlv      $s2, $s2, $t0
.L800C6F98_C7B98:
/* C7B98 800C6F98 92820000 */  lbu        $v0, 0x0($s4)
/* C7B9C 800C6F9C 26940001 */  addiu      $s4, $s4, 0x1
/* C7BA0 800C6FA0 02621004 */  sllv       $v0, $v0, $s3
/* C7BA4 800C6FA4 26730008 */  addiu      $s3, $s3, 0x8
/* C7BA8 800C6FA8 0268082A */  slt        $at, $s3, $t0
/* C7BAC 800C6FAC 1420FFFA */  bnez       $at, .L800C6F98_C7B98
/* C7BB0 800C6FB0 02429025 */   or        $s2, $s2, $v0
.L800C6FB4_C7BB4:
/* C7BB4 800C6FB4 3250001F */  andi       $s0, $s2, 0x1F
/* C7BB8 800C6FB8 01129006 */  srlv       $s2, $s2, $t0
/* C7BBC 800C6FBC 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7BC0 800C6FC0 24080004 */  addiu      $t0, $zero, 0x4
/* C7BC4 800C6FC4 0268082B */  sltu       $at, $s3, $t0
/* C7BC8 800C6FC8 10200008 */  beqz       $at, .L800C6FEC_C7BEC
/* C7BCC 800C6FCC 26100001 */   addiu     $s0, $s0, 0x1
.L800C6FD0_C7BD0:
/* C7BD0 800C6FD0 92820000 */  lbu        $v0, 0x0($s4)
/* C7BD4 800C6FD4 26940001 */  addiu      $s4, $s4, 0x1
/* C7BD8 800C6FD8 02621004 */  sllv       $v0, $v0, $s3
/* C7BDC 800C6FDC 26730008 */  addiu      $s3, $s3, 0x8
/* C7BE0 800C6FE0 0268082A */  slt        $at, $s3, $t0
/* C7BE4 800C6FE4 1420FFFA */  bnez       $at, .L800C6FD0_C7BD0
/* C7BE8 800C6FE8 02429025 */   or        $s2, $s2, $v0
.L800C6FEC_C7BEC:
/* C7BEC 800C6FEC 324A000F */  andi       $t2, $s2, 0xF
/* C7BF0 800C6FF0 254A0004 */  addiu      $t2, $t2, 0x4
/* C7BF4 800C6FF4 3C19800F */  lui        $t9, %hi(gzip_border)
/* C7BF8 800C6FF8 01129006 */  srlv       $s2, $s2, $t0
/* C7BFC 800C6FFC 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7C00 800C7000 000A4825 */  or         $t1, $zero, $t2
/* C7C04 800C7004 27399940 */  addiu      $t9, $t9, %lo(gzip_border)
/* C7C08 800C7008 11400019 */  beqz       $t2, .L800C7070_C7C70
/* C7C0C 800C700C 23AF0044 */   addi      $t7, $sp, 0x44 /* handwritten instruction */
.L800C7010_C7C10:
/* C7C10 800C7010 24080003 */  addiu      $t0, $zero, 0x3
/* C7C14 800C7014 0268082B */  sltu       $at, $s3, $t0
/* C7C18 800C7018 50200009 */  beql       $at, $zero, .L800C7040_C7C40
/* C7C1C 800C701C 93230000 */   lbu       $v1, 0x0($t9)
.L800C7020_C7C20:
/* C7C20 800C7020 92820000 */  lbu        $v0, 0x0($s4)
/* C7C24 800C7024 26940001 */  addiu      $s4, $s4, 0x1
/* C7C28 800C7028 02621004 */  sllv       $v0, $v0, $s3
/* C7C2C 800C702C 26730008 */  addiu      $s3, $s3, 0x8
/* C7C30 800C7030 0268082A */  slt        $at, $s3, $t0
/* C7C34 800C7034 1420FFFA */  bnez       $at, .L800C7020_C7C20
/* C7C38 800C7038 02429025 */   or        $s2, $s2, $v0
/* C7C3C 800C703C 93230000 */  lbu        $v1, 0x0($t9)
.L800C7040_C7C40:
/* C7C40 800C7040 32420007 */  andi       $v0, $s2, 0x7
/* C7C44 800C7044 254AFFFF */  addiu      $t2, $t2, -0x1
/* C7C48 800C7048 00031880 */  sll        $v1, $v1, 2
/* C7C4C 800C704C 006F1821 */  addu       $v1, $v1, $t7
/* C7C50 800C7050 AC620000 */  sw         $v0, 0x0($v1)
/* C7C54 800C7054 01129006 */  srlv       $s2, $s2, $t0
/* C7C58 800C7058 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7C5C 800C705C 1540FFEC */  bnez       $t2, .L800C7010_C7C10
/* C7C60 800C7060 27390001 */   addiu     $t9, $t9, 0x1
/* C7C64 800C7064 2D210013 */  sltiu      $at, $t1, 0x13
/* C7C68 800C7068 5020000A */  beql       $at, $zero, .L800C7094_C7C94
/* C7C6C 800C706C 240D0007 */   addiu     $t5, $zero, 0x7
.L800C7070_C7C70:
/* C7C70 800C7070 93230000 */  lbu        $v1, 0x0($t9)
/* C7C74 800C7074 25290001 */  addiu      $t1, $t1, 0x1
/* C7C78 800C7078 29210013 */  slti       $at, $t1, 0x13
/* C7C7C 800C707C 00031880 */  sll        $v1, $v1, 2
/* C7C80 800C7080 006F1821 */  addu       $v1, $v1, $t7
/* C7C84 800C7084 AC600000 */  sw         $zero, 0x0($v1)
/* C7C88 800C7088 1420FFF9 */  bnez       $at, .L800C7070_C7C70
/* C7C8C 800C708C 27390001 */   addiu     $t9, $t9, 0x1
/* C7C90 800C7090 240D0007 */  addiu      $t5, $zero, 0x7
.L800C7094_C7C94:
/* C7C94 800C7094 23A80034 */  addi       $t0, $sp, 0x34 /* handwritten instruction */
/* C7C98 800C7098 23A90038 */  addi       $t1, $sp, 0x38 /* handwritten instruction */
/* C7C9C 800C709C AFAD0038 */  sw         $t5, 0x38($sp)
/* C7CA0 800C70A0 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C7CA4 800C70A4 24050013 */  addiu      $a1, $zero, 0x13
/* C7CA8 800C70A8 24060013 */  addiu      $a2, $zero, 0x13
/* C7CAC 800C70AC 24070000 */  addiu      $a3, $zero, 0x0
/* C7CB0 800C70B0 AFA00010 */  sw         $zero, 0x10($sp)
/* C7CB4 800C70B4 AFA80014 */  sw         $t0, 0x14($sp)
/* C7CB8 800C70B8 0C0319F5 */  jal        gzip_huft_build
/* C7CBC 800C70BC AFA90018 */   sw        $t1, 0x18($sp)
/* C7CC0 800C70C0 23A90038 */  addi       $t1, $sp, 0x38 /* handwritten instruction */
/* C7CC4 800C70C4 8D2D0000 */  lw         $t5, 0x0($t1)
/* C7CC8 800C70C8 3C02800F */  lui        $v0, %hi(gzip_mask_bits)
/* C7CCC 800C70CC 24429A0C */  addiu      $v0, $v0, %lo(gzip_mask_bits)
/* C7CD0 800C70D0 000D1840 */  sll        $v1, $t5, 1
/* C7CD4 800C70D4 23A80034 */  addi       $t0, $sp, 0x34 /* handwritten instruction */
/* C7CD8 800C70D8 00431020 */  add        $v0, $v0, $v1 /* handwritten instruction */
/* C7CDC 800C70DC 8D0E0000 */  lw         $t6, 0x0($t0)
/* C7CE0 800C70E0 0230C820 */  add        $t9, $s1, $s0 /* handwritten instruction */
/* C7CE4 800C70E4 84580000 */  lh         $t8, 0x0($v0)
/* C7CE8 800C70E8 23AF0044 */  addi       $t7, $sp, 0x44 /* handwritten instruction */
/* C7CEC 800C70EC 240A0000 */  addiu      $t2, $zero, 0x0
.L800C70F0_C7CF0:
/* C7CF0 800C70F0 1320005F */  beqz       $t9, .L800C7270_C7E70
/* C7CF4 800C70F4 026D082B */   sltu      $at, $s3, $t5
/* C7CF8 800C70F8 50200009 */  beql       $at, $zero, .L800C7120_C7D20
/* C7CFC 800C70FC 02581024 */   and       $v0, $s2, $t8
.L800C7100_C7D00:
/* C7D00 800C7100 92820000 */  lbu        $v0, 0x0($s4)
/* C7D04 800C7104 26940001 */  addiu      $s4, $s4, 0x1
/* C7D08 800C7108 02621004 */  sllv       $v0, $v0, $s3
/* C7D0C 800C710C 26730008 */  addiu      $s3, $s3, 0x8
/* C7D10 800C7110 026D082A */  slt        $at, $s3, $t5
/* C7D14 800C7114 1420FFFA */  bnez       $at, .L800C7100_C7D00
/* C7D18 800C7118 02429025 */   or        $s2, $s2, $v0
/* C7D1C 800C711C 02581024 */  and        $v0, $s2, $t8
.L800C7120_C7D20:
/* C7D20 800C7120 000210C0 */  sll        $v0, $v0, 3
/* C7D24 800C7124 01C24821 */  addu       $t1, $t6, $v0
/* C7D28 800C7128 95280004 */  lhu        $t0, 0x4($t1)
/* C7D2C 800C712C 91220001 */  lbu        $v0, 0x1($t1)
/* C7D30 800C7130 29010010 */  slti       $at, $t0, 0x10
/* C7D34 800C7134 00529006 */  srlv       $s2, $s2, $v0
/* C7D38 800C7138 1420001C */  bnez       $at, .L800C71AC_C7DAC
/* C7D3C 800C713C 02629822 */   sub       $s3, $s3, $v0 /* handwritten instruction */
/* C7D40 800C7140 24010010 */  addiu      $at, $zero, 0x10
/* C7D44 800C7144 1101001E */  beq        $t0, $at, .L800C71C0_C7DC0
/* C7D48 800C7148 24010011 */   addiu     $at, $zero, 0x11
/* C7D4C 800C714C 51010033 */  beql       $t0, $at, .L800C721C_C7E1C
/* C7D50 800C7150 24080003 */   addiu     $t0, $zero, 0x3
/* C7D54 800C7154 24080007 */  addiu      $t0, $zero, 0x7
/* C7D58 800C7158 0268082B */  sltu       $at, $s3, $t0
/* C7D5C 800C715C 50200009 */  beql       $at, $zero, .L800C7184_C7D84
/* C7D60 800C7160 3249007F */   andi      $t1, $s2, 0x7F
.L800C7164_C7D64:
/* C7D64 800C7164 92820000 */  lbu        $v0, 0x0($s4)
/* C7D68 800C7168 26940001 */  addiu      $s4, $s4, 0x1
/* C7D6C 800C716C 02621004 */  sllv       $v0, $v0, $s3
/* C7D70 800C7170 26730008 */  addiu      $s3, $s3, 0x8
/* C7D74 800C7174 0268082A */  slt        $at, $s3, $t0
/* C7D78 800C7178 1420FFFA */  bnez       $at, .L800C7164_C7D64
/* C7D7C 800C717C 02429025 */   or        $s2, $s2, $v0
/* C7D80 800C7180 3249007F */  andi       $t1, $s2, 0x7F
.L800C7184_C7D84:
/* C7D84 800C7184 2529000B */  addiu      $t1, $t1, 0xB
/* C7D88 800C7188 01129006 */  srlv       $s2, $s2, $t0
/* C7D8C 800C718C 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7D90 800C7190 0329C823 */  subu       $t9, $t9, $t1
.L800C7194_C7D94:
/* C7D94 800C7194 2529FFFF */  addiu      $t1, $t1, -0x1
/* C7D98 800C7198 ADE00000 */  sw         $zero, 0x0($t7)
/* C7D9C 800C719C 1520FFFD */  bnez       $t1, .L800C7194_C7D94
/* C7DA0 800C71A0 25EF0004 */   addiu     $t7, $t7, 0x4
/* C7DA4 800C71A4 08031C3C */  j          .L800C70F0_C7CF0
/* C7DA8 800C71A8 240A0000 */   addiu     $t2, $zero, 0x0
.L800C71AC_C7DAC:
/* C7DAC 800C71AC ADE80000 */  sw         $t0, 0x0($t7)
/* C7DB0 800C71B0 25EF0004 */  addiu      $t7, $t7, 0x4
/* C7DB4 800C71B4 2739FFFF */  addiu      $t9, $t9, -0x1
/* C7DB8 800C71B8 08031C3C */  j          .L800C70F0_C7CF0
/* C7DBC 800C71BC 00085025 */   or        $t2, $zero, $t0
.L800C71C0_C7DC0:
/* C7DC0 800C71C0 24080002 */  addiu      $t0, $zero, 0x2
/* C7DC4 800C71C4 0268082B */  sltu       $at, $s3, $t0
/* C7DC8 800C71C8 50200009 */  beql       $at, $zero, .L800C71F0_C7DF0
/* C7DCC 800C71CC 32490003 */   andi      $t1, $s2, 0x3
.L800C71D0_C7DD0:
/* C7DD0 800C71D0 92820000 */  lbu        $v0, 0x0($s4)
/* C7DD4 800C71D4 26940001 */  addiu      $s4, $s4, 0x1
/* C7DD8 800C71D8 02621004 */  sllv       $v0, $v0, $s3
/* C7DDC 800C71DC 26730008 */  addiu      $s3, $s3, 0x8
/* C7DE0 800C71E0 0268082A */  slt        $at, $s3, $t0
/* C7DE4 800C71E4 1420FFFA */  bnez       $at, .L800C71D0_C7DD0
/* C7DE8 800C71E8 02429025 */   or        $s2, $s2, $v0
/* C7DEC 800C71EC 32490003 */  andi       $t1, $s2, 0x3
.L800C71F0_C7DF0:
/* C7DF0 800C71F0 21290003 */  addi       $t1, $t1, 0x3 /* handwritten instruction */
/* C7DF4 800C71F4 01129006 */  srlv       $s2, $s2, $t0
/* C7DF8 800C71F8 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7DFC 800C71FC 0329C823 */  subu       $t9, $t9, $t1
.L800C7200_C7E00:
/* C7E00 800C7200 2529FFFF */  addiu      $t1, $t1, -0x1
/* C7E04 800C7204 ADEA0000 */  sw         $t2, 0x0($t7)
/* C7E08 800C7208 1520FFFD */  bnez       $t1, .L800C7200_C7E00
/* C7E0C 800C720C 25EF0004 */   addiu     $t7, $t7, 0x4
/* C7E10 800C7210 08031C3C */  j          .L800C70F0_C7CF0
/* C7E14 800C7214 00000000 */   nop
/* C7E18 800C7218 24080003 */  addiu      $t0, $zero, 0x3
.L800C721C_C7E1C:
/* C7E1C 800C721C 0268082B */  sltu       $at, $s3, $t0
/* C7E20 800C7220 50200009 */  beql       $at, $zero, .L800C7248_C7E48
/* C7E24 800C7224 32490007 */   andi      $t1, $s2, 0x7
.L800C7228_C7E28:
/* C7E28 800C7228 92820000 */  lbu        $v0, 0x0($s4)
/* C7E2C 800C722C 26940001 */  addiu      $s4, $s4, 0x1
/* C7E30 800C7230 02621004 */  sllv       $v0, $v0, $s3
/* C7E34 800C7234 26730008 */  addiu      $s3, $s3, 0x8
/* C7E38 800C7238 0268082A */  slt        $at, $s3, $t0
/* C7E3C 800C723C 1420FFFA */  bnez       $at, .L800C7228_C7E28
/* C7E40 800C7240 02429025 */   or        $s2, $s2, $v0
/* C7E44 800C7244 32490007 */  andi       $t1, $s2, 0x7
.L800C7248_C7E48:
/* C7E48 800C7248 21290003 */  addi       $t1, $t1, 0x3 /* handwritten instruction */
/* C7E4C 800C724C 01129006 */  srlv       $s2, $s2, $t0
/* C7E50 800C7250 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7E54 800C7254 0329C823 */  subu       $t9, $t9, $t1
.L800C7258_C7E58:
/* C7E58 800C7258 2529FFFF */  addiu      $t1, $t1, -0x1
/* C7E5C 800C725C ADE00000 */  sw         $zero, 0x0($t7)
/* C7E60 800C7260 1520FFFD */  bnez       $t1, .L800C7258_C7E58
/* C7E64 800C7264 25EF0004 */   addiu     $t7, $t7, 0x4
/* C7E68 800C7268 08031C3C */  j          .L800C70F0_C7CF0
/* C7E6C 800C726C 240A0000 */   addiu     $t2, $zero, 0x0
.L800C7270_C7E70:
/* C7E70 800C7270 3C01800E */  lui        $at, %hi(gzip_inflate_input)
/* C7E74 800C7274 AC343CF8 */  sw         $s4, %lo(gzip_inflate_input)($at)
/* C7E78 800C7278 3C018013 */  lui        $at, %hi(gzip_bit_buffer)
/* C7E7C 800C727C 24080009 */  addiu      $t0, $zero, 0x9
/* C7E80 800C7280 AC32B090 */  sw         $s2, %lo(gzip_bit_buffer)($at)
/* C7E84 800C7284 AFA80038 */  sw         $t0, 0x38($sp)
/* C7E88 800C7288 3C02800F */  lui        $v0, %hi(gzip_cplext)
/* C7E8C 800C728C 3C018013 */  lui        $at, %hi(gzip_num_bits)
/* C7E90 800C7290 3C07800F */  lui        $a3, %hi(gzip_cplens)
/* C7E94 800C7294 24429992 */  addiu      $v0, $v0, %lo(gzip_cplext)
/* C7E98 800C7298 23A30034 */  addi       $v1, $sp, 0x34 /* handwritten instruction */
/* C7E9C 800C729C 23A80038 */  addi       $t0, $sp, 0x38 /* handwritten instruction */
/* C7EA0 800C72A0 AC33B094 */  sw         $s3, %lo(gzip_num_bits)($at)
/* C7EA4 800C72A4 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C7EA8 800C72A8 00112825 */  or         $a1, $zero, $s1
/* C7EAC 800C72AC 24060101 */  addiu      $a2, $zero, 0x101
/* C7EB0 800C72B0 24E79954 */  addiu      $a3, $a3, %lo(gzip_cplens)
/* C7EB4 800C72B4 AFA20010 */  sw         $v0, 0x10($sp)
/* C7EB8 800C72B8 AFA30014 */  sw         $v1, 0x14($sp)
/* C7EBC 800C72BC 0C0319F5 */  jal        gzip_huft_build
/* C7EC0 800C72C0 AFA80018 */   sw        $t0, 0x18($sp)
/* C7EC4 800C72C4 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C7EC8 800C72C8 00111080 */  sll        $v0, $s1, 2
/* C7ECC 800C72CC 24080006 */  addiu      $t0, $zero, 0x6
/* C7ED0 800C72D0 00822021 */  addu       $a0, $a0, $v0
/* C7ED4 800C72D4 AFA80040 */  sw         $t0, 0x40($sp)
/* C7ED8 800C72D8 3C02800F */  lui        $v0, %hi(gzip_cpdext)
/* C7EDC 800C72DC 3C07800F */  lui        $a3, %hi(gzip_cpdist)
/* C7EE0 800C72E0 244299EE */  addiu      $v0, $v0, %lo(gzip_cpdext)
/* C7EE4 800C72E4 23A3003C */  addi       $v1, $sp, 0x3C /* handwritten instruction */
/* C7EE8 800C72E8 23A80040 */  addi       $t0, $sp, 0x40 /* handwritten instruction */
/* C7EEC 800C72EC 00102825 */  or         $a1, $zero, $s0
/* C7EF0 800C72F0 24060000 */  addiu      $a2, $zero, 0x0
/* C7EF4 800C72F4 24E799B2 */  addiu      $a3, $a3, %lo(gzip_cpdist)
/* C7EF8 800C72F8 AFA20010 */  sw         $v0, 0x10($sp)
/* C7EFC 800C72FC AFA30014 */  sw         $v1, 0x14($sp)
/* C7F00 800C7300 0C0319F5 */  jal        gzip_huft_build
/* C7F04 800C7304 AFA80018 */   sw        $t0, 0x18($sp)
/* C7F08 800C7308 8FA40034 */  lw         $a0, 0x34($sp)
/* C7F0C 800C730C 8FA5003C */  lw         $a1, 0x3C($sp)
/* C7F10 800C7310 8FA60038 */  lw         $a2, 0x38($sp)
/* C7F14 800C7314 0C031D68 */  jal        gzip_inflate_codes
/* C7F18 800C7318 8FA70040 */   lw        $a3, 0x40($sp)
/* C7F1C 800C731C 8FBF0030 */  lw         $ra, 0x30($sp)
/* C7F20 800C7320 8FB4002C */  lw         $s4, 0x2C($sp)
/* C7F24 800C7324 8FB30028 */  lw         $s3, 0x28($sp)
/* C7F28 800C7328 8FB20024 */  lw         $s2, 0x24($sp)
/* C7F2C 800C732C 8FB10020 */  lw         $s1, 0x20($sp)
/* C7F30 800C7330 8FB0001C */  lw         $s0, 0x1C($sp)
/* C7F34 800C7334 03E00008 */  jr         $ra
/* C7F38 800C7338 27BD0540 */   addiu     $sp, $sp, 0x540

/* Handwritten function */
glabel gzip_inflate_fixed
/* C7F3C 800C733C 27BDFAD0 */  addiu      $sp, $sp, -0x530
/* C7F40 800C7340 AFBF001C */  sw         $ra, 0x1C($sp)
/* C7F44 800C7344 23AB0044 */  addi       $t3, $sp, 0x44 /* handwritten instruction */
/* C7F48 800C7348 24080024 */  addiu      $t0, $zero, 0x24
/* C7F4C 800C734C 24090008 */  addiu      $t1, $zero, 0x8
.L800C7350_C7F50:
/* C7F50 800C7350 2508FFFF */  addiu      $t0, $t0, -0x1
/* C7F54 800C7354 AD690000 */  sw         $t1, 0x0($t3)
/* C7F58 800C7358 AD690004 */  sw         $t1, 0x4($t3)
/* C7F5C 800C735C AD690008 */  sw         $t1, 0x8($t3)
/* C7F60 800C7360 AD69000C */  sw         $t1, 0xC($t3)
/* C7F64 800C7364 1500FFFA */  bnez       $t0, .L800C7350_C7F50
/* C7F68 800C7368 256B0010 */   addiu     $t3, $t3, 0x10
/* C7F6C 800C736C 2408001C */  addiu      $t0, $zero, 0x1C
/* C7F70 800C7370 24090009 */  addiu      $t1, $zero, 0x9
.L800C7374_C7F74:
/* C7F74 800C7374 2508FFFF */  addiu      $t0, $t0, -0x1
/* C7F78 800C7378 AD690000 */  sw         $t1, 0x0($t3)
/* C7F7C 800C737C AD690004 */  sw         $t1, 0x4($t3)
/* C7F80 800C7380 AD690008 */  sw         $t1, 0x8($t3)
/* C7F84 800C7384 AD69000C */  sw         $t1, 0xC($t3)
/* C7F88 800C7388 1500FFFA */  bnez       $t0, .L800C7374_C7F74
/* C7F8C 800C738C 256B0010 */   addiu     $t3, $t3, 0x10
/* C7F90 800C7390 24080006 */  addiu      $t0, $zero, 0x6
/* C7F94 800C7394 24090007 */  addiu      $t1, $zero, 0x7
.L800C7398_C7F98:
/* C7F98 800C7398 2508FFFF */  addiu      $t0, $t0, -0x1
/* C7F9C 800C739C AD690000 */  sw         $t1, 0x0($t3)
/* C7FA0 800C73A0 AD690004 */  sw         $t1, 0x4($t3)
/* C7FA4 800C73A4 AD690008 */  sw         $t1, 0x8($t3)
/* C7FA8 800C73A8 AD69000C */  sw         $t1, 0xC($t3)
/* C7FAC 800C73AC 1500FFFA */  bnez       $t0, .L800C7398_C7F98
/* C7FB0 800C73B0 256B0010 */   addiu     $t3, $t3, 0x10
/* C7FB4 800C73B4 24090008 */  addiu      $t1, $zero, 0x8
/* C7FB8 800C73B8 AD690000 */  sw         $t1, 0x0($t3)
/* C7FBC 800C73BC AD690004 */  sw         $t1, 0x4($t3)
/* C7FC0 800C73C0 AD690008 */  sw         $t1, 0x8($t3)
/* C7FC4 800C73C4 AD69000C */  sw         $t1, 0xC($t3)
/* C7FC8 800C73C8 AD690010 */  sw         $t1, 0x10($t3)
/* C7FCC 800C73CC AD690014 */  sw         $t1, 0x14($t3)
/* C7FD0 800C73D0 AD690018 */  sw         $t1, 0x18($t3)
/* C7FD4 800C73D4 AD69001C */  sw         $t1, 0x1C($t3)
/* C7FD8 800C73D8 24080007 */  addiu      $t0, $zero, 0x7
/* C7FDC 800C73DC AFA80038 */  sw         $t0, 0x38($sp)
/* C7FE0 800C73E0 3C02800F */  lui        $v0, %hi(gzip_cplext)
/* C7FE4 800C73E4 3C07800F */  lui        $a3, %hi(gzip_cplens)
/* C7FE8 800C73E8 24429992 */  addiu      $v0, $v0, %lo(gzip_cplext)
/* C7FEC 800C73EC 23A30020 */  addi       $v1, $sp, 0x20 /* handwritten instruction */
/* C7FF0 800C73F0 23A80024 */  addi       $t0, $sp, 0x24 /* handwritten instruction */
/* C7FF4 800C73F4 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C7FF8 800C73F8 24050120 */  addiu      $a1, $zero, 0x120
/* C7FFC 800C73FC 24060101 */  addiu      $a2, $zero, 0x101
/* C8000 800C7400 24E79954 */  addiu      $a3, $a3, %lo(gzip_cplens)
/* C8004 800C7404 AFA20010 */  sw         $v0, 0x10($sp)
/* C8008 800C7408 AFA30014 */  sw         $v1, 0x14($sp)
/* C800C 800C740C 0C0319F5 */  jal        gzip_huft_build
/* C8010 800C7410 AFA80018 */   sw        $t0, 0x18($sp)
/* C8014 800C7414 23AB0044 */  addi       $t3, $sp, 0x44 /* handwritten instruction */
/* C8018 800C7418 2408000A */  addiu      $t0, $zero, 0xA
/* C801C 800C741C 24090005 */  addiu      $t1, $zero, 0x5
.L800C7420_C8020:
/* C8020 800C7420 2508FFFF */  addiu      $t0, $t0, -0x1
/* C8024 800C7424 AD690000 */  sw         $t1, 0x0($t3)
/* C8028 800C7428 AD690004 */  sw         $t1, 0x4($t3)
/* C802C 800C742C AD690008 */  sw         $t1, 0x8($t3)
/* C8030 800C7430 1500FFFB */  bnez       $t0, .L800C7420_C8020
/* C8034 800C7434 256B000C */   addiu     $t3, $t3, 0xC
/* C8038 800C7438 3C02800F */  lui        $v0, %hi(gzip_cpdext)
/* C803C 800C743C 3C07800F */  lui        $a3, %hi(gzip_cpdist)
/* C8040 800C7440 244299EE */  addiu      $v0, $v0, %lo(gzip_cpdext)
/* C8044 800C7444 23A30028 */  addi       $v1, $sp, 0x28 /* handwritten instruction */
/* C8048 800C7448 23A8002C */  addi       $t0, $sp, 0x2C /* handwritten instruction */
/* C804C 800C744C AFA90040 */  sw         $t1, 0x40($sp)
/* C8050 800C7450 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C8054 800C7454 2405001E */  addiu      $a1, $zero, 0x1E
/* C8058 800C7458 24060000 */  addiu      $a2, $zero, 0x0
/* C805C 800C745C 24E799B2 */  addiu      $a3, $a3, %lo(gzip_cpdist)
/* C8060 800C7460 AFA20010 */  sw         $v0, 0x10($sp)
/* C8064 800C7464 AFA30014 */  sw         $v1, 0x14($sp)
/* C8068 800C7468 0C0319F5 */  jal        gzip_huft_build
/* C806C 800C746C AFA80018 */   sw        $t0, 0x18($sp)
/* C8070 800C7470 8FA40020 */  lw         $a0, 0x20($sp)
/* C8074 800C7474 8FA50028 */  lw         $a1, 0x28($sp)
/* C8078 800C7478 8FA60024 */  lw         $a2, 0x24($sp)
/* C807C 800C747C 0C031D68 */  jal        gzip_inflate_codes
/* C8080 800C7480 8FA7002C */   lw        $a3, 0x2C($sp)
/* C8084 800C7484 8FBF001C */  lw         $ra, 0x1C($sp)
/* C8088 800C7488 27BD0530 */  addiu      $sp, $sp, 0x530
/* C808C 800C748C 03E00008 */  jr         $ra
/* C8090 800C7490 00000000 */   nop

/* Handwritten function */
glabel gzip_inflate_stored
/* C8094 800C7494 3C0D8013 */  lui        $t5, %hi(gzip_num_bits)
/* C8098 800C7498 8DADB094 */  lw         $t5, %lo(gzip_num_bits)($t5)
/* C809C 800C749C 3C0C8013 */  lui        $t4, %hi(gzip_bit_buffer)
/* C80A0 800C74A0 8D8CB090 */  lw         $t4, %lo(gzip_bit_buffer)($t4)
/* C80A4 800C74A4 31A80007 */  andi       $t0, $t5, 0x7
/* C80A8 800C74A8 01A86822 */  sub        $t5, $t5, $t0 /* handwritten instruction */
/* C80AC 800C74AC 010C6006 */  srlv       $t4, $t4, $t0
/* C80B0 800C74B0 24080010 */  addiu      $t0, $zero, 0x10
/* C80B4 800C74B4 3C0F800E */  lui        $t7, %hi(gzip_inflate_input)
/* C80B8 800C74B8 3C0E800E */  lui        $t6, %hi(gzip_inflate_output)
/* C80BC 800C74BC 01A8082B */  sltu       $at, $t5, $t0
/* C80C0 800C74C0 8DEF3CF8 */  lw         $t7, %lo(gzip_inflate_input)($t7)
/* C80C4 800C74C4 10200008 */  beqz       $at, .L800C74E8_C80E8
/* C80C8 800C74C8 8DCE3CFC */   lw        $t6, %lo(gzip_inflate_output)($t6)
.L800C74CC_C80CC:
/* C80CC 800C74CC 91E20000 */  lbu        $v0, 0x0($t7)
/* C80D0 800C74D0 25EF0001 */  addiu      $t7, $t7, 0x1
/* C80D4 800C74D4 01A21004 */  sllv       $v0, $v0, $t5
/* C80D8 800C74D8 25AD0008 */  addiu      $t5, $t5, 0x8
/* C80DC 800C74DC 01A8082A */  slt        $at, $t5, $t0
/* C80E0 800C74E0 1420FFFA */  bnez       $at, .L800C74CC_C80CC
/* C80E4 800C74E4 01826025 */   or        $t4, $t4, $v0
.L800C74E8_C80E8:
/* C80E8 800C74E8 01A86822 */  sub        $t5, $t5, $t0 /* handwritten instruction */
/* C80EC 800C74EC 3189FFFF */  andi       $t1, $t4, 0xFFFF
/* C80F0 800C74F0 01A8082B */  sltu       $at, $t5, $t0
/* C80F4 800C74F4 10200008 */  beqz       $at, .L800C7518_C8118
/* C80F8 800C74F8 010C6006 */   srlv      $t4, $t4, $t0
.L800C74FC_C80FC:
/* C80FC 800C74FC 91E20000 */  lbu        $v0, 0x0($t7)
/* C8100 800C7500 25EF0001 */  addiu      $t7, $t7, 0x1
/* C8104 800C7504 01A21004 */  sllv       $v0, $v0, $t5
/* C8108 800C7508 25AD0008 */  addiu      $t5, $t5, 0x8
/* C810C 800C750C 01A8082A */  slt        $at, $t5, $t0
/* C8110 800C7510 1420FFFA */  bnez       $at, .L800C74FC_C80FC
/* C8114 800C7514 01826025 */   or        $t4, $t4, $v0
.L800C7518_C8118:
/* C8118 800C7518 31220003 */  andi       $v0, $t1, 0x3
/* C811C 800C751C 010C6006 */  srlv       $t4, $t4, $t0
/* C8120 800C7520 1040000A */  beqz       $v0, .L800C754C_C814C
/* C8124 800C7524 01A86822 */   sub       $t5, $t5, $t0 /* handwritten instruction */
/* C8128 800C7528 01224822 */  sub        $t1, $t1, $v0 /* handwritten instruction */
.L800C752C_C812C:
/* C812C 800C752C 91EA0000 */  lbu        $t2, 0x0($t7)
/* C8130 800C7530 2042FFFF */  addi       $v0, $v0, -0x1 /* handwritten instruction */
/* C8134 800C7534 21EF0001 */  addi       $t7, $t7, 0x1 /* handwritten instruction */
/* C8138 800C7538 21CE0001 */  addi       $t6, $t6, 0x1 /* handwritten instruction */
/* C813C 800C753C 1440FFFB */  bnez       $v0, .L800C752C_C812C
/* C8140 800C7540 A1CAFFFF */   sb        $t2, -0x1($t6)
/* C8144 800C7544 1120000D */  beqz       $t1, .L800C757C_C817C
/* C8148 800C7548 00000000 */   nop
.L800C754C_C814C:
/* C814C 800C754C 91E20000 */  lbu        $v0, 0x0($t7)
/* C8150 800C7550 2529FFFC */  addiu      $t1, $t1, -0x4
/* C8154 800C7554 25EF0004 */  addiu      $t7, $t7, 0x4
/* C8158 800C7558 A1C20000 */  sb         $v0, 0x0($t6)
/* C815C 800C755C 91E3FFFD */  lbu        $v1, -0x3($t7)
/* C8160 800C7560 25CE0004 */  addiu      $t6, $t6, 0x4
/* C8164 800C7564 A1C3FFFD */  sb         $v1, -0x3($t6)
/* C8168 800C7568 91EAFFFE */  lbu        $t2, -0x2($t7)
/* C816C 800C756C A1CAFFFE */  sb         $t2, -0x2($t6)
/* C8170 800C7570 91EBFFFF */  lbu        $t3, -0x1($t7)
/* C8174 800C7574 1520FFF5 */  bnez       $t1, .L800C754C_C814C
/* C8178 800C7578 A1CBFFFF */   sb        $t3, -0x1($t6)
.L800C757C_C817C:
/* C817C 800C757C 3C01800E */  lui        $at, %hi(gzip_inflate_input)
/* C8180 800C7580 AC2F3CF8 */  sw         $t7, %lo(gzip_inflate_input)($at)
/* C8184 800C7584 3C01800E */  lui        $at, %hi(gzip_inflate_output)
/* C8188 800C7588 AC2E3CFC */  sw         $t6, %lo(gzip_inflate_output)($at)
/* C818C 800C758C 3C018013 */  lui        $at, %hi(gzip_bit_buffer)
/* C8190 800C7590 AC2CB090 */  sw         $t4, %lo(gzip_bit_buffer)($at)
/* C8194 800C7594 3C018013 */  lui        $at, %hi(gzip_num_bits)
/* C8198 800C7598 03E00008 */  jr         $ra
/* C819C 800C759C AC2DB094 */   sw        $t5, %lo(gzip_num_bits)($at)

/* Handwritten function */
glabel gzip_inflate_codes
/* C81A0 800C75A0 27BDFFF0 */  addiu      $sp, $sp, -0x10
/* C81A4 800C75A4 3C0B800F */  lui        $t3, %hi(gzip_mask_bits)
/* C81A8 800C75A8 AFB20008 */  sw         $s2, 0x8($sp)
/* C81AC 800C75AC AFB10004 */  sw         $s1, 0x4($sp)
/* C81B0 800C75B0 AFB00000 */  sw         $s0, 0x0($sp)
/* C81B4 800C75B4 256B9A0C */  addiu      $t3, $t3, %lo(gzip_mask_bits)
/* C81B8 800C75B8 00061040 */  sll        $v0, $a2, 1
/* C81BC 800C75BC 00074040 */  sll        $t0, $a3, 1
/* C81C0 800C75C0 3C12800E */  lui        $s2, %hi(gzip_inflate_input)
/* C81C4 800C75C4 3C11800E */  lui        $s1, %hi(gzip_inflate_output)
/* C81C8 800C75C8 3C198013 */  lui        $t9, %hi(gzip_bit_buffer)
/* C81CC 800C75CC 3C108013 */  lui        $s0, %hi(gzip_num_bits)
/* C81D0 800C75D0 01621821 */  addu       $v1, $t3, $v0
/* C81D4 800C75D4 01684821 */  addu       $t1, $t3, $t0
/* C81D8 800C75D8 8E523CF8 */  lw         $s2, %lo(gzip_inflate_input)($s2)
/* C81DC 800C75DC 8E313CFC */  lw         $s1, %lo(gzip_inflate_output)($s1)
/* C81E0 800C75E0 8F39B090 */  lw         $t9, %lo(gzip_bit_buffer)($t9)
/* C81E4 800C75E4 8E10B094 */  lw         $s0, %lo(gzip_num_bits)($s0)
/* C81E8 800C75E8 946D0000 */  lhu        $t5, 0x0($v1)
/* C81EC 800C75EC 952C0000 */  lhu        $t4, 0x0($t1)
.L800C75F0_C81F0:
/* C81F0 800C75F0 0206082B */  sltu       $at, $s0, $a2
.L800C75F4_C81F4:
/* C81F4 800C75F4 50200009 */  beql       $at, $zero, .L800C761C_C821C
/* C81F8 800C75F8 032D1024 */   and       $v0, $t9, $t5
.L800C75FC_C81FC:
/* C81FC 800C75FC 92420000 */  lbu        $v0, 0x0($s2)
/* C8200 800C7600 26520001 */  addiu      $s2, $s2, 0x1
/* C8204 800C7604 02021004 */  sllv       $v0, $v0, $s0
/* C8208 800C7608 26100008 */  addiu      $s0, $s0, 0x8
/* C820C 800C760C 0206082A */  slt        $at, $s0, $a2
/* C8210 800C7610 1420FFFA */  bnez       $at, .L800C75FC_C81FC
/* C8214 800C7614 0322C825 */   or        $t9, $t9, $v0
/* C8218 800C7618 032D1024 */  and        $v0, $t9, $t5
.L800C761C_C821C:
/* C821C 800C761C 000210C0 */  sll        $v0, $v0, 3
/* C8220 800C7620 00827821 */  addu       $t7, $a0, $v0
/* C8224 800C7624 91F80000 */  lbu        $t8, 0x0($t7)
/* C8228 800C7628 2B010011 */  slti       $at, $t8, 0x11
/* C822C 800C762C 5420001A */  bnel       $at, $zero, .L800C7698_C8298
/* C8230 800C7630 91E20001 */   lbu       $v0, 0x1($t7)
/* C8234 800C7634 81E30001 */  lb         $v1, 0x1($t7)
.L800C7638_C8238:
/* C8238 800C7638 2318FFF0 */  addi       $t8, $t8, -0x10 /* handwritten instruction */
/* C823C 800C763C 02038022 */  sub        $s0, $s0, $v1 /* handwritten instruction */
/* C8240 800C7640 0218082B */  sltu       $at, $s0, $t8
/* C8244 800C7644 10200008 */  beqz       $at, .L800C7668_C8268
/* C8248 800C7648 0079C806 */   srlv      $t9, $t9, $v1
.L800C764C_C824C:
/* C824C 800C764C 92420000 */  lbu        $v0, 0x0($s2)
/* C8250 800C7650 26520001 */  addiu      $s2, $s2, 0x1
/* C8254 800C7654 02021004 */  sllv       $v0, $v0, $s0
/* C8258 800C7658 26100008 */  addiu      $s0, $s0, 0x8
/* C825C 800C765C 0218082A */  slt        $at, $s0, $t8
/* C8260 800C7660 1420FFFA */  bnez       $at, .L800C764C_C824C
/* C8264 800C7664 0322C825 */   or        $t9, $t9, $v0
.L800C7668_C8268:
/* C8268 800C7668 00181040 */  sll        $v0, $t8, 1
/* C826C 800C766C 004B1021 */  addu       $v0, $v0, $t3
/* C8270 800C7670 94490000 */  lhu        $t1, 0x0($v0)
/* C8274 800C7674 8DE80004 */  lw         $t0, 0x4($t7)
/* C8278 800C7678 01394824 */  and        $t1, $t1, $t9
/* C827C 800C767C 000948C0 */  sll        $t1, $t1, 3
/* C8280 800C7680 01097820 */  add        $t7, $t0, $t1 /* handwritten instruction */
/* C8284 800C7684 91F80000 */  lbu        $t8, 0x0($t7)
/* C8288 800C7688 2F010011 */  sltiu      $at, $t8, 0x11
/* C828C 800C768C 5020FFEA */  beql       $at, $zero, .L800C7638_C8238
/* C8290 800C7690 81E30001 */   lb        $v1, 0x1($t7)
/* C8294 800C7694 91E20001 */  lbu        $v0, 0x1($t7)
.L800C7698_C8298:
/* C8298 800C7698 24010010 */  addiu      $at, $zero, 0x10
/* C829C 800C769C 0059C806 */  srlv       $t9, $t9, $v0
/* C82A0 800C76A0 17010005 */  bne        $t8, $at, .L800C76B8_C82B8
/* C82A4 800C76A4 02028022 */   sub       $s0, $s0, $v0 /* handwritten instruction */
/* C82A8 800C76A8 95E20004 */  lhu        $v0, 0x4($t7)
/* C82AC 800C76AC 26310001 */  addiu      $s1, $s1, 0x1
/* C82B0 800C76B0 08031D7C */  j          .L800C75F0_C81F0
/* C82B4 800C76B4 A222FFFF */   sb        $v0, -0x1($s1)
.L800C76B8_C82B8:
/* C82B8 800C76B8 2401000F */  addiu      $at, $zero, 0xF
/* C82BC 800C76BC 13010068 */  beq        $t8, $at, .L800C7860_C8460
/* C82C0 800C76C0 0218082B */   sltu      $at, $s0, $t8
/* C82C4 800C76C4 50200009 */  beql       $at, $zero, .L800C76EC_C82EC
/* C82C8 800C76C8 00181040 */   sll       $v0, $t8, 1
.L800C76CC_C82CC:
/* C82CC 800C76CC 92420000 */  lbu        $v0, 0x0($s2)
/* C82D0 800C76D0 26520001 */  addiu      $s2, $s2, 0x1
/* C82D4 800C76D4 02021004 */  sllv       $v0, $v0, $s0
/* C82D8 800C76D8 26100008 */  addiu      $s0, $s0, 0x8
/* C82DC 800C76DC 0218082A */  slt        $at, $s0, $t8
/* C82E0 800C76E0 1420FFFA */  bnez       $at, .L800C76CC_C82CC
/* C82E4 800C76E4 0322C825 */   or        $t9, $t9, $v0
/* C82E8 800C76E8 00181040 */  sll        $v0, $t8, 1
.L800C76EC_C82EC:
/* C82EC 800C76EC 004B1021 */  addu       $v0, $v0, $t3
/* C82F0 800C76F0 94490000 */  lhu        $t1, 0x0($v0)
/* C82F4 800C76F4 95E80004 */  lhu        $t0, 0x4($t7)
/* C82F8 800C76F8 02188022 */  sub        $s0, $s0, $t8 /* handwritten instruction */
/* C82FC 800C76FC 0207082B */  sltu       $at, $s0, $a3
/* C8300 800C7700 01394824 */  and        $t1, $t1, $t9
/* C8304 800C7704 0319C806 */  srlv       $t9, $t9, $t8
/* C8308 800C7708 10200008 */  beqz       $at, .L800C772C_C832C
/* C830C 800C770C 01097021 */   addu      $t6, $t0, $t1
.L800C7710_C8310:
/* C8310 800C7710 92420000 */  lbu        $v0, 0x0($s2)
/* C8314 800C7714 26520001 */  addiu      $s2, $s2, 0x1
/* C8318 800C7718 02021004 */  sllv       $v0, $v0, $s0
/* C831C 800C771C 26100008 */  addiu      $s0, $s0, 0x8
/* C8320 800C7720 0207082A */  slt        $at, $s0, $a3
/* C8324 800C7724 1420FFFA */  bnez       $at, .L800C7710_C8310
/* C8328 800C7728 0322C825 */   or        $t9, $t9, $v0
.L800C772C_C832C:
/* C832C 800C772C 01991024 */  and        $v0, $t4, $t9
/* C8330 800C7730 000210C0 */  sll        $v0, $v0, 3
/* C8334 800C7734 00A27821 */  addu       $t7, $a1, $v0
/* C8338 800C7738 91F80000 */  lbu        $t8, 0x0($t7)
/* C833C 800C773C 2B010011 */  slti       $at, $t8, 0x11
/* C8340 800C7740 5420001A */  bnel       $at, $zero, .L800C77AC_C83AC
/* C8344 800C7744 91E20001 */   lbu       $v0, 0x1($t7)
/* C8348 800C7748 91E80001 */  lbu        $t0, 0x1($t7)
.L800C774C_C834C:
/* C834C 800C774C 2318FFF0 */  addi       $t8, $t8, -0x10 /* handwritten instruction */
/* C8350 800C7750 02088022 */  sub        $s0, $s0, $t0 /* handwritten instruction */
/* C8354 800C7754 0218082B */  sltu       $at, $s0, $t8
/* C8358 800C7758 10200008 */  beqz       $at, .L800C777C_C837C
/* C835C 800C775C 0119C806 */   srlv      $t9, $t9, $t0
.L800C7760_C8360:
/* C8360 800C7760 92420000 */  lbu        $v0, 0x0($s2)
/* C8364 800C7764 26520001 */  addiu      $s2, $s2, 0x1
/* C8368 800C7768 02021004 */  sllv       $v0, $v0, $s0
/* C836C 800C776C 26100008 */  addiu      $s0, $s0, 0x8
/* C8370 800C7770 0218082A */  slt        $at, $s0, $t8
/* C8374 800C7774 1420FFFA */  bnez       $at, .L800C7760_C8360
/* C8378 800C7778 0322C825 */   or        $t9, $t9, $v0
.L800C777C_C837C:
/* C837C 800C777C 00181040 */  sll        $v0, $t8, 1
/* C8380 800C7780 004B1021 */  addu       $v0, $v0, $t3
/* C8384 800C7784 94490000 */  lhu        $t1, 0x0($v0)
/* C8388 800C7788 8DE80004 */  lw         $t0, 0x4($t7)
/* C838C 800C778C 01394824 */  and        $t1, $t1, $t9
/* C8390 800C7790 000948C0 */  sll        $t1, $t1, 3
/* C8394 800C7794 01097821 */  addu       $t7, $t0, $t1
/* C8398 800C7798 91F80000 */  lbu        $t8, 0x0($t7)
/* C839C 800C779C 2F010011 */  sltiu      $at, $t8, 0x11
/* C83A0 800C77A0 5020FFEA */  beql       $at, $zero, .L800C774C_C834C
/* C83A4 800C77A4 91E80001 */   lbu       $t0, 0x1($t7)
/* C83A8 800C77A8 91E20001 */  lbu        $v0, 0x1($t7)
.L800C77AC_C83AC:
/* C83AC 800C77AC 02028022 */  sub        $s0, $s0, $v0 /* handwritten instruction */
/* C83B0 800C77B0 0218082B */  sltu       $at, $s0, $t8
/* C83B4 800C77B4 10200008 */  beqz       $at, .L800C77D8_C83D8
/* C83B8 800C77B8 0059C806 */   srlv      $t9, $t9, $v0
.L800C77BC_C83BC:
/* C83BC 800C77BC 92420000 */  lbu        $v0, 0x0($s2)
/* C83C0 800C77C0 26520001 */  addiu      $s2, $s2, 0x1
/* C83C4 800C77C4 02021004 */  sllv       $v0, $v0, $s0
/* C83C8 800C77C8 26100008 */  addiu      $s0, $s0, 0x8
/* C83CC 800C77CC 0218082A */  slt        $at, $s0, $t8
/* C83D0 800C77D0 1420FFFA */  bnez       $at, .L800C77BC_C83BC
/* C83D4 800C77D4 0322C825 */   or        $t9, $t9, $v0
.L800C77D8_C83D8:
/* C83D8 800C77D8 00181040 */  sll        $v0, $t8, 1
/* C83DC 800C77DC 004B1021 */  addu       $v0, $v0, $t3
/* C83E0 800C77E0 94490000 */  lhu        $t1, 0x0($v0)
/* C83E4 800C77E4 95E30004 */  lhu        $v1, 0x4($t7)
/* C83E8 800C77E8 31C20003 */  andi       $v0, $t6, 0x3
/* C83EC 800C77EC 01394824 */  and        $t1, $t1, $t9
/* C83F0 800C77F0 02234022 */  sub        $t0, $s1, $v1 /* handwritten instruction */
/* C83F4 800C77F4 01094022 */  sub        $t0, $t0, $t1 /* handwritten instruction */
/* C83F8 800C77F8 0319C806 */  srlv       $t9, $t9, $t8
/* C83FC 800C77FC 1040000A */  beqz       $v0, .L800C7828_C8428
/* C8400 800C7800 02188022 */   sub       $s0, $s0, $t8 /* handwritten instruction */
/* C8404 800C7804 01C27022 */  sub        $t6, $t6, $v0 /* handwritten instruction */
.L800C7808_C8408:
/* C8408 800C7808 910A0000 */  lbu        $t2, 0x0($t0)
/* C840C 800C780C 2042FFFF */  addi       $v0, $v0, -0x1 /* handwritten instruction */
/* C8410 800C7810 21080001 */  addi       $t0, $t0, 0x1 /* handwritten instruction */
/* C8414 800C7814 22310001 */  addi       $s1, $s1, 0x1 /* handwritten instruction */
/* C8418 800C7818 1440FFFB */  bnez       $v0, .L800C7808_C8408
/* C841C 800C781C A22AFFFF */   sb        $t2, -0x1($s1)
/* C8420 800C7820 51C0FF74 */  beql       $t6, $zero, .L800C75F4_C81F4
/* C8424 800C7824 0206082B */   sltu      $at, $s0, $a2
.L800C7828_C8428:
/* C8428 800C7828 91020000 */  lbu        $v0, 0x0($t0)
/* C842C 800C782C 25CEFFFC */  addiu      $t6, $t6, -0x4
/* C8430 800C7830 25080004 */  addiu      $t0, $t0, 0x4
/* C8434 800C7834 A2220000 */  sb         $v0, 0x0($s1)
/* C8438 800C7838 9103FFFD */  lbu        $v1, -0x3($t0)
/* C843C 800C783C 26310004 */  addiu      $s1, $s1, 0x4
/* C8440 800C7840 A223FFFD */  sb         $v1, -0x3($s1)
/* C8444 800C7844 9109FFFE */  lbu        $t1, -0x2($t0)
/* C8448 800C7848 A229FFFE */  sb         $t1, -0x2($s1)
/* C844C 800C784C 910AFFFF */  lbu        $t2, -0x1($t0)
/* C8450 800C7850 15C0FFF5 */  bnez       $t6, .L800C7828_C8428
/* C8454 800C7854 A22AFFFF */   sb        $t2, -0x1($s1)
/* C8458 800C7858 08031D7C */  j          .L800C75F0_C81F0
/* C845C 800C785C 00000000 */   nop
.L800C7860_C8460:
/* C8460 800C7860 3C01800E */  lui        $at, %hi(gzip_inflate_input)
/* C8464 800C7864 AC323CF8 */  sw         $s2, %lo(gzip_inflate_input)($at)
/* C8468 800C7868 3C01800E */  lui        $at, %hi(gzip_inflate_output)
/* C846C 800C786C AC313CFC */  sw         $s1, %lo(gzip_inflate_output)($at)
/* C8470 800C7870 3C018013 */  lui        $at, %hi(gzip_bit_buffer)
/* C8474 800C7874 AC39B090 */  sw         $t9, %lo(gzip_bit_buffer)($at)
/* C8478 800C7878 3C018013 */  lui        $at, %hi(gzip_num_bits)
/* C847C 800C787C AC30B094 */  sw         $s0, %lo(gzip_num_bits)($at)
/* C8480 800C7880 8FB20008 */  lw         $s2, 0x8($sp)
/* C8484 800C7884 8FB10004 */  lw         $s1, 0x4($sp)
/* C8488 800C7888 8FB00000 */  lw         $s0, 0x0($sp)
/* C848C 800C788C 03E00008 */  jr         $ra
/* C8490 800C7890 27BD0010 */   addiu     $sp, $sp, 0x10
/* C8494 800C7894 00000000 */  nop
/* C8498 800C7898 00000000 */  nop
/* C849C 800C789C 00000000 */  nop
